### ISSUE TITLE
Need more meaningful error message

### ISSUE THREAD

**Issue by Sequoia** [Microsoft/vscode-eslint#104]
> Failed to load eslint library. Please install eslint in your workspace folder using 'npm install eslint' or globally using 'npm install -g eslint' and then press Retry.

Issue was, in fact, that my eslint install was broken somehow (it's happening to me a lot, I'm not sure why):
```
bash-3.2$ ./node_modules/.bin/eslint
module.js:327
    throw err;
    ^

Error: Cannot find module './debug'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/a/b/c/node_modules/debug/node.js:15:28)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
bash-3.2$ ./node_modules/.bin/eslint
module.js:327
    throw err;
    ^
```

## Proposal

Differentiate "ESLint not found" message (above) with "ESLint failed"

**Comment by dbaeumer** [comment]
@Sequoia you should now see the output of what fails duing loading in the ESLint Output (Ctrl+Shift+U)
