### ISSUE TITLE
Format on save took to long to process

### ISSUE THREAD

**Issue by petrnymsa** [microsoft/vscode-eslint#1058]
ESLint version: 2.1.8
VSCode: 1.48.2
OS Version: Windows version 2004, OS Build 19041

When saving the file, the eslint formatter takes too long to format and save the file. Unfornutaley this issue happens very randomly. 

The message box with the following message appears: `Saving 'xzy.ts': Running 'ESLint' Formatter` and took about 2 seconds. 

Within developer console, i could see
```
potential listener LEAK detected, having 1146 listeners already. MOST frequent listener 
Aborted onWillSaveTextDocument-event after 1750ms
```

**Comment by dbaeumer** [comment]
@petrnymsa which version of ESLint are you using. The latest version doesn't use `onWillSaveTextDocument`. It uses code action on save instead. 

And could you please enable debugging using the `eslint.debug` setting. The ESLint output channel will then contain a trace showing what takes the extra amount of time.

**Comment by petrnymsa** [comment]
@dbaeumer 
Installed version: 
```
+-- eslint@6.6.0
+-- eslint-config-airbnb@18.0.1
+-- eslint-plugin-import@2.18.2
+-- eslint-plugin-jsx-a11y@6.2.3
+-- eslint-plugin-react@7.14.3
+-- eslint-plugin-react-hooks@1.7.0
```
VSCode plugin version: 2.1.8
-----------------------------------
I've turned on debug mode, as as soon as possible I will add more info. Like I said it occurs very randomly and its hard to reproduce it.

**Comment by dbaeumer** [comment]
Thanks!

**Comment by petrnymsa** [comment]
@dbaeumer Got little progress. 

```
2020-09-01T15:21:24.841Z eslint:linter Linting code for D:\dev\PROJECT\application\src\components\forms\form.test.tsx (pass 1)
2020-09-01T15:21:24.841Z eslint:linter Verify
2020-09-01T15:21:24.841Z eslint:linter With ConfigArray: D:\dev\PROJECT\application\src\components\forms\form.test.tsx
2020-09-01T15:21:31.160Z eslint:linter Parsing error: "parserOptions.project" has been set for @typescript-eslint/parser.
The file does not match your project config: src\components\forms\form.test.tsx.
The file must be included in at least one of the projects provided.
Error: "parserOptions.project" has been set for @typescript-eslint/parser.
The file does not match your project config: src\components\forms\form.test.tsx.
The file must be included in at least one of the projects provided.
    at Object.createProjectProgram (D:\dev\PROJECT\application\node_modules\@typescript-eslint\parser\node_modules\@typescript-eslint\typescript-estree\dist\create-program\createProjectProgram.js:70:15)
    at getProgramAndAST (D:\dev\PROJECT\application\node_modules\@typescript-eslint\parser\node_modules\@typescript-eslint\typescript-estree\dist\parser.js:63:32)
    at Object.parseAndGenerateServices (D:\dev\PROJECT\application\node_modules\@typescript-eslint\parser\node_modules\@typescript-eslint\typescript-estree\dist\parser.js:363:30)
    at Object.parseForESLint (D:\dev\PROJECT\application\node_modules\@typescript-eslint\parser\dist\parser.js:53:51)
    at parse (D:\dev\PROJECT\application\node_modules\eslint\lib\linter\linter.js:640:22)
    at Linter._verifyWithoutProcessors (D:\dev\PROJECT\application\node_modules\eslint\lib\linter\linter.js:1111:33)
    at Linter._verifyWithConfigArray (D:\dev\PROJECT\application\node_modules\eslint\lib\linter\linter.js:1255:21)
    at Linter.verify (D:\dev\PROJECT\application\node_modules\eslint\lib\linter\linter.js:1210:25)
    at Linter.verifyAndFix (D:\dev\PROJECT\application\node_modules\eslint\lib\linter\linter.js:1400:29)
    at verifyText (D:\dev\PROJECT\application\node_modules\eslint\lib\cli-engine\cli-engine.js:231:48)
2020-09-01T15:21:31.160Z eslint:linter Generating fixed text for D:\dev\PROJECT\application\src\components\forms\form.test.tsx (pass 1)
2020-09-01T15:21:31.160Z eslint:source-code-fixer Applying fixes
2020-09-01T15:21:31.160Z eslint:source-code-fixer shouldFix parameter was false, not attempting fixes
2020-09-01T15:21:31.162Z eslint:cli-engine Linting complete in: 6327ms
```
Sometimes, more often, when creating new file this error appears `parserOptions.project" has been set for @typescript-eslint/parser.` 
This slower save like I said occurs randomly and still not have a way to reproduce it.

**Comment by petrnymsa** [comment]
@dbaeumer  Can confirm once more, different file, same error

**Comment by dbaeumer** [comment]
@petrnymsa this is very wired and somehow outside of my code. It is inside the TS eslint plugin. What happens if you run eslint in the terminal in that state?

**Comment by hengkx** [comment]
Rule                               | Time (ms) | Relative
:----------------------------------|----------:|--------:
@typescript-eslint/no-implied-eval |  3492.658 |    18.8%
import/no-named-as-default         |  1726.897 |     9.3%
import/named                       |  1334.207 |     7.2%
import/no-extraneous-dependencies  |  1091.333 |     5.9%
import/no-unresolved               |   977.847 |     5.3%
import/order                       |   677.954 |     3.6%
import/no-duplicates               |   552.529 |     3.0%
import/no-self-import              |   544.598 |     2.9%
react/sort-comp                    |   537.855 |     2.9%
react/no-deprecated                |   510.587 |     2.7%
Rule | Time (ms) | Relative
:----|----------:|--------:

**Comment by dbaeumer** [comment]
@hengkx how did you produce these numbers ?

**Comment by petrnymsa** [comment]
> @petrnymsa this is very wired and somehow outside of my code. It is inside the TS eslint plugin. What happens if you run eslint in the terminal in that state?

Sorry for the late response. Unfortunately, I was not able to verify this as the issue happens randomly without any pattern to reproduce it. 
However, through CLI it seems without any issues.

**Comment by dbaeumer** [comment]
This is very hard to understand without a reproducible case. I still think that it is something in ESLint itself and not with the extension.
