### ISSUE TITLE
Plugin stops working when specifying options for sort-imports rule

### ISSUE THREAD

**Issue by mdazy** [microsoft/vscode-eslint#1063]
Using eslint 7.8.1 and ESLint plugin 2.1.8.

I'm in the process of adding the `sort-imports` rule in our code base. Adding this in the `.eslintrc.json` file works fine:
```js
 "rules": {
    // enforce import ordering
    "sort-imports": "warn"
}
```
However, adding options to customize the rule does not:
```js
 "rules": {
   // enforce import ordering but allow groups
    "sort-imports": ["warn", { "allowSeparatedGroups": true }],
}
```
This ends up with the plugin reporting one of these:
```
[Error - 11:40:29 AM] Request textDocument/codeAction failed.
  Message: Request textDocument/codeAction failed with message: .eslintrc.json:
	Configuration for rule "sort-imports" is invalid:
	Value {"allowSeparatedGroups":true,"ignoreCase":false,"ignoreDeclarationSort":false,"ignoreMemberSort":false} should NOT have additional properties.

  Code: -32603
```
or
```
(node:63756) UnhandledPromiseRejectionWarning: Error: .eslintrc.json:
	Configuration for rule "sort-imports" is invalid:
	Value {"allowSeparatedGroups":true,"ignoreCase":false,"ignoreDeclarationSort":false,"ignoreMemberSort":false} should NOT have additional properties.

    at validateRuleOptions (D:\Work\Web\property-model-update\node_modules\eslint\lib\shared\config-validator.js:132:19)
    at D:\Work\Web\property-model-update\node_modules\eslint\lib\shared\config-validator.js:187:9
    at Array.forEach (<anonymous>)
    at validateRules (D:\Work\Web\property-model-update\node_modules\eslint\lib\shared\config-validator.js:184:30)
    at validateConfigArray (D:\Work\Web\property-model-update\node_modules\eslint\lib\shared\config-validator.js:312:9)
    at CascadingConfigArrayFactory._finalizeConfigArray (D:\Work\Web\property-model-update\node_modules\eslint\lib\cli-engine\cascading-config-array-factory.js:464:13)
    at CascadingConfigArrayFactory.getConfigArrayForFile (D:\Work\Web\property-model-update\node_modules\eslint\lib\cli-engine\cascading-config-array-factory.js:275:21)
    at CLIEngine.getConfigForFile (D:\Work\Web\property-model-update\node_modules\eslint\lib\cli-engine\cli-engine.js:933:14)
    at c:\Users\dazy\.vscode\extensions\dbaeumer.vscode-eslint-2.1.8\server\out\eslintServer.js:1:37396
    at le (c:\Users\dazy\.vscode\extensions\dbaeumer.vscode-eslint-2.1.8\server\out\eslintServer.js:1:46704)
```
After that the plugin appears to stop entirely - in-code highlights are not updated, including for other rules.
Manually running eslint CLI on the files with that same configuration file works as expected.

**Comment by dbaeumer** [comment]
@mdazy can you please provide me with a GitHub repository I can clone that demos what you are experiencing.

**Comment by dbaeumer** [comment]
The error is thrown by the eslint npm module itseld (`node_modules\eslint\lib\shared\config-validator.js:187:9`) so to my knowledge the terminal should produce the same problem.

**Comment by mdazy** [comment]
I expected as much, but CLI run seems to be working.
Working on extracting a minimal repro.

**Comment by mdazy** [comment]
Tried hard to repro, but no luck. I eventually restarted VSCode on my main project and of course everything's running fine now.
I thought maybe upgrading eslint under the plugin's feet might have caused this but I tried to redo the same version changes back and forth and still no problem.
Still no clue what might have happened, but I'll close this as a non-issue.
Sorry for the trouble.
