### ISSUE TITLE
Eslint running times error: Failed to load plugin 'js' declared in 'CLIOptions': Cannot find module 'eslint-plugin-js'

### ISSUE THREAD

**Issue by Joshua-Leee** [microsoft/vscode-eslint#1111]
I have the ESlint plug-in installed in the VSCode editor, and I also have the ESlint tool installed globally, but eslint always reports this error whether it's on the VUE project or the React project：
```
Failed to load plugin 'js' declared in 'CLIOptions': Cannot find module 'eslint-plugin-js'
Require stack:
- /Applications/MAMP/htdocs/shengxue/admin-backend/__placeholder__.js
Happened while validating /Applications/MAMP/htdocs/shengxue/admin-backend/src/App.vue
This can happen for a couple of reasons:
1. The plugin name is spelled incorrectly in an ESLint configuration file (e.g. .eslintrc).
2. If ESLint is installed globally, then make sure 'eslint-plugin-js' is installed globally as well.
3. If ESLint is installed locally, then 'eslint-plugin-js' isn't installed correctly.

Consider running eslint --debug /Applications/MAMP/htdocs/shengxue/admin-backend/src/App.vue from a terminal to obtain a trace about the configuration files used.
```
I have even reinstalled Vscode several times, but it still doesn't work. The following is the content of my vscode configuration file. I hope someone can give me some Suggestions on how to solve this problem:
```
{
  "workbench.colorTheme": "One Dark Pro",
  "workbench.iconTheme": "vscode-icons",
  "editor.wordWrap": "on",
  "cssrem.rootFontSize": 100,
  "editor.detectIndentation": false,
  "editor.tabSize": 2,
  "editor.formatOnSave": true,
  "editor.formatOnPaste": true,
  "javascript.updateImportsOnFileMove.enabled": "always",
  "files.associations": {
    "*.wxss": "css",
    "*.tpl": "html",
    "*.wxml": "wxml",
    "*.vue": "vue",
    "*.scss": "scss",
    "*.cjson": "jsonc",
    "*.wxs": "javascript"
  },
  "emmet.triggerExpansionOnTab": true,
  "emmet.includeLanguages": {
    "vue-html": "html",
    "vue": "html",
    "wxml": "html"
  },
  "eslint.options": {
    "plugins": ["js", "vue", "jsx", "scss"]
  },
  "eslint.validate": ["javascript", "javascriptreact", "html", "vue", "jsx"],
  "liveServer.settings.donotShowInfoMsg": true,
  "javascript.implicitProjectConfig.experimentalDecorators": true,
  "workbench.statusBar.visible": true,
  "workbench.activityBar.visible": true,
  "extensions.autoUpdate": true,
  "git.confirmSync": false,
  "git.autofetch": true,
  "git.enableSmartCommit": true,
  "search.followSymlinks": false,
  "window.zoomLevel": 0,
  "terminal.integrated.rendererType": "dom",
  "[less]": {
    "editor.defaultFormatter": "esbenp.prettier-vscode"
  },
  "typescript.updateImportsOnFileMove.enabled": "always",
  "[javascript]": {
    "editor.defaultFormatter": "esbenp.prettier-vscode"
  },
  "[json]": {
    "editor.defaultFormatter": "esbenp.prettier-vscode"
  },
  "[vue]": {
    "editor.defaultFormatter": "octref.vetur"
  },
  "[javascriptreact]": {
    "editor.defaultFormatter": "esbenp.prettier-vscode"
  },
  "prettier.jsxBracketSameLine": true,
  "prettier.singleQuote": true,
  "prettier.jsxSingleQuote": true,
  "prettier.semi": false,
  "vetur.format.defaultFormatter.html": "prettyhtml",
  "vetur.format.defaultFormatter.js": "prettier-eslint",
  "vetur.format.defaultFormatterOptions": {
    "prettyhtml": {
      "printWidth": 100,
      "singleQuote": false,
      "wrapAttributes": true,
      "sortAttributes": true
    },
    "prettier": {
      "semi": false,
      "singleQuote": true,
      "eslintIntegration": true,
      "parser": "babylon"
    }
  },
  "typescript.locale": "zh-CN",
  "editor.codeActionsOnSave": {
    "source.fixAll.eslint": true
  },
  "fileheader.Author": "Joshua",
  "fileheader.LastModifiedBy": "Joshua",
  "jsdoc.author": "Joshua",
  "editor.fontSize": 14,
  "merge-conflict.autoNavigateNextConflict.enabled": true,
  "eslint.alwaysShowStatus": true,
  "eslint.packageManager": "yarn"
}
```
I installed ESlint globally with the 'YARN Global add Eslint' command and was prompted with success. Then I initialized with the 'eslint -- init' command, but again an error was reported:
```
➜  ~ yarn global add eslint
yarn global v1.22.10
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
[4/4] 🔨  Building fresh packages...

success Installed "eslint@7.13.0" with binaries:
      - eslint
✨  Done in 15.62s.
➜  ~ eslint --init
✔ How would you like to use ESLint? · problems
✔ What type of modules does your project use? · esm
✔ Which framework does your project use? · vue
✔ Does your project use TypeScript? · No / Yes
✔ Where does your code run? · browser, node
✔ What format do you want your config file to be in? · JavaScript

Oops! Something went wrong! :(

ESLint: 7.13.0

Error: Could not find a package.json file. Run 'npm init' to create one.
    at check (/Users/Joshua/.config/yarn/global/node_modules/eslint/lib/init/npm-utils.js:104:15)
    at Object.checkDevDeps (/Users/Joshua/.config/yarn/global/node_modules/eslint/lib/init/npm-utils.js:156:12)
    at getModulesList (/Users/Joshua/.config/yarn/global/node_modules/eslint/lib/init/config-initializer.js:131:40)
    at /Users/Joshua/.config/yarn/global/node_modules/eslint/lib/init/config-initializer.js:590:29
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async main (/Users/Joshua/.config/yarn/global/node_modules/eslint/bin/eslint.js:137:9)
➜  ~ 

```
The above is all my questions. I didn't find the answer I wanted in Google, so I came here to put forward the following questions. I hope someone can give me some Suggestions

OS: OS X 10.15.3 
VSCode: 1.51.0
Node: 14.15.0
NPM: 6.14.8
ESLint: 7.13.0

**Comment by dbaeumer** [comment]
@Joshua-Leee this looks like a problem with ESLint itself. If you try to run ESLint in the terminal does it work? The extension only works correctly if validation works correctly in the terminal.

**Comment by Joshua-Leee** [comment]
> @ Joshua-Leee，这似乎是ESLint本身的问题。如果您尝试在终端中运行ESLint，它可以工作吗？仅当终端中的验证正常工作时，该扩展程序才能正常工作。

**Comment by Joshua-Leee** [comment]
I reinstalled Node, NPM, and YARN, and now this is the case. I run my project on the ZSH terminal on MAC, and ZSH shows some esLINt detection tips, as follows:

> @Joshua-Leee this looks like a problem with ESLint itself. If you try to run ESLint in the terminal does it work? The extension only works correctly if validation works correctly in the terminal.

I reinstalled Node, NPM, and YARN, and now this is the case. I run my project on the ZSH terminal on MAC, and ZSH shows some esLINt detection tips, as follows:
```
Line 60:6:   React Hook useCallback has a missing dependency: 'setAuthRole'. Either include it or remove the dependency array. If 'setAuthRole' changes too often, find the parent component that defines it and wrap that definition in useCallback  react-hooks/exhaustive-deps
```
I think Eslint is working, but when I edit my code in Vscode, Eslint still prompts that it doesn't load:
```
[Info  - 4:41:58 PM] ESLint server is starting
[Info  - 4:41:59 PM] ESLint server running in node v12.14.1
[Info  - 4:42:00 PM] ESLint server is running.
[Info  - 4:42:00 PM] ESLint library loaded from: /Applications/MAMP/htdocs/react-demo/teach-system-react/node_modules/_eslint@6.8.0@eslint/lib/api.js
[Error - 4:42:01 PM] 
Failed to load plugin 'js' declared in 'CLIOptions': Cannot find module 'eslint-plugin-js'
Require stack:
- /Applications/MAMP/htdocs/react-demo/teach-system-react/__placeholder__.js
Happened while validating /Applications/MAMP/htdocs/react-demo/teach-system-react/src/pages/Layout/LayoutHeader/index.js
This can happen for a couple of reasons:
1. The plugin name is spelled incorrectly in an ESLint configuration file (e.g. .eslintrc).
2. If ESLint is installed globally, then make sure 'eslint-plugin-js' is installed globally as well.
3. If ESLint is installed locally, then 'eslint-plugin-js' isn't installed correctly.

Consider running eslint --debug /Applications/MAMP/htdocs/react-demo/teach-system-react/src/pages/Layout/LayoutHeader/index.js from a terminal to obtain a trace about the configuration files used.
```

**Comment by Joshua-Leee** [comment]
There are other cases, like the same React project, running on my colleague's computer, his editor can tell me that the array of dependencies on react hooks are missing or wrong, my editor doesn't work, I think it's the eslint plug-in that's not working, that's causing this.

**Comment by dbaeumer** [comment]
What happens if you validate `/Applications/MAMP/htdocs/react-demo/teach-system-react/src/pages/Layout/LayoutHeader/index.js` in the terminal.
