### ISSUE TITLE
vscode  unstart   ESLint server stopped

### ISSUE THREAD

**Issue by AlexzZzNM** [microsoft/vscode-eslint#1144]
TypeError: Cannot read property 'toLowerCase' of null
	at Object.e.fromString (c:\Users\Administrator\.vscode\extensions\dbaeumer.vscode-eslint-2.1.14\client\out\extension.js:1:44688)
	at R.refreshTrace (c:\Users\Administrator\.vscode\extensions\dbaeumer.vscode-eslint-2.1.14\client\out\extension.js:1:139367)
	at R.initialize (c:\Users\Administrator\.vscode\extensions\dbaeumer.vscode-eslint-2.1.14\client\out\extension.js:1:131626)
	at c:\Users\Administrator\.vscode\extensions\dbaeumer.vscode-eslint-2.1.14\client\out\extension.js:1:131226

**Comment by dbaeumer** [comment]
@AlexzZzNM any steps to reproduce. Do you set a value in your vs code settings to `null`?

**Comment by AlexzZzNM** [comment]
i dont setting vs code ,yesterday is work.but  now stopped.
Below is the console log
[Info  - 上午11:02:34] ESLint server is starting
[Info  - 上午11:02:34] ESLint server stopped.
[Error - 上午11:02:34] Starting client failed
TypeError: Cannot read property 'toLowerCase' of null
	at Object.e.fromString (c:\Users\Administrator\.vscode\extensions\dbaeumer.vscode-eslint-2.1.14\client\out\extension.js:1:44688)
	at R.refreshTrace (c:\Users\Administrator\.vscode\extensions\dbaeumer.vscode-eslint-2.1.14\client\out\extension.js:1:139367)
	at R.initialize (c:\Users\Administrator\.vscode\extensions\dbaeumer.vscode-eslint-2.1.14\client\out\extension.js:1:131626)
	at c:\Users\Administrator\.vscode\extensions\dbaeumer.vscode-eslint-2.1.14\client\out\extension.js:1:131226
[Info  - 上午11:02:35] ESLint server running in node v12.14.1

**Comment by dbaeumer** [comment]
Can you please provide me with your settings (both user and workspace settings). Or even better can you provide me with a GitHub repository I can clone that demos what you are experiencing.

**Comment by dbaeumer** [comment]
Are you sure you are not setting `eslint.trace.server.format` to `null`. This is the only explanation for the exception.

**Comment by dbaeumer** [comment]
This issue has been closed automatically because it needs more information and has not had recent activity. See also our [issue reporting](https://aka.ms/vscodeissuereporting) guidelines.

Happy Coding!
