### ISSUE TITLE
Cannot read property 'type' of undefined when run: onType

### ISSUE THREAD

**Issue by GBrachetta** [microsoft/vscode-eslint#1197]
Eslint extension throws an error permanently when the setting selected is run: onType, for example while typing 

```js
useEffect()
```

And in many other ocassions.

As soon as I enter the first parentheses pair (as in the snippet above) I get the following

![Screenshot 2021-03-07 at 20 20 05](https://user-images.githubusercontent.com/57924268/110251844-d28f1300-7f82-11eb-8cc9-4f1720946bdc.png)

And the output is:

```
[Error - 8:20:42 PM] ESLint stack trace:
[Error - 8:20:42 PM] TypeError: Cannot read property 'type' of undefined
Occurred while linting /Users/Guille/Downloads/getstaticprops-fs-example-main/pages/index.js:6
    at visitCallExpression (/Users/Guille/Downloads/getstaticprops-fs-example-main/node_modules/eslint-plugin-react-hooks/cjs/eslint-plugin-react-hooks.development.js:1734:24)
    at /Users/Guille/Downloads/getstaticprops-fs-example-main/node_modules/eslint/lib/linter/safe-emitter.js:45:58
    at Array.forEach (<anonymous>)
    at Object.emit (/Users/Guille/Downloads/getstaticprops-fs-example-main/node_modules/eslint/lib/linter/safe-emitter.js:45:38)
    at NodeEventGenerator.applySelector (/Users/Guille/Downloads/getstaticprops-fs-example-main/node_modules/eslint/lib/linter/node-event-generator.js:256:26)
    at NodeEventGenerator.applySelectors (/Users/Guille/Downloads/getstaticprops-fs-example-main/node_modules/eslint/lib/linter/node-event-generator.js:285:22)
    at NodeEventGenerator.enterNode (/Users/Guille/Downloads/getstaticprops-fs-example-main/node_modules/eslint/lib/linter/node-event-generator.js:299:14)
    at CodePathAnalyzer.enterNode (/Users/Guille/Downloads/getstaticprops-fs-example-main/node_modules/eslint/lib/linter/code-path-analysis/code-path-analyzer.js:711:23)
    at /Users/Guille/Downloads/getstaticprops-fs-example-main/node_modules/eslint/lib/linter/linter.js:954:32
    at Array.forEach (<anonymous>)
```

This doesn't happen when run: onSave is selected. And strangely it doesn't happen in my installation of VSCode Insiders (just in the stable one).

I tried uninstalling the extension and reinstalling but it didn't help.

What could be the issue?

**Comment by dbaeumer** [comment]
The exception happens in a eslint plugin not in the ESLint extension itself:

```
visitCallExpression (/Users/Guille/Downloads/getstaticprops-fs-example-main/node_modules/eslint-plugin-react-hooks/cjs/eslint-plugin-react-hooks.development.js:1734:24
```

So I guess it has something to do with the version of ESLint or the react plugin

**Comment by GBrachetta** [comment]
Thank you, in fact I believe the error was triggered by this setting:

`"eslint.validate": []`

I am not sure how to use that rule to be honest, but so far removing "javascript" from the array seems to have sorted that permanent error triggering.

**Comment by dbaeumer** [comment]
@GBrachetta but that disables all linting of JS files. Have you tried to update to the latest version of ESLint and the plugins you are using?

**Comment by GBrachetta** [comment]
I'm fully up-to-date. I must say the errors happen when working on jsx files as far as I can tell (that's basically all I'm working on lately). Currently this is my setting:

    "eslint.validate": [
        "javascriptreact"
    ]

It previously contained as well "javascript". Removing it has stopped the error, while I still have linting in jsx files.
I cannot think of what can be wrong otherwise...

**Comment by dbaeumer** [comment]
That sounds very strange. But as comment it happens in the react library. There is nothing I can do anyways to fix this.

**Comment by GBrachetta** [comment]
Thank you! Maybe you would like to try and replicate it and see if the same happens on your end?
I'll experiment a bit more as soon as I have the chance to work on non-jsx files.

**Comment by dbaeumer** [comment]
Will see what I find.

**Comment by dbaeumer** [comment]
Makes sense.
