### ISSUE TITLE
File exists, but `ENOENT: no such file or directory...` reported.

### ISSUE THREAD

**Issue by ruffin--** [microsoft/vscode-eslint#1229]
I'm receiving the following error for some, but not most, files in my project. 

```
(node:26484) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, realpath 'C:\workspaces\WebProduct\Features\MF-QBvN2\Source\Instructor\QuestionBuilder\QuestionBuilder.Web\Scripts\QuestionBuilder\Bank\Models\composite-permissions.service.js'
    at Function.realpathSync.native (fs.js:1684:3)
    at Function.native (electron/js2c/asar_bundle.js:5:4556)
    at c:\Users\usernam\.vscode\extensions\dbaeumer.vscode-eslint-2.1.19\server\out\eslintServer.js:1:14128
    at I (c:\Users\usernam\.vscode\extensions\dbaeumer.vscode-eslint-2.1.19\server\out\eslintServer.js:1:14188)
    at c:\Users\usernam\.vscode\extensions\dbaeumer.vscode-eslint-2.1.19\server\out\eslintServer.js:1:16188
(node:26484) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 290)
```
Actual user name changed to protect the innocent.

-------------------

### Files with this error (not necessarily exhaustive, but all I can find atm):
```
C:\workspaces\WebProduct\Features\MF-QBvN2\Source\Instructor\QuestionBuilder\QuestionBuilder.Web\Scripts\QuestionBuilder\Bank\Models\cache.service.js
C:\workspaces\WebProduct\Features\MF-QBvN2\Source\Instructor\QuestionBuilder\QuestionBuilder.Web\Scripts\QuestionBuilder\Bank\Models\composite-permissions.service.js
```

### Works from the same parent folder:
```
C:\workspaces\WebProduct\Features\MF-QBvN2\Source\Instructor\QuestionBuilder\QuestionBuilder.Web\Scripts\QuestionBuilder\Bank\Models\folder-store.service.js
C:\workspaces\WebProduct\Features\MF-QBvN2\Source\Instructor\QuestionBuilder\QuestionBuilder.Web\Scripts\QuestionBuilder\Bank\Models\folder.js
```

The "no such file or directory" makes me suspect it's not the contents of the files that's the issue, which is why I'm giving paths here.

But additionally note that If I move a file that won't lint to, eg, `c:\temp\composite-permissions.service.js`, it lints as expected. Another piece of evidence that it's not content?

If I execute `eslint C:\workspaces\WebProduct\Features\MF-QBvN2\Source\Instructor\QuestionBuilder\QuestionBuilder.Web\Scripts\QuestionBuilder\Bank\Models\composite-permissions.service.js` from a command prompt in the `C:\Users\usernam` directory, the file lints as expected.

Is there a limit to the characters in a file path specific to the extension? Anything else I can send?

**Comment by dbaeumer** [comment]
@ruffin-- a workaround is to specify your installed node version as the runtime using the `eslint.runtime` setting. But please note that you need to confirm the setting using the Command `ESLint: Select Node Runtime`. 

Let me know if that helps.

**Comment by ruffin--** [comment]
I'll give that a shot today. Out of curiosity, what's causing it to blow up? The paths of things that work seem as long or longer than some that fail. Is it b/c they start with `c`? (I'm joking. I think. :^D)

**Comment by ruffin--** [comment]
VS Code updated to v1.55.0 and now I'm receiving

![image](https://user-images.githubusercontent.com/5659878/113437488-afeeef00-93b4-11eb-9143-6030b9290375.png)

Output says...
```
[Info  - 1:08:59 PM] ESLint server is starting
[Info  - 1:08:59 PM] ESLint server stopped.
[Error - 1:08:59 PM] Starting client failed
Launching server using runtime C:\Program Files\nodejs\eslint failed.
```

I no longer receive the above error after removing `eslint.runtime` from settings.

That is, I'm not 100% how sure a fix this is. I'm in another project now; will try with the one that was giving the original errors when I return.

![image](https://user-images.githubusercontent.com/5659878/113437497-b715fd00-93b4-11eb-8bce-94fe06ec1f8c.png)

**Comment by dbaeumer** [comment]
@ruffin-- you need to set the runtime setting to a node executable (e.g. node.exe). In addition you need to confirm.

The reason why this will address the issue is that it looks like you are using JS constructs which aren't support in the node runtime VS Code ships.

**Comment by Niaro** [comment]
@dbaeumer I'm experiencing the same issue, changing node runtime doesn't help; tried 14, 15, 16.
I see this happening on very long file paths, 250-255

**Comment by dbaeumer** [comment]
@Niaro this could be the old Windows path limitation of 256 characters.

**Comment by Niaro** [comment]
> @Niaro this could be the old Windows path limitation of 256 characters.

That was my assumption too, I changed the registry setting to support long paths and nothing has changed. Although I didn't restart the machine... Could be it

**Comment by dbaeumer** [comment]
I am actually not very familiar with the workaround of the long path name issues in Windows.

**Comment by HomyeeKing** [comment]
![image](https://user-images.githubusercontent.com/49113249/126930737-1efabb97-3518-43ef-8649-6a7c97cdbe8c.png)
 
select node version failed

and why the `eslint` disappear from the vscode status bar

**Comment by doomchild** [comment]
I get this error when I create a new file.  To fix it, I either have to save the file, close it, then re-open it, or restart the LSP workspace.

**Comment by luis-cosillo** [comment]
I have the same problem, someone knows how to solve it, at the moment the solution is to upload that component a subfolder before, and there it reads, but when many subfolders eslint does not support it.

```
(node:24172) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, realpath 'G:\proyectos\deerview\frontendsegurosuni\src\app\universal\area-tecnica\configuracion-producto\components\productos\descuento\editar-descuento\descuento-usuario\editar-descuento-usuario\modal-plan-usuario\editar-modal-plan-usuario\editar-modal-plan-usuario.component.html'
    at Function.realpathSync.native (fs.js:1787:3)
    at Function.native (electron/js2c/asar_bundle.js:5:4607)
    at c:\Users\Luis O. Gonzalez\.vscode\extensions\dbaeumer.vscode-eslint-2.2.2\server\out\eslintServer.js:1:171219
    at X (c:\Users\Luis O. Gonzalez\.vscode\extensions\dbaeumer.vscode-eslint-2.2.2\server\out\eslintServer.js:1:171279)
    at c:\Users\Luis O. Gonzalez\.vscode\extensions\dbaeumer.vscode-eslint-2.2.2\server\out\eslintServer.js:1:174350
(node:24172) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 36)

```

**Comment by thomaswdean** [comment]
I am also  seeing this issue on a Windows machine with the registry setting to allow for long file paths turned on. No visible errors but files with a path over 256 are not showing the linter errors.

**Comment by luis-cosillo** [comment]
@thomaswdean I had to move the files because I did not find suddenly someone has managed to solve it

**Comment by thomaswdean** [comment]
@luis-cosillo Thank you. I am considering doing the same. I just wanted to post here to see if anything is being done to address this issue.

**Comment by luis-cosillo** [comment]
@thomaswdean Yes, I still hope to have it because it may be later on, depending on the project, but hopefully they will fix it.

**Comment by elvinagam** [comment]
I do not think this has been fixed yet... Same issue

**Comment by luis-cosillo** [comment]
Follow the only solution is to rename files

**Comment by elvinagam** [comment]
This is an actual issue which might be hard to fix.
Say I have a filename which should be AppleandPeach.jpg
This "feature" of VSCode makes the filename as appleandpeach.jpng. Say, u have 1 million images like that. How will u programmatically capitalize the capital letter in the second word? No way.

**Comment by ZerdoX-x** [comment]
For me error looks like this:
```
Error: ENOENT: no such file or directory, realpath '/Users/username/path/src/lib/ui/dialog/index.ts'
    at realpathSync.native (node:fs:2554:3)
    at Function.native (node:electron/js2c/asar_bundle:5:4831)
    at t.getFileSystemPath (/Users/username/.vscode/extensions/dbaeumer.vscode-eslint-2.2.6/server/out/eslintServer.js:1:33280)
    at b (/Users/username/.vscode/extensions/dbaeumer.vscode-eslint-2.2.6/server/out/eslintServer.js:1:206750)
    at /Users/username/.vscode/extensions/dbaeumer.vscode-eslint-2.2.6/server/out/eslintServer.js:1:19353
    at async /Users/username/.vscode/extensions/dbaeumer.vscode-eslint-2.2.6/server/out/eslintServer.js:1:210071
```

This file existed in different branch.
Workaround: delete repo where issue appears, create new folder with new path, clone repo.
I've tried to clean cache, vscode history and other things too.. Nothing except this helps.
Maybe vscode-eslint uses some cache under the hood that may be outdated or something..

**Comment by tryonelove** [comment]
Same issue here, occurs when filepath length is greater than Windows MAX_PATH length, even though long paths are enabled both in policies and registry. In my case, filepath length is **302**.

Looking forward for a fix. 

Log:
```
Uncaught exception received.
Error: ENOENT: no such file or directory, realpath 'LONG_COMPONENT_PATH_THAT_IS_PRIVATE'
    at Function.realpathSync.native (node:fs:2554:3)
    at Function.native (node:electron/js2c/asar_bundle:5:4831)
    at t.getFileSystemPath (c:\Users\Ilya\.vscode\extensions\dbaeumer.vscode-eslint-2.4.0\server\out\eslintServer.js:1:34203)
    at b (c:\Users\Ilya\.vscode\extensions\dbaeumer.vscode-eslint-2.4.0\server\out\eslintServer.js:1:217463)
    at c:\Users\Ilya\.vscode\extensions\dbaeumer.vscode-eslint-2.4.0\server\out\eslintServer.js:1:19757
Uncaught exception received.
Error: ENOENT: no such file or directory, realpath 'LONG_COMPONENT_PATH_THAT_IS_PRIVATE'
    at Function.realpathSync.native (node:fs:2554:3)
    at Function.native (node:electron/js2c/asar_bundle:5:4831)
    at t.getFileSystemPath (c:\Users\Ilya\.vscode\extensions\dbaeumer.vscode-eslint-2.4.0\server\out\eslintServer.js:1:34203)
    at b (c:\Users\Ilya\.vscode\extensions\dbaeumer.vscode-eslint-2.4.0\server\out\eslintServer.js:1:217463)
    at c:\Users\Ilya\.vscode\extensions\dbaeumer.vscode-eslint-2.4.0\server\out\eslintServer.js:1:19757
```

**Comment by luis-cosillo** [comment]
They still haven't fixed it, I think we will die without a solution

**Comment by tryonelove** [comment]
I've done some research and probably it's related to a node version VS Code is using.

My VS Code setup:
Version: 1.76.2 (user setup)
Commit: ee2b180d582a7f601fa6ecfdad8d9fd269ab1884
Date: 2023-03-14T17:55:54.936Z
Electron: 19.1.11
Chromium: 102.0.5005.196
Node.js: 16.14.2
V8: 10.2.154.26-electron.0
OS: Windows_NT x64 10.0.22621
Sandboxed: No

There was an issue (https://github.com/nodejs/node/pull/44536) with `fs.realpathSync.native`  that was fixed in Node v16.18.0 & 18.10. As we can above, in the VS Code versions, it uses Node v.16.14.2.

Sadly, we cannot do anything until VS Code starts using newer version of Node.

**Comment by dbaeumer** [comment]
@tryonelove actually you can. You can use `eslint.runtime` setting to point to a different node version used to run the ESLint server.
