### ISSUE TITLE
Cannot set property message of  which has only a getter

### ISSUE THREAD

**Issue by boojum** [microsoft/vscode-eslint#1262]
I'm trying to get type checking in `*.svelte` files working in vscode through a combination of `eslint`, `eslint-plugin-svelte3`, and `eslint-svelte3-preprocess` but `vscode-eslint` is not happy about it:

```
[Info  - 09:31:21] ESLint server is starting
[Info  - 09:31:23] ESLint server running in node v14.16.0
[Info  - 09:31:23] ESLint server is running.
[Info  - 09:31:28] ESLint library loaded from: /home/boojum/Projects/playground/svelte-template/node_modules/eslint/lib/api.js
[Info  - 09:31:31] Cannot set property message of  which has only a getter
[Error - 09:31:56] ESLint stack trace:
[Error - 09:31:56] TypeError: Cannot set property message of  which has only a getter
    at loadJSConfigFile (/home/boojum/Projects/playground/svelte-template/node_modules/@eslint/eslintrc/lib/config-array-factory.js:228:19)
    at loadConfigFile (/home/boojum/Projects/playground/svelte-template/node_modules/@eslint/eslintrc/lib/config-array-factory.js:309:20)
    at ConfigArrayFactory._loadConfigData (/home/boojum/Projects/playground/svelte-template/node_modules/@eslint/eslintrc/lib/config-array-factory.js:609:42)
    at ConfigArrayFactory.loadFile (/home/boojum/Projects/playground/svelte-template/node_modules/@eslint/eslintrc/lib/config-array-factory.js:475:40)
    at createCLIConfigArray (/home/boojum/Projects/playground/svelte-template/node_modules/@eslint/eslintrc/lib/cascading-config-array-factory.js:171:35)
    at new CascadingConfigArrayFactory (/home/boojum/Projects/playground/svelte-template/node_modules/@eslint/eslintrc/lib/cascading-config-array-factory.js:243:29)
    at new CLIEngine (/home/boojum/Projects/playground/svelte-template/node_modules/eslint/lib/cli-engine/cli-engine.js:563:36)
    at _e (/home/boojum/.vscode/extensions/dbaeumer.vscode-eslint-2.1.20/server/out/eslintServer.js:1:29805)
    at /home/boojum/.vscode/extensions/dbaeumer.vscode-eslint-2.1.20/server/out/eslintServer.js:1:23865
    at /home/boojum/.vscode/extensions/dbaeumer.vscode-eslint-2.1.20/server/out/eslintServer.js:1:25181
```

To reproduce:
1. clone [this](https://gitlab.com/b00jum/svelte-template) repo
2. `npm install`
3. open in vscode
4. open file `./src/components/foo.svelte`
5. the above error should pop up in `vscode-eslint` output channel.

VS Code:
Version: 1.56.2
Commit: 054a9295330880ed74ceaedda236253b4f39a335
Date: 2021-05-12T16:45:26.313Z
Electron: 12.0.4
Chrome: 89.0.4389.114
Node.js: 14.16.0
V8: 8.9.255.24-electron.0
OS: Linux x64 5.11.0-17-generic

VS Code Eslint:
dbaeumer.vscode-eslint v2.1.20

I would appreciate any pointer on how I can debug my configuration. Thanks!

**Comment by dbaeumer** [comment]
@boojum try get this working in the terminal only using the `eslint` command. A helpful option to pass is `--debug` which gives you detailed output about what ESLint does. When it works in the terminal try it in VS Code. IF you still see issue you might need to tweak `eslint.workingDirectories` setting.

Let me know how it goes.

**Comment by dbaeumer** [comment]
This issue has been closed automatically because it needs more information and has not had recent activity. See also our [issue reporting](https://aka.ms/vscodeissuereporting) guidelines.

Happy Coding!
