### ISSUE TITLE
Error: command 'eslint.applySingleFix' already exists

### ISSUE THREAD

**Issue by selfagency** [microsoft/vscode-eslint#1300]
Running VS Code via WSL, eslint throws the following error repeatedly:

```
Error: command 'eslint.applySingleFix' already exists
    at S.registerCommand (/home/dsieradski/.vscode-server/bin/2aeda6b18e13c4f4f9edf6667158a6b8d408874b/out/vs/server/remoteExtensionHostProcess.js:84:119253)
    at Object.registerCommand (/home/dsieradski/.vscode-server/bin/2aeda6b18e13c4f4f9edf6667158a6b8d408874b/out/vs/server/remoteExtensionHostProcess.js:93:20920)
    at J.register (/home/dsieradski/.vscode-server/extensions/dbaeumer.vscode-eslint-2.1.23/client/out/extension.js:1:121794)
    at J.initialize (/home/dsieradski/.vscode-server/extensions/dbaeumer.vscode-eslint-2.1.23/client/out/extension.js:1:121366)
    at R.initializeFeatures (/home/dsieradski/.vscode-server/extensions/dbaeumer.vscode-eslint-2.1.23/client/out/extension.js:1:141947)
    at /home/dsieradski/.vscode-server/extensions/dbaeumer.vscode-eslint-2.1.23/client/out/extension.js:1:133444
    at runNextTicks (internal/process/task_queues.js:58:5)
    at processImmediate (internal/timers.js:434:9)
```

**Comment by dbaeumer** [comment]
@selfagency any special steps. I develop in WSL 90% of my time and never say that. I also check the LSP code and registered commands are properly disposed on shutdown. https://github.com/microsoft/vscode-languageserver-node/blob/main/client/src/common/client.ts#L2667

**Comment by Zangetsu101** [comment]
removing "lint": "next lint" from scripts in package.json solved this for me. So I guess they were running eslint twice hence the problem.

**Comment by dbaeumer** [comment]
Thanks for creating this issue! We figured it's missing some basic information or in some other way doesn't follow our issue reporting guidelines. Please take the time to review these and update the issue.

Happy Coding!
