### ISSUE TITLE
Error: Failed to load config "./.config/eslint.config" to extend from.

### ISSUE THREAD

**Issue by alesmenzel** [microsoft/vscode-eslint#1301]
I have started seeing the exact same issue as mentioned in https://github.com/microsoft/vscode-eslint/issues/1182 and according to searching through issues here on GitHub I am not the only one. The issue is kind of annoying one, because vscode keeps showing notifications about this every few minutes. 

Here is the output I see in vscode for eslint (The project was shortend to `<project>` for readability)
```
[Error - 3:57:47 PM] Error: Failed to load config "./.config/eslint.config" to extend from.
Referenced from: <project>/node_modules/@popperjs/core/package.json
    at configInvalidError (<project>/node_modules/@eslint/eslintrc/lib/config-array-factory.js:290:9)
    at ConfigArrayFactory._loadExtendedShareableConfig (<project>/node_modules/@eslint/eslintrc/lib/config-array-factory.js:883:23)
    at ConfigArrayFactory._loadExtends (<project>/node_modules/@eslint/eslintrc/lib/config-array-factory.js:781:25)
    at ConfigArrayFactory._normalizeObjectConfigDataBody (<project>/node_modules/@eslint/eslintrc/lib/config-array-factory.js:720:25)
    at _normalizeObjectConfigDataBody.next (<anonymous>)
    at ConfigArrayFactory._normalizeObjectConfigData (<project>/node_modules/@eslint/eslintrc/lib/config-array-factory.js:665:20)
    at _normalizeObjectConfigData.next (<anonymous>)
    at ConfigArrayFactory.loadInDirectory (<project>/node_modules/@eslint/eslintrc/lib/config-array-factory.js:511:28)
    at CascadingConfigArrayFactory._loadConfigInAncestors (<project>/node_modules/@eslint/eslintrc/lib/cascading-config-array-factory.js:379:46)
    at CascadingConfigArrayFactory._loadConfigInAncestors (<project>/node_modules/@eslint/eslintrc/lib/cascading-config-array-factory.js:398:20)
```

I am running on latest vscode, latest eslint + ts.

_Originally posted by @alesmenzel in https://github.com/microsoft/vscode-eslint/issues/1182#issuecomment-882061401_

**Comment by nbaleli-w** [comment]
@alesmenzel doing a full wipe of vscode, and reinstalling fixed it for me.
I have no idea what actually was the problem but it was with my setup (https://github.com/microsoft/vscode-eslint/issues/1182)

**Comment by alesmenzel** [comment]
For anyone facing the same issue. It seems to be caused by setting the `eslint.validate: []` configuration. I had it like
```
"eslint.validate": [
  "javascript",
  "javascriptreact",
  "typescript",
  "typescriptreact"
],
```
removing this option fixed the issue and TS files are still being validated through vscode-eslint plugin eventhough the default states, it only has `javascript and javascriptreact`.

**Comment by dbaeumer** [comment]
ESLint does some auto probing now. This is why `eslint.validate` is deprecated. I will close the issue. Please ping if there is still an issue.

**Comment by Meligy** [comment]
I'm seeing the same issue with and without setting `eslint.validate`. I think it's not specific to it.

**Comment by hfabio-upsiide** [comment]
> I'm seeing the same issue with and without setting `eslint.validate`. I think it's not specific to it.

same here...
