### ISSUE TITLE
vscode-eslint fails to load eslint-plugin with entry point other than /index.js and not dot-prefixed

### ISSUE THREAD

**Issue by RobertSandiford** [microsoft/vscode-eslint#1354]
I just tried to load this plugin: https://github.com/SebastienGllmt/eslint-plugin-no-floating-promise
with eslint and vscode-eslint.

The package specifies it's entry point with "main": "lib/index.js"

Command line eslint works. vscode-eslint fails

Changing the entry point to "main": "./lib/index.js" fixes the problem. So, it appears that vscode-eslint fails without a ./

Seems to be a fairly common practice, so it would seem that vscode-eslint should accept it.

```
(node:15988) UnhandledPromiseRejectionWarning: Error: Failed to load plugin 'eslint-plugin-promise' declared in '.eslintrc.json': Cannot find module 'eslint-plugin-promise'
Require stack:
- AppLocation\.eslintrc.json
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:934:15)
    at Function.resolve (internal/modules/cjs/helpers.js:94:19)
    at Object.resolve (AppLocation\node_modules\@eslint\eslintrc\lib\shared\relative-module-resolver.js:28:50)
    at Object.ModuleResolver.resolve (AppLocation\node_modules\@rushstack\eslint-patch\lib\modern-module-resolution.js:148:44)
    at ConfigArrayFactory._loadPlugin (AppLocation\node_modules\@eslint\eslintrc\lib\config-array-factory.js:1017:39)
    at ConfigArrayFactory._loadPlugin (AppLocation\node_modules\@rushstack\eslint-patch\lib\modern-module-resolution.js:150:43)
    at AppLocation\node_modules\@eslint\eslintrc\lib\config-array-factory.js:908:33
    at Array.reduce (<anonymous>)
    at ConfigArrayFactory._loadPlugins (AppLocation\node_modules\@eslint\eslintrc\lib\config-array-factory.js:904:22)
    at ConfigArrayFactory._normalizeObjectConfigDataBody (AppLocation\node_modules\@eslint\eslintrc\lib\config-array-factory.js:725:44)
(node:15988) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 591)
```

**Comment by RobertSandiford** [comment]
It started working later on. I don't know what the issue was...

I made a variant with './lib/index.js' and that seems to work but with errors. Then the original started working. Mystery

**Comment by RobertSandiford** [comment]
I suspect this had something to do with the caching, which I wasn't aware of at the time.
