### ISSUE TITLE
node version does not match that in terminal

### ISSUE THREAD

**Issue by gajus** [microsoft/vscode-eslint#1383]
Output tab says:

```
[Info  - 2:18:01 PM] ESLint server is starting
[Info  - 2:18:02 PM] ESLint server running in node v14.16.0
[Info  - 2:18:02 PM] ESLint server is running.
```

Whereas terminal says:

```
14:18:04 ➜ node -v
v16.11.1
```

**Comment by gajus** [comment]
I suspect this is because `vscode-eslint` does not respect `.nvmrc`. Since I don't see anyone mention this, what's the correct way to make it respect `.nvmrc`?

**Comment by gajus** [comment]
Is there a way to run `nvm use`  before vscode-eslint starts the server?

**Comment by gajus** [comment]
It doesn't look like it is picking up zshrc, even though I have it configured to use it:

```json
"terminal.integrated.defaultProfile.osx": "zsh",
  "terminal.integrated.profiles.osx": {
    "zsh": {
      "path": "zsh"
    }
  },
```

**Comment by gajus** [comment]
Ended up hardcoding `"eslint.runtime"` value. Not ideal, though.

**Comment by dbaeumer** [comment]
@gajus by default the extension uses the node runtime shipped with VS Code. This is why you see `v14.16.0`. 

The way how to use a different node runtime is the `eslint.runtime` property. Usually using `node` as a value should pick the default version even if you are using a node version manager.

**Comment by casp4** [comment]
An example snippet to add to vscode settings would be ideal here.

**Comment by p17gh** [comment]
@dbaeumer I see you closed this, so I guess it's supposed to be fixed

for me, though, running
```
Version: 1.64.2
Commit: f80445acd5a3dadef24aa209168452a3d97cc326
Date: 2022-02-09T22:02:29.527Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Linux x64 5.16.9-200.fc35.x86_64
```

with this
```
VS Code ESLint extension v2.2.3
```

inside vscode terminal
```
yarn info --name-only eslint
	└─ eslint@npm:8.9.0	

node -v
	v17.5.0

npx eslint --env-info
	Need to install the following packages:
	  eslint
	Ok to proceed? (y) y
	Environment Info:

	Node version: v17.5.0
	npm version: v8.4.1
	Local ESLint version: Not found
	Global ESLint version: Not found
	Operating System: linux 5.16.9-200.fc35.x86_64
```

if I add to my config
```
"eslint.runtime": "node",
```

in vscode i get a dialog
```
The ESLint server crashed 5 times in the last 3 minutes. The server will not be restarted. The output for more information.
```

and in output,
```
[Info  - 10:26:26 AM] ESLint server is starting
node:fs:1538
  handleErrorFromBinding(ctx);
  ^

Error: EACCES: permission denied, stat '/home/dev/.vscode/extensions/dbaeumer.vscode-eslint-2.2.3/server/out/eslintServer.js'
    at statSync (node:fs:1538:3)
    at fileExists (node:internal/modules/esm/resolve:260:10)
    at resolveExtensionsWithTryExactName (node:internal/modules/esm/resolve:321:7)
    at finalizeResolution (node:internal/modules/esm/resolve:375:16)
    at moduleResolve (node:internal/modules/esm/resolve:946:10)
    at defaultResolve (node:internal/modules/esm/resolve:1043:11)
    at ESMLoader.resolve (node:internal/modules/esm/loader:530:30)
    at ESMLoader.getModuleJob (node:internal/modules/esm/loader:251:18)
    at ESMLoader.import (node:internal/modules/esm/loader:332:22)
    at node:internal/modules/run_main:54:28 {
  errno: -13,
  syscall: 'stat',
  code: 'EACCES',
  path: '/home/dev/.vscode/extensions/dbaeumer.vscode-eslint-2.2.3/server/out/eslintServer.js'
}

Node.js v17.5.0
[Info  - 10:26:26 AM] Connection to server got closed. Server will restart.
[Info  - 10:26:26 AM] ESLint server stopped.
[Info  - 10:26:26 AM] ESLint server is starting
node:fs:1538
  handleErrorFromBinding(ctx);
  ^

Error: EACCES: permission denied, stat '/home/dev/.vscode/extensions/dbaeumer.vscode-eslint-2.2.3/server/out/eslintServer.js'
    at statSync (node:fs:1538:3)
    at fileExists (node:internal/modules/esm/resolve:260:10)
    at resolveExtensionsWithTryExactName (node:internal/modules/esm/resolve:321:7)
    at finalizeResolution (node:internal/modules/esm/resolve:375:16)
    at moduleResolve (node:internal/modules/esm/resolve:946:10)
    at defaultResolve (node:internal/modules/esm/resolve:1043:11)
    at ESMLoader.resolve (node:internal/modules/esm/loader:530:30)
    at ESMLoader.getModuleJob (node:internal/modules/esm/loader:251:18)
    at ESMLoader.import (node:internal/modules/esm/loader:332:22)
    at node:internal/modules/run_main:54:28 {
  errno: -13,
  syscall: 'stat',
  code: 'EACCES',
  path: '/home/dev/.vscode/extensions/dbaeumer.vscode-eslint-2.2.3/server/out/eslintServer.js'
}

Node.js v17.5.0
[Info  - 10:26:26 AM] Connection to server got closed. Server will restart.
[Info  - 10:26:26 AM] ESLint server stopped.
[Info  - 10:26:26 AM] ESLint server is starting
node:fs:1538
  handleErrorFromBinding(ctx);
  ^

Error: EACCES: permission denied, stat '/home/dev/.vscode/extensions/dbaeumer.vscode-eslint-2.2.3/server/out/eslintServer.js'
    at statSync (node:fs:1538:3)
    at fileExists (node:internal/modules/esm/resolve:260:10)
    at resolveExtensionsWithTryExactName (node:internal/modules/esm/resolve:321:7)
    at finalizeResolution (node:internal/modules/esm/resolve:375:16)
    at moduleResolve (node:internal/modules/esm/resolve:946:10)
    at defaultResolve (node:internal/modules/esm/resolve:1043:11)
    at ESMLoader.resolve (node:internal/modules/esm/loader:530:30)
    at ESMLoader.getModuleJob (node:internal/modules/esm/loader:251:18)
    at ESMLoader.import (node:internal/modules/esm/loader:332:22)
    at node:internal/modules/run_main:54:28 {
  errno: -13,
  syscall: 'stat',
  code: 'EACCES',
  path: '/home/dev/.vscode/extensions/dbaeumer.vscode-eslint-2.2.3/server/out/eslintServer.js'
}

Node.js v17.5.0
[Info  - 10:26:26 AM] Connection to server got closed. Server will restart.
[Info  - 10:26:26 AM] ESLint server stopped.
[Info  - 10:26:26 AM] ESLint server is starting
node:fs:1538
  handleErrorFromBinding(ctx);
  ^

Error: EACCES: permission denied, stat '/home/dev/.vscode/extensions/dbaeumer.vscode-eslint-2.2.3/server/out/eslintServer.js'
    at statSync (node:fs:1538:3)
    at fileExists (node:internal/modules/esm/resolve:260:10)
    at resolveExtensionsWithTryExactName (node:internal/modules/esm/resolve:321:7)
    at finalizeResolution (node:internal/modules/esm/resolve:375:16)
    at moduleResolve (node:internal/modules/esm/resolve:946:10)
    at defaultResolve (node:internal/modules/esm/resolve:1043:11)
    at ESMLoader.resolve (node:internal/modules/esm/loader:530:30)
    at ESMLoader.getModuleJob (node:internal/modules/esm/loader:251:18)
    at ESMLoader.import (node:internal/modules/esm/loader:332:22)
    at node:internal/modules/run_main:54:28 {
  errno: -13,
  syscall: 'stat',
  code: 'EACCES',
  path: '/home/dev/.vscode/extensions/dbaeumer.vscode-eslint-2.2.3/server/out/eslintServer.js'
}

Node.js v17.5.0
[Info  - 10:26:26 AM] Connection to server got closed. Server will restart.
[Info  - 10:26:26 AM] ESLint server stopped.
[Info  - 10:26:26 AM] ESLint server is starting
node:fs:1538
  handleErrorFromBinding(ctx);
  ^

Error: EACCES: permission denied, stat '/home/dev/.vscode/extensions/dbaeumer.vscode-eslint-2.2.3/server/out/eslintServer.js'
    at statSync (node:fs:1538:3)
    at fileExists (node:internal/modules/esm/resolve:260:10)
    at resolveExtensionsWithTryExactName (node:internal/modules/esm/resolve:321:7)
    at finalizeResolution (node:internal/modules/esm/resolve:375:16)
    at moduleResolve (node:internal/modules/esm/resolve:946:10)
    at defaultResolve (node:internal/modules/esm/resolve:1043:11)
    at ESMLoader.resolve (node:internal/modules/esm/loader:530:30)
    at ESMLoader.getModuleJob (node:internal/modules/esm/loader:251:18)
    at ESMLoader.import (node:internal/modules/esm/loader:332:22)
    at node:internal/modules/run_main:54:28 {
  errno: -13,
  syscall: 'stat',
  code: 'EACCES',
  path: '/home/dev/.vscode/extensions/dbaeumer.vscode-eslint-2.2.3/server/out/eslintServer.js'
}

Node.js v17.5.0
[Error - 10:26:26 AM] The ESLint server crashed 5 times in the last 3 minutes. The server will not be restarted. The output for more information.
[Info  - 10:26:26 AM] ESLint server stopped.
[Error - 10:26:26 AM] On ready failed
Error: Connection to server got closed. Server will not be restarted.
    at R.handleConnectionClosed (/home/dev/.vscode/extensions/dbaeumer.vscode-eslint-2.2.3/client/out/extension.js:1:144193)
    at R.handleConnectionClosed (/home/dev/.vscode/extensions/dbaeumer.vscode-eslint-2.2.3/client/out/extension.js:1:225911)
    at t (/home/dev/.vscode/extensions/dbaeumer.vscode-eslint-2.2.3/client/out/extension.js:1:142004)
    at r.invoke (/home/dev/.vscode/extensions/dbaeumer.vscode-eslint-2.2.3/client/out/extension.js:1:61661)
    at o.fire (/home/dev/.vscode/extensions/dbaeumer.vscode-eslint-2.2.3/client/out/extension.js:1:62426)
    at Z (/home/dev/.vscode/extensions/dbaeumer.vscode-eslint-2.2.3/client/out/extension.js:1:48389)
    at r.invoke (/home/dev/.vscode/extensions/dbaeumer.vscode-eslint-2.2.3/client/out/extension.js:1:61661)
    at o.fire (/home/dev/.vscode/extensions/dbaeumer.vscode-eslint-2.2.3/client/out/extension.js:1:62426)
    at d.fireClose (/home/dev/.vscode/extensions/dbaeumer.vscode-eslint-2.2.3/client/out/extension.js:1:70238)
    at ChildProcess.<anonymous> (/home/dev/.vscode/extensions/dbaeumer.vscode-eslint-2.2.3/client/out/extension.js:1:81092)
    at ChildProcess.emit (events.js:327:22)
    at maybeClose (internal/child_process.js:1048:16)
    at Socket.<anonymous> (internal/child_process.js:439:11)
    at Socket.emit (events.js:315:20)
    at Pipe.<anonymous> (net.js:673:12)
```

If I remove the
```
"eslint.runtime": "node",
```

I get instead
```
[Info  - 10:29:00 AM] ESLint server is starting
[Info  - 10:29:00 AM] ESLint server running in node v14.16.0
[Info  - 10:29:00 AM] ESLint server is running.
```

in terminal, in vscode,
```
yarn run eslint --debug .
	s/test +0ms
	  eslint:file-enumerator
	  ...
	  eslint:file-enumerator Complete iterating files: ["."] +0ms
	  eslint:cli-engine Linting complete in: 488ms +19ms
```

with no errors

it looks like to me there's some kind of permission error?

but i don't know why it's only in vscode, not at my shell.

**Comment by dbaeumer** [comment]
It looks like node `v17.5.0` has problems accessing the eslint server on your disk. What happens when you run

```
node /home/dev/.vscode/extensions/dbaeumer.vscode-eslint-2.2.3/server/out/eslintServer.js 
```

in the terminal?

**Comment by p17gh** [comment]
@dbaeumer 

from terminal inside vscode,
```
whoami
	dev

node /home/dev/.vscode/extensions/dbaeumer.vscode-eslint-2.2.3/server/out/eslintServer.js
	node:fs:1538
	  handleErrorFromBinding(ctx);
	  ^

	Error: EACCES: permission denied, stat '/home/dev/.vscode/extensions/dbaeumer.vscode-eslint-2.2.3/server/out/eslintServer.js'
	    at statSync (node:fs:1538:3)
	    at fileExists (node:internal/modules/esm/resolve:260:10)
	    at resolveExtensionsWithTryExactName (node:internal/modules/esm/resolve:321:7)
	    at finalizeResolution (node:internal/modules/esm/resolve:375:16)
	    at moduleResolve (node:internal/modules/esm/resolve:946:10)
	    at defaultResolve (node:internal/modules/esm/resolve:1043:11)
	    at ESMLoader.resolve (node:internal/modules/esm/loader:530:30)
	    at ESMLoader.getModuleJob (node:internal/modules/esm/loader:251:18)
	    at ESMLoader.import (node:internal/modules/esm/loader:332:22)
	    at node:internal/modules/run_main:54:28 {
	  errno: -13,
	  syscall: 'stat',
	  code: 'EACCES',
	  path: '/home/dev/.vscode/extensions/dbaeumer.vscode-eslint-2.2.3/server/out/eslintServer.js'
	}

	Node.js v17.5.0
```

checking
```
ls -altR /home/dev/.vscode/extensions/dbaeumer.vscode-eslint-2.2.3
	/home/dev/.vscode/extensions/dbaeumer.vscode-eslint-2.2.3:
	total 136K
	drwxr-xr-x 62 dev dev  12K Feb 23 10:26 ../
	-rw-r--r--  1 dev dev  15K Feb 23 10:04 package.json
	drwxr-xr-x  5 dev dev 4.0K Feb 23 10:04 ./
	-rw-r--r--  1 dev dev 1.9K Feb 23 10:04 ThirdPartyNotices.txt
	drwxr-xr-x  3 dev dev 4.0K Feb 23 10:04 server/
	-rw-r--r--  1 dev dev  22K Feb 23 10:04 README.md
	-rw-r--r--  1 dev dev 2.8K Feb 23 10:04 SECURITY.md
	-rw-r--r--  1 dev dev 1.1K Feb 23 10:04 License.txt
	-rw-r--r--  1 dev dev  193 Feb 23 10:04 package-json-schema.json
	drwxr-xr-x  3 dev dev 4.0K Feb 23 10:04 images/
	-rw-r--r--  1 dev dev  32K Feb 23 10:04 eslint_icon.png
	-rw-r--r--  1 dev dev  16K Feb 23 10:04 CHANGELOG.md
	drwxr-xr-x  3 dev dev 4.0K Feb 23 10:04 client/
	-rw-r--r--  1 dev dev 2.7K Feb 23 10:04 .vsixmanifest

	/home/dev/.vscode/extensions/dbaeumer.vscode-eslint-2.2.3/server:
	total 12K
	drwxr-xr-x 5 dev dev 4.0K Feb 23 10:04 ../
	drwxr-xr-x 3 dev dev 4.0K Feb 23 10:04 ./
	drwxr-xr-x 2 dev dev 4.0K Feb 23 10:04 out/

	/home/dev/.vscode/extensions/dbaeumer.vscode-eslint-2.2.3/server/out:
	total 204K
	drwxr-xr-x 2 dev dev 4.0K Feb 23 10:04 ./
	drwxr-xr-x 3 dev dev 4.0K Feb 23 10:04 ../
	-rw-r--r-- 1 dev dev 196K Feb 23 10:04 eslintServer.js

	/home/dev/.vscode/extensions/dbaeumer.vscode-eslint-2.2.3/images:
	total 12K
	drwxr-xr-x 5 dev dev 4.0K Feb 23 10:04 ../
	drwxr-xr-x 3 dev dev 4.0K Feb 23 10:04 ./
	drwxr-xr-x 2 dev dev 4.0K Feb 23 10:04 2_1_10/

	/home/dev/.vscode/extensions/dbaeumer.vscode-eslint-2.2.3/images/2_1_10:
	total 56K
	drwxr-xr-x 2 dev dev 4.0K Feb 23 10:04 ./
	drwxr-xr-x 3 dev dev 4.0K Feb 23 10:04 ../
	-rw-r--r-- 1 dev dev  42K Feb 23 10:04 eslint-dialog.png
	-rw-r--r-- 1 dev dev 1.1K Feb 23 10:04 eslint-status.png

	/home/dev/.vscode/extensions/dbaeumer.vscode-eslint-2.2.3/client:
	total 12K
	drwxr-xr-x 5 dev dev 4.0K Feb 23 10:04 ../
	drwxr-xr-x 3 dev dev 4.0K Feb 23 10:04 ./
	drwxr-xr-x 2 dev dev 4.0K Feb 23 10:04 out/

	/home/dev/.vscode/extensions/dbaeumer.vscode-eslint-2.2.3/client/out:
	total 328K
	-rw-r--r-- 1 dev dev 317K Feb 23 10:04 extension.js
	drwxr-xr-x 2 dev dev 4.0K Feb 23 10:04 ./
	drwxr-xr-x 3 dev dev 4.0K Feb 23 10:04 ../
```

**Comment by dbaeumer** [comment]
What happens if you set the execute bit on the `esleslintServer.js` file. May be something in node has changed.

**Comment by p17gh** [comment]
no change, unfortunately
```
ls -al /home/dev/.vscode/extensions/dbaeumer.vscode-eslint-2.2.3/server/out/eslintServer.js
	-rwxr-xr-x 1 dev dev 196K Feb 23 10:04 /home/dev/.vscode/extensions/dbaeumer.vscode-eslint-2.2.3/server/out/eslintServer.js*

node /home/dev/.vscode/extensions/dbaeumer.vscode-eslint-2.2.3/server/out/eslintServer.js
node:fs:1538
  handleErrorFromBinding(ctx);
  ^

Error: EACCES: permission denied, stat '/home/dev/.vscode/extensions/dbaeumer.vscode-eslint-2.2.3/server/out/eslintServer.js'
    at statSync (node:fs:1538:3)
    at fileExists (node:internal/modules/esm/resolve:260:10)
    at resolveExtensionsWithTryExactName (node:internal/modules/esm/resolve:321:7)
    at finalizeResolution (node:internal/modules/esm/resolve:375:16)
    at moduleResolve (node:internal/modules/esm/resolve:946:10)
    at defaultResolve (node:internal/modules/esm/resolve:1043:11)
    at ESMLoader.resolve (node:internal/modules/esm/loader:530:30)
    at ESMLoader.getModuleJob (node:internal/modules/esm/loader:251:18)
    at ESMLoader.import (node:internal/modules/esm/loader:332:22)
    at node:internal/modules/run_main:54:28 {
  errno: -13,
  syscall: 'stat',
  code: 'EACCES',
  path: '/home/dev/.vscode/extensions/dbaeumer.vscode-eslint-2.2.3/server/out/eslintServer.js'
}

Node.js v17.5.0
```

**Comment by dbaeumer** [comment]
Actually I tested this and node 17.5.0 has no problems executing a JS file without the execute bit set. So it seems to be something else on your machine that prevents node 17.5.0 to access the file.

**Comment by casp4** [comment]
@dbaeumer what machine did you test it on ? and was it fresh?

**Comment by dbaeumer** [comment]
Ubuntu 20.04.4 LTS. Node was freshly installed, Ubuntu is older.

**Comment by casp4** [comment]
Thanks for the version, but could something else on that machine be helping node access the file?

**Comment by dbaeumer** [comment]
I search the WEB for it and I couldn't find any indication that Node changed this behavior in the 17.x release.
