### ISSUE TITLE
 'reportUnusedDisableDirectives' must be any of "error", "warn", "off", and null

### ISSUE THREAD

**Issue by wmertens** [microsoft/vscode-eslint#1415]
When I update my eslint installation, VSCode linting stops working with the below error. It works fine from the command line, so something in vscode is inserting it.

I don't set `reportUnusedDisableDirectives` myself, and this happens even when I disable everything in my .eslintrc.

I added logging in the eslint module and I see that `reportUnusedDisableDirectives` is set to `true`.

```
(node:1345199) UnhandledPromiseRejectionWarning: Error: Invalid Options:
- 'reportUnusedDisableDirectives' must be any of "error", "warn", "off", and null.
    at processOptions (/home/wmertens/Projects/Cap/node_modules/.pnpm/eslint@8.6.0/node_modules/eslint/lib/eslint/eslint.js:293:15)
    at new ESLint (/home/wmertens/Projects/Cap/node_modules/.pnpm/eslint@8.6.0/node_modules/eslint/lib/eslint/eslint.js:440:34)
    at Object.e.newESLintClass (/home/wmertens/.vscode/extensions/dbaeumer.vscode-eslint-2.2.2/server/out/eslintServer.js:1:167243)
    at Ce (/home/wmertens/.vscode/extensions/dbaeumer.vscode-eslint-2.2.2/server/out/eslintServer.js:1:186299)
    at h.then.o.validate (/home/wmertens/.vscode/extensions/dbaeumer.vscode-eslint-2.2.2/server/out/eslintServer.js:1:176323)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(node:1345199) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 11230)
[Info  - 7:28:35 AM] Invalid Options: - 'reportUnusedDisableDirectives' must be any of "error", "warn", "off", and null.
```

**Comment by wmertens** [comment]
I was able to work around this by setting `reportUnusedDisableDirectives: true` in my eslintrc. I tried setting it to `"error"` first but that gave an error, in the eslintrc it has to be a boolean.

**Comment by dbaeumer** [comment]
@wmertens can you please provide me with a Github repository I can clone that demos that. Otherwise it is very hard to tell why this fails.

**Comment by wmertens** [comment]
@dbaeumer thanks for checking! I have it with current master of https://github.com/StratoKit/strato-db.
Actually the workaround doesn't work, I forgot I patched eslint to ignore it.

The options that it uses are just the below, not from my eslintrc.
```
[Info  - 1:36:20 PM] Invalid Options: - 'reportUnusedDisableDirectives' true must be any of "error", "warn", "off", and null.
[Object: null prototype] {
  reportUnusedDisableDirectives: true,
  cwd: '/home/wmertens/Projects/strato-db'
}
```

 I think they're the command line options somehow, when I run `npx eslint .` in the terminal the options it uses are
```
{
  allowInlineConfig: true,
  cache: false,
  cacheLocation: '.eslintcache',
  cacheStrategy: 'metadata',
  errorOnUnmatchedPattern: true,
  extensions: undefined,
  fix: undefined,
  fixTypes: undefined,
  ignore: true,
  ignorePath: undefined,
  overrideConfig: {
    env: undefined,
    globals: undefined,
    ignorePatterns: undefined,
    parser: undefined,
    parserOptions: undefined,
    plugins: undefined,
    rules: undefined
  },
  overrideConfigFile: undefined,
  reportUnusedDisableDirectives: undefined,
  resolvePluginsRelativeTo: undefined,
  rulePaths: undefined,
  useEslintrc: true
}
```

**Comment by dbaeumer** [comment]
If you have special options on the command line you can use the `eslint.options` VS Code setting to let ESLint know about this. Can you give that a try?

**Comment by wmertens** [comment]
Aha! That's why - somehow that configuration was in my eslint.options. Maybe I added it in there a few years ago? I removed it and everything's working again. Thanks!
