### ISSUE TITLE
Error: Cannot find module 'xxx/node_modules/espree/dist/espree.cjs'

### ISSUE THREAD

**Issue by Toby-Liuzhifu** [microsoft/vscode-eslint#1436]
When using the vscode plugin, open any file, and a prompt "ESLint: Cannot find module  /node/eleme/ele-client/node_modules/espree/dist/espree.cjs'. Please see the 'ESLint' output channel for details" will pop up.

output channel:
[Error - 1:52:42 PM] ESLint stack trace:
[Error - 1:52:42 PM] Error: Cannot find module '/node/eleme/ele-client/node_modules/espree/dist/espree.cjs'
    at createEsmNotFoundErr (internal/modules/cjs/loader.js:961:15)
    at finalizeEsmResolution (internal/modules/cjs/loader.js:954:15)
    at resolveExports (internal/modules/cjs/loader.js:439:14)
    at Function.Module._findPath (internal/modules/cjs/loader.js:479:31)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:921:27)
    at Module._load (internal/modules/cjs/loader.js:779:27)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12913)
    at Module.require (internal/modules/cjs/loader.js:1006:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/Users/liuzhifu/Documents/node/eleme/ele-client/node_modules/eslint/lib/rules/utils/ast-utils.js:13:16)

vscode-eslint version - 2.2.2
eslint version: 7.32.0

**Comment by Toby-Liuzhifu** [comment]
After restarting vscode the problem disappeared
