### ISSUE TITLE
eslint --init failed with syntax error

### ISSUE THREAD

**Issue by petervesely** [microsoft/vscode-eslint#1443]
Hello,

I have just installed the module and tried to init the config. I got the following error:

`$ ./node_modules/.bin/eslint --init
You can also run this command directly using 'npm init @eslint/config'.
npx: installed 40 in 3.126s
/home/user/.npm/_npx/32206/lib/node_modules/@eslint/create-config/bin/create-config.js:9
import { initializeConfig } from "../lib/init/config-initializer.js";
       ^

SyntaxError: Unexpected token {
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)

$ npm --version
6.14.4
$ node --version
v10.19.0
`

**Comment by dbaeumer** [comment]
@petervesely please report this to ESLint itself. This repository is about the ESLint extension for VS Code which uses ESLint under the hood.
