### ISSUE TITLE
Server crashes with message Error: Connection to server got closed. Server will not be restarted.

### ISSUE THREAD

**Issue by janjaap** [microsoft/vscode-eslint#1453]
Eslint keeps crashing after the last update of Visual Studio Code.

VS Code:
```
Version: 1.66.2
Commit: dfd34e8260c270da74b5c2d86d61aee4b6d56977
Date: 2022-04-11T07:49:24.808Z
Electron: 17.2.0
Chromium: 98.0.4758.109
Node.js: 16.13.0
V8: 9.8.177.11-electron.0
OS: Linux x64 5.13.0-40-generic snap
```

Extension: v2.2.2
Eslint: v8.7.0

Stack trace:
```
[Info  - 1:06:36 PM] ESLint server is starting
Invalid option '--node-ipc' - perhaps you meant '--config'?
[Info  - 1:06:36 PM] Connection to server got closed. Server will restart.
[Info  - 1:06:36 PM] ESLint server stopped.
[Info  - 1:06:36 PM] ESLint server is starting
Invalid option '--node-ipc' - perhaps you meant '--config'?
[Info  - 1:06:36 PM] Connection to server got closed. Server will restart.
[Info  - 1:06:36 PM] ESLint server stopped.
[Info  - 1:06:36 PM] ESLint server is starting
Invalid option '--node-ipc' - perhaps you meant '--config'?
[Info  - 1:06:36 PM] Connection to server got closed. Server will restart.
[Info  - 1:06:36 PM] ESLint server stopped.
[Info  - 1:06:36 PM] ESLint server is starting
Invalid option '--node-ipc' - perhaps you meant '--config'?
[Info  - 1:06:37 PM] Connection to server got closed. Server will restart.
[Info  - 1:06:37 PM] ESLint server stopped.
[Info  - 1:06:37 PM] ESLint server is starting
Invalid option '--node-ipc' - perhaps you meant '--config'?
[Error - 1:06:37 PM] Connection to server got closed. Server will not be restarted.
[Info  - 1:06:37 PM] ESLint server stopped.
[Error - 1:06:37 PM] On ready failed
Error: Connection to server got closed. Server will not be restarted.
	at R.handleConnectionClosed (~/.vscode/extensions/dbaeumer.vscode-eslint-2.2.2/client/out/extension.js:1:142771)
	at R.handleConnectionClosed (~/.vscode/extensions/dbaeumer.vscode-eslint-2.2.2/client/out/extension.js:1:219725)
	at t (~/.vscode/extensions/dbaeumer.vscode-eslint-2.2.2/client/out/extension.js:1:140624)
	at r.invoke (~/.vscode/extensions/dbaeumer.vscode-eslint-2.2.2/client/out/extension.js:1:61065)
	at o.fire (~/.vscode/extensions/dbaeumer.vscode-eslint-2.2.2/client/out/extension.js:1:61830)
	at Q (~/.vscode/extensions/dbaeumer.vscode-eslint-2.2.2/client/out/extension.js:1:47961)
	at r.invoke (~/.vscode/extensions/dbaeumer.vscode-eslint-2.2.2/client/out/extension.js:1:61065)
	at o.fire (~/.vscode/extensions/dbaeumer.vscode-eslint-2.2.2/client/out/extension.js:1:61830)
	at d.fireClose (~/.vscode/extensions/dbaeumer.vscode-eslint-2.2.2/client/out/extension.js:1:69716)
	at ChildProcess.<anonymous> (~/.vscode/extensions/dbaeumer.vscode-eslint-2.2.2/client/out/extension.js:1:80714)
	at ChildProcess.emit (node:events:402:35)
	at maybeClose (node:internal/child_process:1064:16)
	at Process.ChildProcess._handle.onexit (node:internal/child_process:301:5)
```

**Comment by dbaeumer** [comment]
> Invalid option '--node-ipc' - perhaps you meant '--config'? 

This is not coming from the eslint server and points to some custom configuration.

Can you please provide me with a GitHub repository I can clone that demos what you are seeing. Then I can investigate?

**Comment by janjaap** [comment]
I think I found the issue. I had created a workspace with two project folders and since the extension was looking for the Eslint executable in that folder, it couldn't run. I've set the `eslint.nodePath` setting for both folders separately and now it works.
