### ISSUE TITLE
Does not work with ESLint v8 (ESLint: Invalid Options: - Unknown options: object-shorthand)

### ISSUE THREAD

**Issue by mckravchyk** [microsoft/vscode-eslint#1463]
I have started a new project and VS Code ESLint would not work. This message popped up. ESLint from console was working fine. The problem persisted even after removing all ESLint configuration. The issue was resolved after downgrading to ESLint 7.x

`[Error - 5:44:09 PM] Error: Invalid Options:
- Unknown options: object-shorthand
    at processOptions (/home/.../project/node_modules/eslint/lib/eslint/eslint.js:281:15)
    at new ESLint (/home/.../project/node_modules/eslint/lib/eslint/eslint.js:428:34)
    at Object.e.newESLintClass (/home/.../.vscode-oss/extensions/dbaeumer.vscode-eslint-2.2.3/server/out/eslintServer.js:1:170158)
    at Ce (/home/.../.vscode-oss/extensions/dbaeumer.vscode-eslint-2.2.3/server/out/eslintServer.js:1:189261)
    at /home/.../.vscode-oss/extensions/dbaeumer.vscode-eslint-2.2.3/server/out/eslintServer.js:1:183220
    at /home/.../.vscode-oss/extensions/dbaeumer.vscode-eslint-2.2.3/server/out/eslintServer.js:1:184587
`

**Comment by dbaeumer** [comment]
Which version of VS Code are you using? VS Code ships with a node version and I guess that one is too old. You can either use `eslint.runtime` to point to a newer node version or ensure that you are using the latest version of VS Code.

**Comment by mckravchyk** [comment]
I'm using 1.67.1, which is currently the latest version.

Version: 1.67.1
Commit: da15b6fd3ef856477bf6f4fb29ba1b7af717770d
Date: 2022-05-10T21:35:59.370Z
Electron: 17.4.3
Chromium: 98.0.4758.141
Node.js: 16.13.0
V8: 9.8.177.13-electron.0
OS: Linux x64 5.17.4

**Comment by dbaeumer** [comment]
@mckravchyk can you try validating the file in the console using a node version 16.13. 

If this works fine can you please provide me with a GitHub repository I can clone that demos what you are seeing.

If it doesn't work use the `eslint.runtime` option to ask the ESLint server to use a different node executable.

**Comment by mckravchyk** [comment]
Hey @dbaeumer, sorry for the late reply.  I have been ignoring the issue but now I'm keen on finally resolving it as it's probably a matter of time when using an older version of Eslint blocks me from upgrading other packages.

- I have verified that CLI linting works with Node 16.14
- I have reproduced the problem in [this most basic fiddle](https://gist.github.com/mckravchyk/d8ed77bce1041af1b50ed8af1fbc880f)

Please let me know if there's anything I can do to gather more debugging info.

My current Code version:
```
Version: 1.73.0
Commit: 8fa188b2b301d36553cbc9ce1b0a146ccb93351f
Date: 2022-11-03T14:04:08.642Z
Electron: 19.1.4
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Linux x64 6.0.7
Sandboxed: No

```

**Comment by dbaeumer** [comment]
I am not able to reproduce this:

<img width="1036" alt="image" src="https://user-images.githubusercontent.com/1931590/202672132-df6a1bf2-0148-45ff-9e37-184f14b76e13.png">

Could it be that there is a eslintrc config file in a parent directory that is considered. You can stop looking up the chain using   `root: true`

**Comment by mckravchyk** [comment]
There's no parent directory. I have added root: true though and it had no effect.

It looks like the error is due to an invalid "object-shorthand" option being passed to the ESLint constructor. 

I have added the following to the local ESLint module:

```js
/**
 * Main API.
 */
class ESLint {

    /**
     * Creates a new instance of the main ESLint API.
     * @param {ESLintOptions} options The options for this instance.
     */
    ...
    constructor(options = {}) {
        console.log('Initializing ESLint');
        console.log(options);

        // Injecting this fixes the  issue
        if (typeof options['object-shorthand'] !== 'undefined') {
            delete options['object-shorthand'];
        }
       ...
```

CLI gives me:
```
Initializing ESLint
{
  allowInlineConfig: true,
  cache: false,
  cacheLocation: '.eslintcache',
  cacheStrategy: 'metadata',
  errorOnUnmatchedPattern: true,
  fix: undefined,
  fixTypes: undefined,
  ignore: true,
  overrideConfig: {
    env: undefined,
    globals: undefined,
    ignorePatterns: undefined,
    parser: undefined,
    parserOptions: undefined,
    plugins: undefined,
    rules: undefined
  },
  overrideConfigFile: undefined,
  reportUnusedDisableDirectives: undefined,
  resolvePluginsRelativeTo: undefined,
  rulePaths: undefined,
  useEslintrc: true,
  extensions: undefined,
  ignorePath: undefined
}
```

Extension output gives  me:
```
Initializing ESLint
[Object: null prototype] {
  'object-shorthand': [ 'error', 'always' ],
  cwd: '/home/.../eslint-bug'
}
```

Injecting code to the ESLinnt constructor to remove the option before it's being processed fixes this issue.

**Comment by dbaeumer** [comment]
I am a little bit puzzled as well. If I add an `object-shorthand` to the eslintrc file everything works for me:

<img width="785" alt="image" src="https://user-images.githubusercontent.com/1931590/202696561-aed9dd2f-0f85-45c5-bbb8-01b7fcbf7f01.png">

It is hard to say without steps on how to reproduce this.

BTW: the options passed to the ESLint class constructor are not rule definition. These options are documented here: https://eslint.org/docs/latest/developer-guide/nodejs-api#-new-eslintoptions

**Comment by mckravchyk** [comment]
It took me going up the call stack to find that  I had the below in my global settings.json :)

```
      "eslint.options": {
          "object-shorthand": ["error", "always"]
      },
```

I know these constructor options are different but for whatever bizzare  reason I defined it in the options a few years ago and forgot about it. It seems like ESLint introduced option validation in v8, so it went on unnoticed in the previous versions.

**Comment by dbaeumer** [comment]
Good to heat that you were able to solve this.
