### ISSUE TITLE
Extension fails with pnpm command not found

### ISSUE THREAD

**Issue by doubleplusc** [microsoft/vscode-eslint#1464]
I previously commented on #1462 but OP's problem was fixed so the issue closed. My problem persists even after a restart, so I am creating a new issue.

I have pnpm installed on Linux via `npm install -g pnpm`. pnpm works fine in the vscode integrated terminal and standalone terminals.

The extension fails with the following error on load:
```
Uncaught exception received.
Error: Command failed: pnpm root -g
/bin/sh: line 1: pnpm: command not found

    at checkExecSyncError (node:child_process:835:11)
    at execSync (node:child_process:909:15)
    at node:electron/js2c/asar_bundle:5:12692
    at Object.get (/home/doubleplusc/.vscode-oss/extensions/dbaeumer.vscode-eslint-2.2.2/server/out/eslintServer.js:1:172258)
    at /home/doubleplusc/.vscode-oss/extensions/dbaeumer.vscode-eslint-2.2.2/server/out/eslintServer.js:1:174308
    at /home/doubleplusc/.vscode-oss/extensions/dbaeumer.vscode-eslint-2.2.2/server/out/eslintServer.js:1:174323
```
`pnpm root -g` returns
/home/doubleplusc/.local/share/pnpm/global/5/node_modules

Thanks!

**Comment by dbaeumer** [comment]
How do you start VS Code? Can you try starting it from a terminal in which `pnpm` works and see if you get the same error?

**Comment by doubleplusc** [comment]
I always start it via my DE's application menu.
I did what you suggested, I opened a terminal (with working `pnpm`) and opened VSCode. The extension now works as intended.
I can start VSCode from the terminal for the time being, but it's really strange that starting via terminal vs non-terminal would have different behavior. Any chance this can be fixed?

**Comment by Asesjix** [comment]
I have the same problem. In general, there are always various problems with regard to the shell.
In my opinion, the cause of the problem is that the plugin always starts its own instance of "/bin/sh" instead of creating an instance of the default automation profile shell. 
Furthermore, the VSCode internal node is probably used and not the one from the environment. I think so because the node version in the plugin is always different from my environment.

Why do I think so? Many who use Node use NVM or something similar.
This is typically only configured for the shell in which you are working. In my case zsh.

I have made many attempts to solve problems of this type, unfortunately I usually fail.
Since I'm using Debian in WSL, /bin/sh points to dash.
The way the plugin uses /bin/sh, the shell isn't customizable either. Because changes in /etc/profile or ~/.profile have no effect on it.

Proof of this:

```
# Plugin
Error: Command failed: pnpm root -g
/bin/sh: line 1: pnpm: command not found
```

```sh
#/bin/zsh
pnpm root -g
/home/seri/.local/share/pnpm/global/5/node_modules
```
```sh
#/bin/zsh
/bin/sh -c "pnpm root -g"
/home/seri/.local/share/pnpm/global/5/node_modules
```

```sh
#/bin/zsh
/bin/sh
pnpm root -g
/home/seri/.local/share/pnpm/global/5/node_modules
```
