### ISSUE TITLE
Cannot load graphql schemas from URL - Error: Error while loading schema: Command failed

### ISSUE THREAD

**Issue by chendoron** [microsoft/vscode-eslint#1481]
I've recently added `@graphql-eslint/eslint-plugin` to our projects.
It works perfectly fine on my server app.

However on my react app side of things, I use the URL to the graphql schema in the `parserOptions` as described by the vendor of the plugin here: https://github.com/B2o5T/graphql-eslint

```
"overrides": [
    {
      "files": ["**/*.ts", "**/*.tsx"],
      "rules": {
        "react/prop-types": "error"
      }
    },
    {
      "files": ["*.graphql"],
      "parserOptions": {
        "schema": "https://staging.*********.***/gql",
        "operations": "src/graphql/operations/**/*.graphql"
      }
    }
  ]
  ```

The error I'm getting is this:

```
[Info  - 8:00:38 AM] ESLint server is starting
[Info  - 8:00:38 AM] ESLint server running in node v16.13.0
[Info  - 8:00:38 AM] ESLint server is running.
[Info  - 8:00:39 AM] ESLint library loaded from: ....../node_modules/eslint/lib/api.js
[Error - 8:00:40 AM] ESLint stack trace:
[Error - 8:00:40 AM] Error: Error while loading schema: Command failed: /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper.app/Contents/MacOS/Code Helper ....../node_modules/sync-fetch/worker.js
Occurred while linting ....../src/graphql/fragments/highlights.graphql:1
    at checkExecSyncError (node:child_process:846:11)
    at execFileSync (node:child_process:884:15)
    at func (node:electron/js2c/asar_bundle:5:1812)
    at sendMessage (....../node_modules/sync-fetch/index.js:41:10)
    at fetch (....../node_modules/sync-fetch/index.js:32:31)
    at defaultSyncFetch (....../node_modules/@graphql-tools/url-loader/index.js:51:12)
    at ....../node_modules/@graphql-tools/url-loader/index.js:492:36
    at new ValueOrPromise (....../node_modules/value-or-promise/build/main/ValueOrPromise.js:14:21)
    at executor (....../node_modules/@graphql-tools/url-loader/index.js:460:20)
    at ....../node_modules/@graphql-tools/url-loader/index.js:759:35
```

I've tried debugging it locally to understand better for no results though.
I've asked for help on the eslint support chat and they directed me here saying that the vscode extension is quite a mess.
Please help me fix it, this would tremendously benefit my development team.

**Comment by dbaeumer** [comment]
> saying that the vscode extension is quite a mess.

Would be interesting to me who said that :-)

Does validation happen for you correctly when doing it in the terminal for the specific file. If yes, do you need to do a change directory to make it work. If so, you need to let the eslint extension know about this using the `eslint.workingDirectories` setting. If validation happens correctly and  you don't need to `cd` then please provide me with a GitHub repository I can clone that demos that. Then I can have a look.

**Comment by dbaeumer** [comment]
Just to make sure. When you lint in the terminal you do this from the workspace folder root. Not from a directory you `cd` into?

And you said that for the server app linting works correctly. Does that mean it works there with the ESLint extension?

Without steps to reproduce it is very hard to tell why this fails.

**Comment by chendoron** [comment]
@dbaeumer 

1. Yes I am linting in my terminal from the root folder of the project I'm attempting to lint (different folders for the server app and the react app). In both cases - linting in the terminal works just fine.

I've tried to make it clear as to why the failure happens but I'll try to reiterate:

My graphql schema lives on my server app, so the linter works fine because the files are local.
For my react app - I give my `.eslintrc` file a link to the graphql schema, and eslint is trying to request that schema from the server when linting. as described in this eslint config override:
```
    {
      "files": ["*.graphql"],
      "parserOptions": {
        "schema": "https://staging.*********.***/gql",
        "operations": "src/graphql/operations/**/*.graphql"
      }
    }
```

I've also attached the stack trace of the error in vscode.

In addition I can try to describe other steps to reproduce:
- Attempt to use the graphql eslint module and give its options a public graphql schema introspection url.

**Comment by dbaeumer** [comment]
The only thing I can think of is a problem with the node version used. What you can try is using the setting `eslint.runtime` to set it to the node version you use when running ESLint in the terminal. If this doesn't help could you please provide me with a Github repository I can clone that demos this.

**Comment by IvanGrekov** [comment]
@chendoron Hi, I'm curious if you resolved this issue? At the moment, I'm also trying to use `@graphql-eslint/eslint-plugin` but it works strange

**Comment by chendoron** [comment]
> 

We never got it working on vscode.

**Comment by chendoron** [comment]
> @chendoron Hi, I'm curious if you resolved this issue? At the moment, I'm also trying to use `@graphql-eslint/eslint-plugin` but it works strange

We never got it working on vscode.

**Comment by Rigo-m** [comment]
Same problem here

**Comment by camilo-mujica** [comment]
Same problem here

**Comment by dbaeumer** [comment]
Can someone who sees this provide me with a sample Github repository I can clone that shows the behaviour?

**Comment by dbaeumer** [comment]
You can invite me to the repository.

**Comment by dbaeumer** [comment]
I cloned the repository. Could you provide me with steps on how to reproduce what you are seeing?

**Comment by justlevine** [comment]
@dbaeumer 
Checkout [this commit](https://github.com/AxeWP/axewp-frontend/commit/564919051323d0c62630d4422a3be5f7fa0f7105), run `npm install` and `npm run codegen`, reload vscode, and you should see the error listed in the `Problems` tab on any file that is using GraphQL.

(The following commit disabled graphql-eslint entirely for the time being)

**Comment by dbaeumer** [comment]
@justlevine `npm run codegen` failed for me in the following way:

<img width="481" alt="image" src="https://github.com/microsoft/vscode-eslint/assets/1931590/fa528e40-c432-4e2d-922b-dc128ab10684">

**Comment by dbaeumer** [comment]
Any advise?

**Comment by justlevine** [comment]
@dbaeumer copying over `.env.example` to `.env` and uncommenting `NODE_TLS_REJECT_UNAUTHORIZED=0` is all it takes me to run codegen locally (I forgot to mention that in my repro steps, new to frontend dev 🤦‍♂️).

![image](https://github.com/microsoft/vscode-eslint/assets/29322304/2214a649-9370-4ad1-a7e8-36abb7709e18)

If that's still not working, can you see see the live GraphQL endpoint in your browser if you visit `{NEXT_PUBLIC_WORDPRESS_URL}/index.php?graphql`?

![image](https://github.com/microsoft/vscode-eslint/assets/29322304/b0cd5612-cc2b-4033-ada7-e798b49cef98)

If it's helpful, I'm happy to share additional credentials privately or hop on a video call, just open an issue in the private repo, so I don't leak those deets publicly.

**Comment by dbaeumer** [comment]
Which file do I have to open to see ESLint fail?

**Comment by dbaeumer** [comment]
This issue has been closed because it needs more information and has not had recent activity. See also our [issue reporting](https://aka.ms/vscodeissuereporting) guidelines.

Happy Coding!
