### ISSUE TITLE
Server process exited with code 1. This usually indicates a misconfigured ESLint setup.

### ISSUE THREAD

**Issue by yoyo837** [microsoft/vscode-eslint#1535]
```
[Info  - 9:23:01 AM] ESLint server is starting
[Info  - 9:23:02 AM] ESLint server running in node v16.14.2
[Info  - 9:23:02 AM] ESLint server is running.
[Info  - 9:23:03 AM] ESLint library loaded from: /Users/tanghui/git/ydmap/web/ydmap-web-portal/node_modules/eslint/lib/api.js
error: unknown option '--node-ipc'
[Error - 11:43:59 AM] Server process exited with code 1. This usually indicates a misconfigured ESLint setup.
Error: stack
    at process.exit (/Users/tanghui/.vscode/extensions/dbaeumer.vscode-eslint-2.2.6/server/out/eslintServer.js:1:207186)
    at Command._exit (/Users/tanghui/git/ydmap/web/ydmap-web-portal/node_modules/commander/lib/command.js:452:13)
    at Command.error (/Users/tanghui/git/ydmap/web/ydmap-web-portal/node_modules/commander/lib/command.js:1572:10)
    at Command.unknownOption (/Users/tanghui/git/ydmap/web/ydmap-web-portal/node_modules/commander/lib/command.js:1722:10)
    at checkForUnknownOptions (/Users/tanghui/git/ydmap/web/ydmap-web-portal/node_modules/commander/lib/command.js:1253:14)
    at Command._parseCommand (/Users/tanghui/git/ydmap/web/ydmap-web-portal/node_modules/commander/lib/command.js:1295:7)
    at Command.parse (/Users/tanghui/git/ydmap/web/ydmap-web-portal/node_modules/commander/lib/command.js:890:10)
    at Object.<anonymous> (/Users/tanghui/git/ydmap/web/ydmap-web-portal/vue.config.js:26:9)
    at Module._compile (node:internal/modules/cjs/loader:1165:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1220:10)
    at Module.load (node:internal/modules/cjs/loader:1035:32)
    at Module._load (node:internal/modules/cjs/loader:876:12)
    at Function.c._load (node:electron/js2c/asar_bundle:5:13343)
    at Module.require (node:internal/modules/cjs/loader:1059:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at exports.loadModule (/Users/tanghui/git/ydmap/web/ydmap-web-portal/node_modules/@vue/cli-shared-utils/lib/module.js:79:64)
    at loadFileConfig (/Users/tanghui/git/ydmap/web/ydmap-web-portal/node_modules/@vue/cli-service/lib/util/loadFileConfig.js:30:20)
    at Service.loadUserOptions (/Users/tanghui/git/ydmap/web/ydmap-web-portal/node_modules/@vue/cli-service/lib/Service.js:339:44)
    at Service.init (/Users/tanghui/git/ydmap/web/ydmap-web-portal/node_modules/@vue/cli-service/lib/Service.js:73:30)
    at Object.<anonymous> (/Users/tanghui/git/ydmap/web/ydmap-web-portal/node_modules/@vue/cli-service/webpack.config.js:9:11)
    at Module._compile (node:internal/modules/cjs/loader:1165:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1220:10)
    at Module.load (node:internal/modules/cjs/loader:1035:32)
    at Module._load (node:internal/modules/cjs/loader:876:12)
    at Function.c._load (node:electron/js2c/asar_bundle:5:13343)
    at Module.require (node:internal/modules/cjs/loader:1059:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.exports.resolve (/Users/tanghui/git/ydmap/web/ydmap-web-portal/node_modules/eslint-import-resolver-webpack/index.js:86:25)
    at v2 (/Users/tanghui/git/ydmap/web/ydmap-web-portal/node_modules/eslint-module-utils/resolve.js:116:23)
    at withResolver (/Users/tanghui/git/ydmap/web/ydmap-web-portal/node_modules/eslint-module-utils/resolve.js:121:14)
    at fullResolve (/Users/tanghui/git/ydmap/web/ydmap-web-portal/node_modules/eslint-module-utils/resolve.js:138:22)
    at relative (/Users/tanghui/git/ydmap/web/ydmap-web-portal/node_modules/eslint-module-utils/resolve.js:83:10)
    at resolve (/Users/tanghui/git/ydmap/web/ydmap-web-portal/node_modules/eslint-module-utils/resolve.js:219:12)
    at Function.get (/Users/tanghui/git/ydmap/web/ydmap-web-portal/node_modules/eslint-plugin-import/src/ExportMap.js:299:16)
    at processBodyStatement (/Users/tanghui/git/ydmap/web/ydmap-web-portal/node_modules/eslint-plugin-import/src/rules/namespace.js:11:27)
    at forEach (/Users/tanghui/git/ydmap/web/ydmap-web-portal/node_modules/eslint-plugin-import/src/rules/namespace.js:82:27)
    at Array.forEach (<anonymous>)
    at Program (/Users/tanghui/git/ydmap/web/ydmap-web-portal/node_modules/eslint-plugin-import/src/rules/namespace.js:82:14)
    at ruleErrorHandler (/Users/tanghui/git/ydmap/web/ydmap-web-portal/node_modules/eslint/lib/linter/linter.js:1114:28)
    at /Users/tanghui/git/ydmap/web/ydmap-web-portal/node_modules/eslint/lib/linter/safe-emitter.js:45:58
    at Array.forEach (<anonymous>)
    at Object.emit (/Users/tanghui/git/ydmap/web/ydmap-web-portal/node_modules/eslint/lib/linter/safe-emitter.js:45:38)
    at NodeEventGenerator.applySelector (/Users/tanghui/git/ydmap/web/ydmap-web-portal/node_modules/eslint/lib/linter/node-event-generator.js:297:26)
    at NodeEventGenerator.applySelectors (/Users/tanghui/git/ydmap/web/ydmap-web-portal/node_modules/eslint/lib/linter/node-event-generator.js:326:22)
    at NodeEventGenerator.enterNode (/Users/tanghui/git/ydmap/web/ydmap-web-portal/node_modules/eslint/lib/linter/node-event-generator.js:340:14)
    at CodePathAnalyzer.enterNode (/Users/tanghui/git/ydmap/web/ydmap-web-portal/node_modules/eslint/lib/linter/code-path-analysis/code-path-analyzer.js:795:23)
    at /Users/tanghui/git/ydmap/web/ydmap-web-portal/node_modules/eslint/lib/linter/linter.js:1149:32
    at Array.forEach (<anonymous>)
    at runRules (/Users/tanghui/git/ydmap/web/ydmap-web-portal/node_modules/eslint/lib/linter/linter.js:1144:15)
    at Linter._verifyWithoutProcessors (/Users/tanghui/git/ydmap/web/ydmap-web-portal/node_modules/eslint/lib/linter/linter.js:1393:31)
[Error - 11:44:00 AM] Connection to server got closed. Server will not be restarted.
[Info  - 11:44:00 AM] ESLint server stopped.
```

**Comment by yoyo837** [comment]
It crashes when I type `import Vue from ''`.

**Comment by yoyo837** [comment]
Thanks for the quick reply, I think I know how to fix it.
