### ISSUE TITLE
Can't fix "'configFile' has been removed. Please use the 'overrideConfigFile' option instead" error

### ISSUE THREAD

**Issue by n8creator** [microsoft/vscode-eslint#1615]
Hi there! I encountered the error `'configFile' has been removed. Please use the 'overrideConfigFile' option instead` while setting up the ESLint Plugin that I can't solve.  I've tried to overcome error by configuring `configFile` / `overrideConfigFile` files via `settings.json` - doesn't helped. Tried to install/configure ESLint globally - doesn't helped too. 

Tried to find a solution to the problem in the closed Issues of the ESLint, as well as on Stackoverflow - couldn't find anything.

Any thoughts how to overcome this problem? Would appreciate any advice!

### Here is my system specs

- Win11 + WSL2 (Ubuntu-20.04) installed
- ESLint extension v.2.4.0 enabled on 'WSL: Ubuntu-20.04'
- ESLint installed locally (tried to install globally)
- [Boilerplate Project with all config settings(github.com)](https://github.com/n8creator/nodejs-package) - contains all config files

Node & `npm` info:

```sh
n8creator@XPS17:~/.../nodejs-package$ which eslint   # installed locally
n8creator@XPS17:~/.../nodejs-package$ node -v
v19.7.0
n8creator@XPS17:~/.../nodejs-package$ which node
/usr/local/bin/node
n8creator@XPS17:~/.../nodejs-package$ npm -v
9.5.0
```

ESlint installed locally:

```sh
n8creator@XPS17:~/.../nodejs-package$ npm ls
@hexlet/nodejs-package@0.0.3 /home/n8creator/test_projects/nodejs-package
├── @jest/globals@29.0.1
├── debug@4.3.4
├── eslint-config-airbnb-base@15.0.0
├── eslint-plugin-import@2.26.0
├── eslint-plugin-jest@27.0.0
├── eslint@8.23.0
├── jest-cli@29.0.1
├── jest@29.0.1
├── lodash@4.17.21
├── npm-check-updates@16.0.6
└── simple-git-hooks@2.8.0
```

`.vscode/settings.json` file settings:

```json
{
  "eslint.enable": true,
  "eslint.run":"onType",
  "eslint.packageManager": "npm",
  "eslint.workingDirectories": [
    {
      "directory": "./",
      "!cwd": true
    }
  ],
  "[javascript]": {
    "editor.defaultFormatter": "dbaeumer.vscode-eslint"
  },
  "[typescript]": {
    "editor.defaultFormatter": "dbaeumer.vscode-eslint"
  },
  "eslint.validate": [
    "javascript",
    "typescript",
    "html"
  ],
  "eslint.format.enable": true,
  "editor.formatOnSave": true,
  "editor.defaultFormatter": "dbaeumer.vscode-eslint",
  "eslint.options": {
    //"configFile": "./.eslintrc.yml",
    "overrideConfigFile": "./.eslintrc.yml"
  },
  "eslint.nodePath": "./node_modules"
}
```

ESLint output message:

```txt
[Info  - 10:57:13 AM] ESLint server is starting.
[Trace - 10:57:13 AM] Sending request 'initialize - (0)'.
[Trace - 10:57:13 AM] Received notification 'window/logMessage'.
[Info  - 10:57:13 AM] ESLint server running in node v16.14.2
[Trace - 10:57:14 AM] Received notification '$/progress'.
[Trace - 10:57:14 AM] Received notification '$/progress'.
[Trace - 10:57:14 AM] Received response 'initialize - (0)' in 346ms.
[Info  - 10:57:14 AM] ESLint server is running.
[Trace - 10:57:14 AM] Sending notification 'initialized'.
[Trace - 10:57:14 AM] Sending notification 'textDocument/didOpen'.
[Trace - 10:57:14 AM] Received request 'client/registerCapability - (0)'.
[Trace - 10:57:14 AM] Sending response 'client/registerCapability - (0)'. Processing request took 1ms
[Trace - 10:57:14 AM] Received request 'client/registerCapability - (1)'.
[Trace - 10:57:14 AM] Sending response 'client/registerCapability - (1)'. Processing request took 1ms
[Trace - 10:57:14 AM] Received request 'workspace/configuration - (2)'.
[Trace - 10:57:14 AM] Sending response 'workspace/configuration - (2)'. Processing request took 16ms
[Trace - 10:57:15 AM] 'npm config get prefix' value is: /usr/local
[Trace - 10:57:15 AM] NODE_PATH value is: /home/n8creator/test_projects/nodejs-package/node_modules
[Trace - 10:57:15 AM] Received notification 'window/logMessage'.
[Info  - 10:57:15 AM] ESLint library loaded from: /home/n8creator/test_projects/nodejs-package/node_modules/eslint/lib/api.js
Uncaught exception received.
Error: Invalid Options:
- Unknown options: configFile
- 'configFile' has been removed. Please use the 'overrideConfigFile' option instead.
    at processOptions (/home/n8creator/test_projects/nodejs-package/node_modules/eslint/lib/eslint/eslint.js:281:15)
    at new ESLint (/home/n8creator/test_projects/nodejs-package/node_modules/eslint/lib/eslint/eslint.js:428:34)
    at q (/home/n8creator/.vscode-server/extensions/dbaeumer.vscode-eslint-2.4.0/server/out/eslintServer.js:1:18361)
    at Object.E [as withClass] (/home/n8creator/.vscode-server/extensions/dbaeumer.vscode-eslint-2.4.0/server/out/eslintServer.js:1:18703)
    at w.then.g.validate (/home/n8creator/.vscode-server/extensions/dbaeumer.vscode-eslint-2.4.0/server/out/eslintServer.js:1:23304)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
Uncaught exception received.
Error: Invalid Options:
- Unknown options: configFile
- 'configFile' has been removed. Please use the 'overrideConfigFile' option instead.
    at processOptions (/home/n8creator/test_projects/nodejs-package/node_modules/eslint/lib/eslint/eslint.js:281:15)
    at new ESLint (/home/n8creator/test_projects/nodejs-package/node_modules/eslint/lib/eslint/eslint.js:428:34)
    at q (/home/n8creator/.vscode-server/extensions/dbaeumer.vscode-eslint-2.4.0/server/out/eslintServer.js:1:18361)
    at Object.E [as withClass] (/home/n8creator/.vscode-server/extensions/dbaeumer.vscode-eslint-2.4.0/server/out/eslintServer.js:1:18703)
    at w.then.g.validate (/home/n8creator/.vscode-server/extensions/dbaeumer.vscode-eslint-2.4.0/server/out/eslintServer.js:1:23304)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

**Comment by MariaSolOs** [comment]
I cloned https://github.com/n8creator/nodejs-package and the extension worked fine:
![image](https://user-images.githubusercontent.com/62502207/223879163-2788254c-294b-49df-bf04-0b085e116420.png)

Indeed, the following settings cause the error:
```
"eslint.options": {
  "configFile": "./.eslintrc.yml",
  //"overrideConfigFile": "./.eslintrc.yml"
},
```
![image](https://user-images.githubusercontent.com/62502207/223879348-6c0f7f64-c853-4f75-8d95-eb353707b3c1.png)

But it gets fixed if I restore them to their original values (removing `configFile` and using `overrideConfigFile`) _AND_ restarting the ESLint server (which is that first option here):
![image](https://user-images.githubusercontent.com/62502207/223879684-c1fe62e9-0f47-456f-b5ee-611db7dceb4e.png)

**Comment by dbaeumer** [comment]
The `eslint.options` setting depends on the ESLint npm version you are using. the ESLint npm package remove the option `configFile` and replaced it with `overrideConfigFile`. This is something the extension can't control. 

Why do you need to override the config file at all. ESLint is very good in detecting the right file.

**Comment by n8creator** [comment]
I found the root of the problem :) I had `eslint.options` setting configured both _globally_ (global `settings.json` file) and _locally_ (local `.vscode/settings.json` file), and these files been conflicting each with other. 

Deleted `eslint.options` in both files and now ESLint works fine!
