### ISSUE TITLE
vscdode-eslint fails to load the extended rules

### ISSUE THREAD

**Issue by hirvinen** [microsoft/vscode-eslint#1625]
I have a monorepo setup, but I suspect that that is not relevant here, because I can run eslint successfully from the command line. Vscode-eslint output:
```
Uncaught exception received.
Error: Cannot find module '../../conf/eslint-recommended.js'
Require stack:
- /path/to/project/node_modules/eslint/lib/cli-engine/cli-engine.js
- /path/to/project/node_modules/eslint/lib/eslint/eslint.js
- /path/to/project/node_modules/eslint/lib/eslint/index.js
- /path/to/project/node_modules/eslint/lib/api.js
- /home/patrik/.vscode-server/extensions/dbaeumer.vscode-eslint-2.4.0/server/out/eslintServer.js
Referenced from: /path/to/project/.eslintrc.cjs
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.mod._resolveFilename (/path/to/project/node_modules/eslint-config-next/index.js:49:26)
    at Function.mod._resolveFilename (/path/to/project/node_modules/eslint-config-next/index.js:49:26)
    at Function.mod._resolveFilename (/path/to/project/node_modules/eslint-config-next/index.js:49:26)
    at Function.mod._resolveFilename (/path/to/project/node_modules/eslint-config-next/index.js:49:26)
    at Function.mod._resolveFilename (/path/to/project/node_modules/eslint-config-next/index.js:49:26)
    at Function.mod._resolveFilename (/path/to/project/node_modules/eslint-config-next/index.js:49:26)
    at Function.mod._resolveFilename (/path/to/project/node_modules/eslint-config-next/index.js:49:26)
    at Function.mod._resolveFilename (/path/to/project/node_modules/eslint-config-next/index.js:49:26)
    at Function.mod._resolveFilename (/path/to/project/node_modules/eslint-config-next/index.js:49:26)
```

Example output from cli to make sure the config is working there.
```
/path/to/project/root $ npx eslint apps/api/src/eslint-test.ts

/path/to/project/apps/api/src/eslint-test.ts
  1:1  error  Unexpected var, use let or const instead  no-var
  1:5  error  'foo' is assigned a value but never used  @typescript-eslint/no-unused-vars

✖ 2 problems (2 errors, 0 warnings)
  1 error and 0 warnings potentially fixable with the `--fix` option.
```

`/path/to/project/.eslintrc.cjs`:
```
module.exports = {
  extends: [
    'eslint:recommended',
  ],
  plugins: [
    '@typescript-eslint',
    'react',
    'import',
  ],
  parser: '@typescript-eslint/parser',
  overrides: [
    {
      files: [
        "**/*.ts",
        "**/*.tsx"
      ],
      extends: [
        'eslint:recommended',
        'plugin:@typescript-eslint/recommended',
        'plugin:@typescript-eslint/recommended-requiring-type-checking',
        'airbnb-typescript',
        'prettier',
      ],
      parserOptions: {
        project: [
          './tsconfig.eslint.json',
          './packages/**/tsconfig.json',
          './apps/**/tsconfig.json',
        ],
        tsconfigRootDir: __dirname,
      },
    }
  ],
  root: true,
};
```

Versions:

- eslint: 8.37.0
- vscode: 1.76.2
- vscode-eslint: 2.4.0
- npm: 9.5.1
- node: 19.8.1

If relevant, my project is on Ubuntu running under WSL2 on Windows 11.

**Comment by dbaeumer** [comment]
In mono repositories it is essential to configure `eslint.workingdirectories` to let the ESLint server now about the structure. If you `chdir` into certain folders to get eslint run correctly in the terminal these directories are usually a good indication for the working directories to use in ESLint extension. 

Let me know if this helps.

**Comment by hirvinen** [comment]
Hi, sorry I was unclear about this. I can run eslint cli from the project root without issues. In fact, I need to run it from there, since my `.eslintrc.cjs` lives there.

However, just now I realized that the extension is working as expected, so I guess you can close the issue. That's kind of mysterious since I haven't restarted vs code, haven't changed any configs even remotely related to it, and the only new thing I've installed since filing the issue is jest...

**Comment by dbaeumer** [comment]
Thanks for getting back. I will close the issue.
