### ISSUE TITLE
Non-package project  always throws unmanaged exception  (No ESLint configuration found))

### ISSUE THREAD

**Issue by Kein** [microsoft/vscode-eslint#1643]
I'm writing a single-file userscript for one of the *Monkey extensions and I want to leverage Typescript to cut down on basic issues/errors. I basically have one `MyScript.ts` file with I compile with `tsc` into javascript one. 
However, it seems like ESLint is unable to work with such basic setup, it constantly crashes and throws errors:

```
[Info  - 2:36:24 AM] ESLint server is starting
[Info  - 2:36:25 AM] ESLint server running in node v16.13.0
[Info  - 2:36:25 AM] ESLint server is running.
[Info  - 2:36:25 AM] ESLint library loaded from: d:\Programs\NodeJS\node_modules\eslint\lib\api.js
Uncaught exception received.
Error: No ESLint configuration found in D:\GIT\JS\TestScript\src.
    at CascadingConfigArrayFactory._finalizeConfigArray (d:\Programs\NodeJS\node_modules\eslint\node_modules\@eslint\eslintrc\dist\eslintrc.cjs:3977:19)
    at CascadingConfigArrayFactory.getConfigArrayForFile (d:\Programs\NodeJS\node_modules\eslint\node_modules\@eslint\eslintrc\dist\eslintrc.cjs:3768:21)
    at CLIEngine.getConfigForFile (d:\Programs\NodeJS\node_modules\eslint\lib\cli-engine\cli-engine.js:969:14)
    at ESLint.calculateConfigForFile (d:\Programs\NodeJS\node_modules\eslint\lib\eslint\eslint.js:667:26)
    at c:\Programs\VSCode\data\extensions\dbaeumer.vscode-eslint-2.2.2\server\out\eslintServer.js:1:176344
    at Ce (c:\Programs\VSCode\data\extensions\dbaeumer.vscode-eslint-2.2.2\server\out\eslintServer.js:1:186295)
    at h.then.o.validate (c:\Programs\VSCode\data\extensions\dbaeumer.vscode-eslint-2.2.2\server\out\eslintServer.js:1:176323)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

Now, I know I can probably solve it via `npm init` and the follow-up with `eslint --init` but the thing is, this is not a npm package, it just a single-file script and all I need is basic semantic and linting and some error/syntax checking features working, **THAT'S IT.** Why I'm required to have a complexity of full-fledged npm package setup?

**Comment by dbaeumer** [comment]
The reason for that is that the extension doesn't ship its own version of ESLint npm module (mainly to give users the flexibility of deciding which versions to use).

There is actually no need to do a full npm package setup. You can also install ESLint globally and have a eslint config file in your user directory. The extension will respect that.

**Comment by Kein** [comment]
> You can also install ESLint globally

The thing is, I do have it installed globally.

**Comment by Kein** [comment]
Also, why is this closed? It is a valid issue.

```
C:\>npm list -g --depth 0
d:\Programs\NodeJS
+-- @typescript-eslint/eslint-plugin@5.59.0
+-- @typescript-eslint/parser@5.59.0
+-- babel-eslint@10.1.0
+-- brotli@1.3.3
+-- corepack@0.17.0
+-- eslint-plugin-react@7.32.2
+-- eslint@8.39.0
+-- generator-code@1.7.5
+-- gulp@4.0.2
+-- jshint@2.13.6
+-- npm-check-updates@16.10.9
+-- npm@9.6.5
+-- typescript@5.0.4
+-- web-ext@7.6.1
+-- yarn@1.22.19
`-- yo@4.3.1
```

**.eslintrc.json**
```
{
    "env": {
        "browser": true,
        "es2021": true
    },
    "extends": [
        "eslint:recommended",
        "plugin:@typescript-eslint/recommended"
    ],
    "overrides": [
    ],
    "parser": "@typescript-eslint/parser",
    "parserOptions": {
        "ecmaVersion": "latest"
    },
    "plugins": [
        "@typescript-eslint"
    ],
    "rules": {
        "indent": [
            "error",
            4
        ],
        "linebreak-style": [
            "error",
            "windows"
        ],
        "quotes": [
            "warn",
            "single",
            { "avoidEscape": true, "allowTemplateLiterals": true }
        ],
        "semi": [
            "error",
            "always"
        ]
    }
}
```

Yet I'm still unable to use it:
```
Error: Failed to load plugin '@typescript-eslint' declared in '.eslintrc.json': Cannot find module '@typescript-eslint/eslint-plugin'
Require stack:
```
