### ISSUE TITLE
[Bug] Not working if you open project in `git worktree`

### ISSUE THREAD

**Issue by Profesor08** [microsoft/vscode-eslint#1704]
If you working in some git repository, and create an git worktree, and open it in new vscode window, eslint will stop working. It will not show any warnings or errors.

### Reproduction steps:

1. clone git repo: https://github.com/Profesor08/vscode-eslint-1704
2. open in vscode
3. install dependencies `npm i`
4. create worktree `git worktree add test-worktree`
5. open test-worktree in vscode
6. install dependencies `npm i`
7. open `src/index.tsx`
8. there will be no warnings

If warning exists, close all vscode windows and open in worktree

### Expected result to see some warning:

![image](https://github.com/microsoft/vscode-eslint/assets/8218016/c328db0b-d655-41d4-841c-11ab0161ed2f)

### How to check if it reads config from parent directory?

Just add some unknown plugin extends `"omg-some-unknown"` and run `npx eslint .` in worktree.

```
$ npx eslint .

Oops! Something went wrong! :(

ESLint: 8.47.0

ESLint couldn't find the config "omg-some-shit" to extend from. Please check that the name of the config is correct.

The config "omg-some-shit" was referenced from the config file in "C:\Users\prof\Desktop\vscode-eslint-1704\.eslintrc".

If you still have problems, please stop by https://eslint.org/chat/help to chat with the team.
```

**Comment by Profesor08** [comment]
Also it reads config from main git repository but not from worktree if I use cli `npx eslint .`

**Comment by dbaeumer** [comment]
Can you please provide me with a GitHub repository I can clone with steps on how you created the worktree.

**Comment by Profesor08** [comment]
@dbaeumer i have added additional info

**Comment by dbaeumer** [comment]
I cloned the repository and followed the steps but can't reproduce the problem

<img width="666" alt="image" src="https://github.com/microsoft/vscode-eslint/assets/1931590/10f77b86-8e40-4ba1-b8db-b9e23218f692">

**Comment by dbaeumer** [comment]
Any additional steps?

**Comment by Profesor08** [comment]
I forget about vscode version. I use Insiders Preview to have acces to Copilot. There is version:

```
Version: 1.82.0-insider (user setup)
Commit: f7973f357e7c316a88e8817886f41a843021fe74
Date: 2023-08-28T05:35:52.131Z
Electron: 25.5.0
ElectronBuildId: 23084831
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Windows_NT x64 10.0.22621
```

**Comment by Profesor08** [comment]
Additionaly, I have tried to restart ESlint server, and get error.

```
[Error - 10:56:23 AM] Restarting client failed
Error: Stopping the server timed out
    at c:\Users\prof\.vscode-insiders\extensions\dbaeumer.vscode-eslint-2.4.2\client\out\extension.js:1:104373
    at w.restart (c:\Users\prof\.vscode-insiders\extensions\dbaeumer.vscode-eslint-2.4.2\client\out\extension.js:1:265414)
```

**Comment by Profesor08** [comment]
After a few tries, I get this error with some conflicts

```
[Info  - 11:07:32 AM] ESLint server is starting.
[Info  - 11:07:32 AM] ESLint server running in node v18.15.0
[Info  - 11:07:32 AM] ESLint server is running.
[Info  - 11:07:33 AM] ESLint library loaded from: C:\Users\prof\Desktop\vscode-eslint-1704\test-worktree\node_modules\eslint\lib\api.js
Uncaught exception received.
Error: Plugin "react" was conflicted between ".eslintrc" and "..\.eslintrc".
    at mergePlugins (C:\Users\prof\Desktop\vscode-eslint-1704\test-worktree\node_modules\@eslint\eslintrc\dist\eslintrc.cjs:598:19)
    at createConfig (C:\Users\prof\Desktop\vscode-eslint-1704\test-worktree\node_modules\@eslint\eslintrc\dist\eslintrc.cjs:701:9)
    at ConfigArray.extractConfig (C:\Users\prof\Desktop\vscode-eslint-1704\test-worktree\node_modules\@eslint\eslintrc\dist\eslintrc.cjs:877:33)
    at CLIEngine.getConfigForFile (C:\Users\prof\Desktop\vscode-eslint-1704\test-worktree\node_modules\eslint\lib\cli-engine\cli-engine.js:981:14)
    at ESLint.calculateConfigForFile (C:\Users\prof\Desktop\vscode-eslint-1704\test-worktree\node_modules\eslint\lib\eslint\eslint.js:667:26)
    at c:\Users\prof\.vscode-insiders\extensions\dbaeumer.vscode-eslint-2.4.2\server\out\eslintServer.js:1:22644
    at Object.E [as withClass] (c:\Users\prof\.vscode-insiders\extensions\dbaeumer.vscode-eslint-2.4.2\server\out\eslintServer.js:1:19218)
    at w.then.g.validate (c:\Users\prof\.vscode-insiders\extensions\dbaeumer.vscode-eslint-2.4.2\server\out\eslintServer.js:1:22610)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
Uncaught exception received.
Error: Plugin "react" was conflicted between ".eslintrc" and "..\.eslintrc".
    at mergePlugins (C:\Users\prof\Desktop\vscode-eslint-1704\test-worktree\node_modules\@eslint\eslintrc\dist\eslintrc.cjs:598:19)
    at createConfig (C:\Users\prof\Desktop\vscode-eslint-1704\test-worktree\node_modules\@eslint\eslintrc\dist\eslintrc.cjs:701:9)
    at ConfigArray.extractConfig (C:\Users\prof\Desktop\vscode-eslint-1704\test-worktree\node_modules\@eslint\eslintrc\dist\eslintrc.cjs:877:33)
    at CLIEngine.getConfigForFile (C:\Users\prof\Desktop\vscode-eslint-1704\test-worktree\node_modules\eslint\lib\cli-engine\cli-engine.js:981:14)
    at ESLint.calculateConfigForFile (C:\Users\prof\Desktop\vscode-eslint-1704\test-worktree\node_modules\eslint\lib\eslint\eslint.js:667:26)
    at c:\Users\prof\.vscode-insiders\extensions\dbaeumer.vscode-eslint-2.4.2\server\out\eslintServer.js:1:22644
    at Object.E [as withClass] (c:\Users\prof\.vscode-insiders\extensions\dbaeumer.vscode-eslint-2.4.2\server\out\eslintServer.js:1:19218)
    at w.then.g.validate (c:\Users\prof\.vscode-insiders\extensions\dbaeumer.vscode-eslint-2.4.2\server\out\eslintServer.js:1:22610)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

**Comment by dbaeumer** [comment]
Works for me in Insider as well.

Does validation happen for you correctly in the terminal? From the traces this looks more like a ESLint problem itself than a problem with the extension.

**Comment by Profesor08** [comment]
@dbaeumer if fails in terminal too

```
$ npx eslint .

Oops! Something went wrong! :(

ESLint: 8.47.0

ESLint couldn't determine the plugin "react" uniquely.

- C:\Users\prof\Desktop\vscode-eslint-1704\test-worktree\node_modules\eslint-plugin-react\index.js (loaded in ".eslintrc")
- C:\Users\prof\Desktop\vscode-eslint-1704\node_modules\eslint-plugin-react\index.js (loaded in "..\.eslintrc")

Please remove the "plugins" setting from either config or remove either plugin installation.

If you still can't figure out the problem, please stop by https://eslint.org/chat/help to chat with the team.
```

**Comment by dbaeumer** [comment]
If it fails in the terminal it will fail in the extension has well since both use the same underlying npm library. The only suggestion I can make is to get it working in the terminal first. If it works there and still fails in the extension then please ping me and I will re-open the issue.
