### ISSUE TITLE
ESLint error in output when starting the codespace in github (NOT NOTICEABLE?)

### ISSUE THREAD

**Issue by nogalogg** [microsoft/vscode-eslint#1728]
I'm using the latest vscode-eslint and the latest eslint installed with pnpm as a devdependency.
Everytime i start the github codespace, this appears in the ESLint output:

```
[Info  - 11:15:19 AM] ESLint server is starting.
[Info  - 11:15:22 AM] ESLint server running in node v18.15.0
[Info  - 11:15:22 AM] ESLint server is running.
[Info  - 11:15:28 AM] ESLint library loaded from: /workspaces/exoBOT/node_modules/.pnpm/eslint@8.53.0/node_modules/eslint/lib/api.js
Uncaught exception received.
Error: Invalid Options:
- Unknown options: esversion
    at processOptions (/workspaces/exoBOT/node_modules/.pnpm/eslint@8.53.0/node_modules/eslint/lib/eslint/eslint.js:282:15)
    at new ESLint (/workspaces/exoBOT/node_modules/.pnpm/eslint@8.53.0/node_modules/eslint/lib/eslint/eslint.js:429:34)
    at q (/home/codespace/.vscode-remote/extensions/dbaeumer.vscode-eslint-2.4.2/server/out/eslintServer.js:1:18675)
    at Object.E [as withClass] (/home/codespace/.vscode-remote/extensions/dbaeumer.vscode-eslint-2.4.2/server/out/eslintServer.js:1:19173)
    at w.then.g.validate (/home/codespace/.vscode-remote/extensions/dbaeumer.vscode-eslint-2.4.2/server/out/eslintServer.js:1:23774)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
Uncaught exception received.
Error: Invalid Options:
- Unknown options: esversion
    at processOptions (/workspaces/exoBOT/node_modules/.pnpm/eslint@8.53.0/node_modules/eslint/lib/eslint/eslint.js:282:15)
    at new ESLint (/workspaces/exoBOT/node_modules/.pnpm/eslint@8.53.0/node_modules/eslint/lib/eslint/eslint.js:429:34)
    at q (/home/codespace/.vscode-remote/extensions/dbaeumer.vscode-eslint-2.4.2/server/out/eslintServer.js:1:18675)
    at Object.E [as withClass] (/home/codespace/.vscode-remote/extensions/dbaeumer.vscode-eslint-2.4.2/server/out/eslintServer.js:1:19173)
    at w.then.g.validate (/home/codespace/.vscode-remote/extensions/dbaeumer.vscode-eslint-2.4.2/server/out/eslintServer.js:1:23774)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
Uncaught exception received.
Error: Invalid Options:
- Unknown options: esversion
    at processOptions (/workspaces/exoBOT/node_modules/.pnpm/eslint@8.53.0/node_modules/eslint/lib/eslint/eslint.js:282:15)
    at new ESLint (/workspaces/exoBOT/node_modules/.pnpm/eslint@8.53.0/node_modules/eslint/lib/eslint/eslint.js:429:34)
    at q (/home/codespace/.vscode-remote/extensions/dbaeumer.vscode-eslint-2.4.2/server/out/eslintServer.js:1:18675)
    at Object.E [as withClass] (/home/codespace/.vscode-remote/extensions/dbaeumer.vscode-eslint-2.4.2/server/out/eslintServer.js:1:19173)
    at w.then.g.validate (/home/codespace/.vscode-remote/extensions/dbaeumer.vscode-eslint-2.4.2/server/out/eslintServer.js:1:23774)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
Uncaught exception received.
Error: Invalid Options:
- Unknown options: esversion
    at processOptions (/workspaces/exoBOT/node_modules/.pnpm/eslint@8.53.0/node_modules/eslint/lib/eslint/eslint.js:282:15)
    at new ESLint (/workspaces/exoBOT/node_modules/.pnpm/eslint@8.53.0/node_modules/eslint/lib/eslint/eslint.js:429:34)
    at q (/home/codespace/.vscode-remote/extensions/dbaeumer.vscode-eslint-2.4.2/server/out/eslintServer.js:1:18675)
    at Object.E [as withClass] (/home/codespace/.vscode-remote/extensions/dbaeumer.vscode-eslint-2.4.2/server/out/eslintServer.js:1:19173)
    at w.then.g.validate (/home/codespace/.vscode-remote/extensions/dbaeumer.vscode-eslint-2.4.2/server/out/eslintServer.js:1:23774)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
Uncaught exception received.
Error: Invalid Options:
- Unknown options: esversion
    at processOptions (/workspaces/exoBOT/node_modules/.pnpm/eslint@8.53.0/node_modules/eslint/lib/eslint/eslint.js:282:15)
    at new ESLint (/workspaces/exoBOT/node_modules/.pnpm/eslint@8.53.0/node_modules/eslint/lib/eslint/eslint.js:429:34)
    at q (/home/codespace/.vscode-remote/extensions/dbaeumer.vscode-eslint-2.4.2/server/out/eslintServer.js:1:18675)
    at Object.E [as withClass] (/home/codespace/.vscode-remote/extensions/dbaeumer.vscode-eslint-2.4.2/server/out/eslintServer.js:1:19173)
    at w.then.g.validate (/home/codespace/.vscode-remote/extensions/dbaeumer.vscode-eslint-2.4.2/server/out/eslintServer.js:1:23774)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
Uncaught exception received.
Error: Invalid Options:
- Unknown options: esversion
    at processOptions (/workspaces/exoBOT/node_modules/.pnpm/eslint@8.53.0/node_modules/eslint/lib/eslint/eslint.js:282:15)
    at new ESLint (/workspaces/exoBOT/node_modules/.pnpm/eslint@8.53.0/node_modules/eslint/lib/eslint/eslint.js:429:34)
    at q (/home/codespace/.vscode-remote/extensions/dbaeumer.vscode-eslint-2.4.2/server/out/eslintServer.js:1:18675)
    at Object.E [as withClass] (/home/codespace/.vscode-remote/extensions/dbaeumer.vscode-eslint-2.4.2/server/out/eslintServer.js:1:19173)
    at w.then.g.validate (/home/codespace/.vscode-remote/extensions/dbaeumer.vscode-eslint-2.4.2/server/out/eslintServer.js:1:23774)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

I don't know why it's running in Node v18.15.0, but i have v21.1.0 installed.
Although this error appears, i do not notice any errors yet: i just want to contribute.

this is how my eslintrc is configured:

```
{
	"extends": "eslint:recommended",
	"env": {
		"node": true,
		"es6": true
	},
	"parserOptions": {
		"ecmaVersion": 2022,
		"sourceType": "module"
	}
}
```

**Comment by dbaeumer** [comment]
@nogalogg the extension used by default the node version that comes with VS Code. You can set `eslint.runtime` to point to a different node version. If it is on the path you can use `"eslint.runtime":"node"`

Do you see the same error message when validating the file in the terminal?
