### ISSUE TITLE
Error: Cannot find module 'node:util'

### ISSUE THREAD

**Issue by carrrywu** [microsoft/vscode-eslint#1775]
Error: Cannot find module 'node:util'
Require stack:
- c:\Users\...\.vscode\extensions\dbaeumer.vscode-eslint-2.4.4\server\out\eslintServer.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.7261 (c:\Users\...\.vscode\extensions\dbaeumer.vscode-eslint-2.4.4\server\out\eslintServer.js:1:176395)
    at n (c:\Users\...\.vscode\extensions\dbaeumer.vscode-eslint-2.4.4\server\out\eslintServer.js:1:215913)
    at Object.5809 (c:\Users\...\.vscode\extensions\dbaeumer.vscode-eslint-2.4.4\server\out\eslintServer.js:1:173195)
    at n (c:\Users\...\.vscode\extensions\dbaeumer.vscode-eslint-2.4.4\server\out\eslintServer.js:1:215913)
    at Object.8212 (c:\Users\...\.vscode\extensions\dbaeumer.vscode-eslint-2.4.4\server\out\eslintServer.js:1:176215)
    at n (c:\Users\...\.vscode\extensions\dbaeumer.vscode-eslint-2.4.4\server\out\eslintServer.js:1:215913) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'c:\\Users\\...\\.vscode\\extensions\\dbaeumer.vscode-eslint-2.4.4\\server\\out\\eslintServer.js'
  ]

**Comment by carrrywu** [comment]
Replace the code "require("node:util")" in eslintServer.js with "require("util")" fix the error.

**Comment by dbaeumer** [comment]
Are you using an old node version?

**Comment by aladdin-add** [comment]
node protocol was introduced in node 16, so you need to upgrade your node.js.

refs: https://nodejs.org/api/esm.html#node-imports

**Comment by dbaeumer** [comment]
@aladdin-add thanks.

Will close the issue assuming that updating node will fix this.
