### ISSUE TITLE
error: `Request textDocument/codeAction failed with message: Range#create called with invalid arguments[[object Object], [object Object], undefined, undefined]`

### ISSUE THREAD

**Issue by ulugbekna** [microsoft/vscode-eslint#1931]
Not sure how to repro, but I get this error in dev console: 

```
 ERR Request textDocument/codeAction failed with message: Range#create called with invalid arguments[[object Object], [object Object], undefined, undefined]: Error: Request textDocument/codeAction failed with message: Range#create called with invalid arguments[[object Object], [object Object], undefined, undefined]
    at ae (/Users/ulugbekna/.vscode-insiders/extensions/dbaeumer.vscode-eslint-3.0.10/client/out/extension.js:1:41596)
    at re (/Users/ulugbekna/.vscode-insiders/extensions/dbaeumer.vscode-eslint-3.0.10/client/out/extension.js:1:39556)
    at Immediate.<anonymous> (/Users/ulugbekna/.vscode-insiders/extensions/dbaeumer.vscode-eslint-3.0.10/client/out/extension.js:1:35850)
    at processImmediate (node:internal/timers:478:21)
```

![Image](https://github.com/user-attachments/assets/99e862ea-c7a2-4943-8a5b-d3942e374020)

Feel free to close if not actionable.

**Comment by dbaeumer** [comment]
Hard to say. It tries to create a range with invalid positions, but unsure why. I think they come invalid from ESLint. If you can have steps or a file you are seeing it in would be helpful.

**Comment by xkeshav** [comment]
facing same issues.

vs code v 1.94.1
OS: Ubuntu 24.04

having below settings in _settings.json_ and also in _.code-workspace_ file

```json
  "editor.codeActionsOnSave": {
    "source.fixAll.eslint": "explicit",
    "source.fixAll": "explicit",
    "source.organizeImports": "explicit"
  },
  "eslint.useFlatConfig": true,
  "eslint.validate": [
    "mdx",
    "javascript",
    "typescript"
  ],
  "eslint.options": {
    "extensions": [
      ".js",
      ".md",
    ],
  },
````
and whenever we save js /md file it gives below message in Vs Code Output Panel
```
2024-10-09 19:16:06.781 [error] [dbaeumer.vscode-eslint] provider FAILED
2024-10-09 19:16:06.781 [error] Error: Request textDocument/codeAction failed with message: Invalid Options:
- Unknown options: extensions
- 'extensions' has been removed.
    at ae (/home/recursive/.vscode/extensions/dbaeumer.vscode-eslint-3.0.10/client/out/extension.js:1:41596)
    at re (/home/recursive/.vscode/extensions/dbaeumer.vscode-eslint-3.0.10/client/out/extension.js:1:39556)
    at Immediate.<anonymous> (/home/recursive/.vscode/extensions/dbaeumer.vscode-eslint-3.0.10/client/out/extension.js:1:35850)
    at processImmediate (node:internal/timers:483:21)

```

**Comment by dbaeumer** [comment]
@xkeshav any steps on how to reproduce this. Would like to understand why this is happening. Simply dropping the range / problem is not a good fix.

**Comment by xkeshav** [comment]
@dbaeumer  here is minimal repruction repo link using vs code web: https://stunning-guacamole-vw7vgxx5qfwp94.github.dev/

please check the README and let me know if it help.

Thanks

**Comment by dbaeumer** [comment]
@xkeshav I can't access that code space. Could you provide me with a GitHub repository I can clone.

**Comment by xkeshav** [comment]
Oh. Why access issue? No I haven't made any repo but just open codespace and write.

Is there any other way? Stackblitz does not give the option to install extension 


Let me check the access issue.

**Comment by xkeshav** [comment]
here is[ the repo ](https://github.com/xkeshav/test/) ; please check and let me know whether you are able to generate

**Comment by dbaeumer** [comment]
```
- 'extensions' has been removed.
    at ae (/home/codespace/.vscode-remote/extensions/dbaeumer.vscode-eslint-3.0.10/client/out/extension.js:1:41596)
    at re (/home/codespace/.vscode-remote/extensions/dbaeumer.vscode-eslint-3.0.10/client/out/extension.js:1:39556)
    at Immediate.<anonymous> (/home/codespace/.vscode-remote/extensions/dbaeumer.vscode-eslint-3.0.10/client/out/extension.js:1:35850)
    at processImmediate (node:internal/timers:483:21)
```

comes from the fact that you have this

```
```

**Comment by dbaeumer** [comment]
How would I reproduce the `Request textDocument/codeAction failed with message: Range#create called with invalid arguments[[object Object], [object Object], undefined, undefined]` error with your example?

**Comment by xkeshav** [comment]
my issue has been resolved by removing the settings . Thanks @dbaeumer

**Comment by dbaeumer** [comment]
I will close the issue for now since I can't reproduce this. 

As soon as someone can, please ping and I will re-open the issue.

**Comment by cklimowski1** [comment]
> I will close the issue for now since I can't reproduce this.
> 
> As soon as someone can, please ping and I will re-open the issue.

I am still having this issue. Please let me know what information you need from me.

**Comment by dbaeumer** [comment]
@cklimowski1 best would be a repository I can clone, including steps on how to reprodoce, that demos the problem.

**Comment by dbaeumer** [comment]
@cklimowski1 actually no. A repro case will be great.

**Comment by zdenkolini** [comment]
I fixed this by deleting this from my user and project settings.

```json
  "eslint.options": {
    "extensions": [
      ".js",
      ".md",
    ],
  }
```

**Comment by neotan** [comment]
> ```
> - 'extensions' has been removed.
>     at ae (/home/codespace/.vscode-remote/extensions/dbaeumer.vscode-eslint-3.0.10/client/out/extension.js:1:41596)
>     at re (/home/codespace/.vscode-remote/extensions/dbaeumer.vscode-eslint-3.0.10/client/out/extension.js:1:39556)
>     at Immediate.<anonymous> (/home/codespace/.vscode-remote/extensions/dbaeumer.vscode-eslint-3.0.10/client/out/extension.js:1:35850)
>     at processImmediate (node:internal/timers:483:21)
> ```
> 
> comes from the fact that you have this
> 
> ```
>     "eslint.options": {
>       "extensions": [
>         ".js",
>         ".md",
>       ],
>     },
> ```
> 
> in your workspace file. In ESLint 9.x the extensions setting is not supported anymore since you use sections in the config file instead.

Thanks for the solution!

my case was a little bit tricky when I got the error in the `View > Appearance > Panel > tab Output > dropdown ESLint`

```
[Error - 10:22:10 AM] Request textDocument/diagnostic failed.
  Message: Request textDocument/diagnostic failed with message: Invalid Options:
- Unknown options: extensions
- 'extensions' has been removed.
  Code: -32603 
```

i have nothing about `extensions` in `my-project/.vscode/settings.json` but in 
- **VS Code**: `%userprofile%\AppData\Roaming\Code\User\settings.json`
- **Cursor**: `%userprofile%\AppData\Roaming\Cursor\User\settings.json`

making changes according to the error msgs under `eslint.options: {...}` fixed the issues. hope it helps.
