### ISSUE TITLE
Failed to load plugin 'react-hooks' declared in ' » eslint-config-next/core-web-vitals » Cannot find module 'eslint-plugin-react-hooks'

### ISSUE THREAD

**Issue by J4v4Scr1pt** [microsoft/vscode-eslint#1960]
I'm upgrading to NextJS 15 together with ESLint 9. But I keep getting this error on the ESLint Exstension output:
![Image](https://github.com/user-attachments/assets/62c53dcd-8014-4fee-a6c3-a536c6f295dd)

```
[Info  - 1:16:45 PM] ESLint server is starting.
[Info  - 1:16:46 PM] ESLint server running in node v22.12.0
[Info  - 1:16:46 PM] ESLint server is running.
[Info  - 1:16:48 PM] ESLint library loaded from: C:\Workspace\ThnJK\node_modules\.pnpm\eslint@9.17.0\node_modules\eslint\lib\api.js
[Error - 1:16:50 PM] Calculating config file for file:///c%3A/Workspace/ThnJK/next.config.mjs) failed.
Error: Failed to load plugin 'react-hooks' declared in ' » eslint-config-next/core-web-vitals » C:\Workspace\ThnJK\node_modules\.pnpm\eslint-config-next@15.1.0_eslint@9.17.0_typescript@5.7.2\node_modules\eslint-config-next\index.js': Cannot find module 'eslint-plugin-react-hooks'
Require stack:
- C:\Workspace\ThnJK\__placeholder__.js
Referenced from: C:\Workspace\ThnJK\node_modules\.pnpm\eslint-config-next@15.1.0_eslint@9.17.0_typescript@5.7.2\node_modules\eslint-config-next\index.js
    at Function.<anonymous> (node:internal/modules/cjs/loader:1249:15)
    at mod._resolveFilename (C:\Workspace\ThnJK\node_modules\.pnpm\eslint-config-next@15.1.0_eslint@9.17.0_typescript@5.7.2\node_modules\eslint-config-next\index.js:50:26)
    at Function.resolve (node:internal/modules/helpers:148:19)
    at Module.resolve (file:///C:/Workspace/ThnJK/node_modules/.pnpm/@eslint+eslintrc@3.2.0/node_modules/@eslint/eslintrc/lib/shared/relative-module-resolver.js:23:46)
    at ConfigArrayFactory._loadPlugin (file:///C:/Workspace/ThnJK/node_modules/.pnpm/@eslint+eslintrc@3.2.0/node_modules/@eslint/eslintrc/lib/config-array-factory.js:1068:33)
    at ConfigArrayFactory._loadExtendedPluginConfig (file:///C:/Workspace/ThnJK/node_modules/.pnpm/@eslint+eslintrc@3.2.0/node_modules/@eslint/eslintrc/lib/config-array-factory.js:887:29)
    at ConfigArrayFactory._loadExtends (file:///C:/Workspace/ThnJK/node_modules/.pnpm/@eslint+eslintrc@3.2.0/node_modules/@eslint/eslintrc/lib/config-array-factory.js:808:29)
    at ConfigArrayFactory._normalizeObjectConfigDataBody (file:///C:/Workspace/ThnJK/node_modules/.pnpm/@eslint+eslintrc@3.2.0/node_modules/@eslint/eslintrc/lib/config-array-factory.js:749:25)
    at _normalizeObjectConfigDataBody.next (<anonymous>)
    at ConfigArrayFactory._normalizeObjectConfigData (file:///C:/Workspace/ThnJK/node_modules/.pnpm/@eslint+eslintrc@3.2.0/node_modules/@eslint/eslintrc/lib/config-array-factory.js:694:20)
[Error - 1:16:50 PM] Calculating config file for file:///c%3A/Workspace/ThnJK/package.json) failed.
Error: Failed to load plugin 'react-hooks' declared in ' » eslint-config-next/core-web-vitals » C:\Workspace\ThnJK\node_modules\.pnpm\eslint-config-next@15.1.0_eslint@9.17.0_typescript@5.7.2\node_modules\eslint-config-next\index.js': Cannot find module 'eslint-plugin-react-hooks'
Require stack:
- C:\Workspace\ThnJK\__placeholder__.js
Referenced from: C:\Workspace\ThnJK\node_modules\.pnpm\eslint-config-next@15.1.0_eslint@9.17.0_typescript@5.7.2\node_modules\eslint-config-next\index.js
    at Function.<anonymous> (node:internal/modules/cjs/loader:1249:15)
    at mod._resolveFilename (C:\Workspace\ThnJK\node_modules\.pnpm\eslint-config-next@15.1.0_eslint@9.17.0_typescript@5.7.2\node_modules\eslint-config-next\index.js:50:26)
    at Function.resolve (node:internal/modules/helpers:148:19)
    at Module.resolve (file:///C:/Workspace/ThnJK/node_modules/.pnpm/@eslint+eslintrc@3.2.0/node_modules/@eslint/eslintrc/lib/shared/relative-module-resolver.js:23:46)
    at ConfigArrayFactory._loadPlugin (file:///C:/Workspace/ThnJK/node_modules/.pnpm/@eslint+eslintrc@3.2.0/node_modules/@eslint/eslintrc/lib/config-array-factory.js:1068:33)
    at ConfigArrayFactory._loadExtendedPluginConfig (file:///C:/Workspace/ThnJK/node_modules/.pnpm/@eslint+eslintrc@3.2.0/node_modules/@eslint/eslintrc/lib/config-array-factory.js:887:29)
    at ConfigArrayFactory._loadExtends (file:///C:/Workspace/ThnJK/node_modules/.pnpm/@eslint+eslintrc@3.2.0/node_modules/@eslint/eslintrc/lib/config-array-factory.js:808:29)
    at ConfigArrayFactory._normalizeObjectConfigDataBody (file:///C:/Workspace/ThnJK/node_modules/.pnpm/@eslint+eslintrc@3.2.0/node_modules/@eslint/eslintrc/lib/config-array-factory.js:749:25)
    at _normalizeObjectConfigDataBody.next (<anonymous>)
    at ConfigArrayFactory._normalizeObjectConfigData (file:///C:/Workspace/ThnJK/node_modules/.pnpm/@eslint+eslintrc@3.2.0/node_modules/@eslint/eslintrc/lib/config-array-factory.js:694:20)
```

I opened an ticket on Vercel but then realized that running `next lint` works, and also during the build.
Running  `npx eslint --debug eslint.config.mjs` comes out without any errors. 
I only get this error from the extension, but can't understand why, because it worked before I migrated the eslint-config to flat.
I have enabled the Extension to use `pre-release` to make sure that there is no fix in that one.

ESLint config:
```
import { dirname } from 'path';
import { fileURLToPath } from 'url';
import { FlatCompat } from '@eslint/eslintrc';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

const compat = new FlatCompat({
	baseDirectory: __dirname,
});

const eslintConfig = [
	...compat.config({
		extends: ['next/core-web-vitals', 'next/typescript', 'prettier'],
	}),
];

export default eslintConfig;
```

package.json:
```
{
	"name": "my-app",
	"version": "0.1.0",
	"private": true,
	"scripts": {
		"preinstall": "npx only-allow pnpm",
		"dev": "next dev",
		"build": "next build",
		"start": "next start",
		"lint": "next lint"
	},
	"dependencies": {
		"@internationalized/date": "3.6.0",
		"@nextui-org/react": "^2.6.8",
		"@tanstack/react-query": "^5.62.7",
		"@tanstack/react-query-devtools": "^5.62.7",
		"@iconify/react": "^5.1.0",
		"clsx": "^2.1.1",
		"framer-motion": "11.14.4",
		"lenis": "^1.1.18",
		"mini-svg-data-uri": "^1.4.4",
		"next": "15.1.0",
		"next-themes": "^0.4.4",
		"postcss": "8.4.49",
		"react": "19.0.0",
		"react-dom": "19.0.0",
		"sonner": "^1.7.1",
		"tailwind-merge": "^2.5.5",
		"usehooks-ts": "^3.1.0",
		"zod": "^3.24.1"
	},
	"devDependencies": {
		"@eslint/eslintrc": "3.2.0",
		"@next/bundle-analyzer": "15.1.0",
		"@tanstack/eslint-plugin-query": "^5.62.1",
		"@types/node": "22.10.2",
		"@types/react": "19.0.1",
		"@types/react-dom": "19.0.2",
		"autoprefixer": "10.4.20",
		"cross-env": "^7.0.3",
		"eslint": "9.17.0",
		"eslint-config-next": "15.1.0",
		"eslint-config-prettier": "^9.1.0",
		"prettier": "3.4.2",
		"prettier-plugin-tailwindcss": "^0.6.9",
		"tailwind-variants": "^0.3.0",
		"tailwindcss": "3.4.16",
		"typescript": "5.7.2"
	},
	"overrides": {
		"@types/react": "19.0.1",
		"@types/react-dom": "19.0.2"
	}
}
```

**Comment by J4v4Scr1pt** [comment]
The problem is that I need to have an `.npmrc `file with this line of code:
`public-hoist-pattern[]=*@nextui-org/*`

**Comment by J4v4Scr1pt** [comment]
Will close the issue because this is a pnpm issue which was solved by help on the pnpm github. https://github.com/pnpm/pnpm/issues/8878
