### ISSUE TITLE
Error bar showing "Cannot read property 'value' of null"

### ISSUE THREAD

**Issue by moberemk** [Microsoft/vscode-eslint#212]
Right now any lint operation using plugin version 1.2.7 with local eslint 3.17.0 fails on one of my files specifically by showing the error message "Cannot read property 'value' of null". Looking at the console it's registered as an error but the stack trace doesn't call out specifically this plugin; I determined it was likely to be the culprit based on disabling extensions until the error stopped appearing.

Below is the Flow-annotated code that's affected; notably this hasn't yet been reproducible on any other similar files.

```js
// @flow
const { Map, Set } = require('immutable');

module.exports = function ModelToDatabaseObject(original: Object, constructor: (Object) => Object, allowedKeys: ?Set<string> = null): Object {
  let m = Map(constructor(original));
  if (allowedKeys instanceof Set) {
    m = m.filter((v: any, k: string) => allowedKeys.has(k));
  }

  return m.filterNot((v: any) => v === undefined).toJS();
};
```

**Comment by dbaeumer** [comment]
@moberemk can you share a project which I could clone. Makes it a lot easier to track down.

And do you see any exception when linting from the shell?

**Comment by moberemk** [comment]
Good call on linting from the shell, didn't think to do that for some reason. The output looks like this, seems like a bug in `eslint-plugin-flowtype` to do with the type for the `constructor` parameter being a callable:

```
Cannot read property 'value' of null
TypeError: Cannot read property 'value' of null
    at /Users/moberemk/neutun/richmond-rest/node_modules/eslint-plugin-flowtype/dist/rules/typeColonSpacing/reporter.js:36:14
    at /Users/moberemk/neutun/richmond-rest/node_modules/eslint-plugin-flowtype/dist/rules/typeColonSpacing/evaluateTypical.js:30:7
    at arrayEach (/Users/moberemk/neutun/richmond-rest/node_modules/lodash/lodash.js:537:11)
    at Function.forEach (/Users/moberemk/neutun/richmond-rest/node_modules/lodash/lodash.js:9344:14)
    at EventEmitter.<anonymous> (/Users/moberemk/neutun/richmond-rest/node_modules/eslint-plugin-flowtype/dist/rules/typeColonSpacing/evaluateFunctions.js:28:22)
    at emitOne (events.js:101:20)
    at EventEmitter.emit (events.js:188:7)
    at NodeEventGenerator.enterNode (/Users/moberemk/neutun/richmond-rest/node_modules/eslint/lib/util/node-event-generator.js:39:22)
    at CodePathAnalyzer.enterNode (/Users/moberemk/neutun/richmond-rest/node_modules/eslint/lib/code-path-analysis/code-path-analyzer.js:607:23)
    at CommentEventGenerator.enterNode (/Users/moberemk/neutun/richmond-rest/node_modules/eslint/lib/util/comment-event-generator.js:98:23)
    at Controller.enter (/Users/moberemk/neutun/richmond-rest/node_modules/eslint/lib/eslint.js:928:36)
```

I'll have to throw an issue up on that repo then. That said, is there any way to make eslint errors more obvious to the user? There was nothing in the error message to clarify where the error arose.

**Comment by dbaeumer** [comment]
They should show up in the ESLint channel in the output panel. Can you try to reproduce and look if it shows up there?

**Comment by dbaeumer** [comment]
This issue has been closed because it needs more information and has not had recent activity. Thank you for your contributions.
