### ISSUE TITLE
(Insiders/1.2.10) "Cannot read property 'then' of undefined"

### ISSUE THREAD

**Issue by ankon** [Microsoft/vscode-eslint#240]
~~~~
[Info  - 1:47:07 PM] ESLint server is running.
/home/andreas/.vscode-insiders/extensions/dbaeumer.vscode-eslint-1.2.10/server/server.js:613
    return document2Library[document.uri].then((library) => {
                                         ^

TypeError: Cannot read property 'then' of undefined
    at validateSingle (/home/andreas/.vscode-insiders/extensions/dbaeumer.vscode-eslint-1.2.10/server/server.js:613:42)
    at Object.messageQueue.onNotification [as handler] (/home/andreas/.vscode-insiders/extensions/dbaeumer.vscode-eslint-1.2.10/server/server.js:308:5)
    at BufferedMessageQueue.processQueue (/home/andreas/.vscode-insiders/extensions/dbaeumer.vscode-eslint-1.2.10/server/server.js:297:18)
    at Immediate.timer.setImmediate (/home/andreas/.vscode-insiders/extensions/dbaeumer.vscode-eslint-1.2.10/server/server.js:260:18)
    at runCallback (timers.js:651:20)
    at tryOnImmediate (timers.js:624:5)
    at processImmediate [as _immediateCallback] (timers.js:596:5)
[Error - 1:47:07 PM] Connection to server got closed. Server will not be restarted.
[Info  - 1:47:07 PM] ESLint server stopped.
~~~~

Only thing I can remember is that I did update VSCode and the extension, and then did my usual "work on projects".

**Comment by ankon** [comment]
Some more thinking/playing: This happened in a project where `npm install` hadn't been executed; I did that now and the extension seems to be slightly happier...
~~~~
[Warn  - 1:50:16 PM] 
No ESLint configuration (e.g .eslintrc) found for file: index.js
File will not be validated. Consider running the 'Create .eslintrc.json file' command.
Alternatively you can disable ESLint for this workspace by executing the 'Disable ESLint for this workspace' command.
~~~~

**Comment by oliversalzburg** [comment]
Sadly, installing all dependencies only temporarily resolved the issue for me. Now the server keeps crashing again.

**Comment by dbaeumer** [comment]
This is a bug I introduced in 1.2.10. Will work on a fix.

**Comment by svipben** [comment]
Same here, this is the output:

```
[Info  - 5:39:05 PM] ESLint server is running.
/home/svipben/.vscode/extensions/dbaeumer.vscode-eslint-1.2.10/server/server.js:613
    return document2Library[document.uri].then((library) => {
                                         ^

TypeError: Cannot read property 'then' of undefined
    at validateSingle (/home/svipben/.vscode/extensions/dbaeumer.vscode-eslint-1.2.10/server/server.js:613:42)
    at Object.messageQueue.onNotification [as handler] (/home/svipben/.vscode/extensions/dbaeumer.vscode-eslint-1.2.10/server/server.js:308:5)
    at BufferedMessageQueue.processQueue (/home/svipben/.vscode/extensions/dbaeumer.vscode-eslint-1.2.10/server/server.js:297:18)
    at Immediate.timer.setImmediate (/home/svipben/.vscode/extensions/dbaeumer.vscode-eslint-1.2.10/server/server.js:260:18)
    at runCallback (timers.js:651:20)
    at tryOnImmediate (timers.js:624:5)
    at processImmediate [as _immediateCallback] (timers.js:596:5)
[Info  - 5:39:05 PM] Connection to server got closed. Server will restart.
[Info  - 5:39:05 PM] ESLint server stopped.
[Info  - 5:39:06 PM] ESLint server is running.
/home/svipben/.vscode/extensions/dbaeumer.vscode-eslint-1.2.10/server/server.js:613
    return document2Library[document.uri].then((library) => {
                                         ^

TypeError: Cannot read property 'then' of undefined
    at validateSingle (/home/svipben/.vscode/extensions/dbaeumer.vscode-eslint-1.2.10/server/server.js:613:42)
    at Object.messageQueue.onNotification [as handler] (/home/svipben/.vscode/extensions/dbaeumer.vscode-eslint-1.2.10/server/server.js:308:5)
    at BufferedMessageQueue.processQueue (/home/svipben/.vscode/extensions/dbaeumer.vscode-eslint-1.2.10/server/server.js:297:18)
    at Immediate.timer.setImmediate (/home/svipben/.vscode/extensions/dbaeumer.vscode-eslint-1.2.10/server/server.js:260:18)
    at runCallback (timers.js:651:20)
    at tryOnImmediate (timers.js:624:5)
    at processImmediate [as _immediateCallback] (timers.js:596:5)
[Info  - 5:39:06 PM] Connection to server got closed. Server will restart.
[Info  - 5:39:06 PM] ESLint server stopped.
[Info  - 5:39:07 PM] ESLint server is running.
/home/svipben/.vscode/extensions/dbaeumer.vscode-eslint-1.2.10/server/server.js:613
    return document2Library[document.uri].then((library) => {
                                         ^

TypeError: Cannot read property 'then' of undefined
    at validateSingle (/home/svipben/.vscode/extensions/dbaeumer.vscode-eslint-1.2.10/server/server.js:613:42)
    at Object.messageQueue.onNotification [as handler] (/home/svipben/.vscode/extensions/dbaeumer.vscode-eslint-1.2.10/server/server.js:308:5)
    at BufferedMessageQueue.processQueue (/home/svipben/.vscode/extensions/dbaeumer.vscode-eslint-1.2.10/server/server.js:297:18)
    at Immediate.timer.setImmediate (/home/svipben/.vscode/extensions/dbaeumer.vscode-eslint-1.2.10/server/server.js:260:18)
    at runCallback (timers.js:651:20)
    at tryOnImmediate (timers.js:624:5)
    at processImmediate [as _immediateCallback] (timers.js:596:5)
[Info  - 5:39:07 PM] Connection to server got closed. Server will restart.
[Info  - 5:39:07 PM] ESLint server stopped.
[Info  - 5:39:08 PM] ESLint server is running.
/home/svipben/.vscode/extensions/dbaeumer.vscode-eslint-1.2.10/server/server.js:613
    return document2Library[document.uri].then((library) => {
                                         ^

TypeError: Cannot read property 'then' of undefined
    at validateSingle (/home/svipben/.vscode/extensions/dbaeumer.vscode-eslint-1.2.10/server/server.js:613:42)
    at Object.messageQueue.onNotification [as handler] (/home/svipben/.vscode/extensions/dbaeumer.vscode-eslint-1.2.10/server/server.js:308:5)
    at BufferedMessageQueue.processQueue (/home/svipben/.vscode/extensions/dbaeumer.vscode-eslint-1.2.10/server/server.js:297:18)
    at Immediate.timer.setImmediate (/home/svipben/.vscode/extensions/dbaeumer.vscode-eslint-1.2.10/server/server.js:260:18)
    at runCallback (timers.js:651:20)
    at tryOnImmediate (timers.js:624:5)
    at processImmediate [as _immediateCallback] (timers.js:596:5)
[Info  - 5:39:08 PM] Connection to server got closed. Server will restart.
[Info  - 5:39:08 PM] ESLint server stopped.
[Info  - 5:39:09 PM] ESLint server is running.
/home/svipben/.vscode/extensions/dbaeumer.vscode-eslint-1.2.10/server/server.js:613
    return document2Library[document.uri].then((library) => {
                                         ^

TypeError: Cannot read property 'then' of undefined
    at validateSingle (/home/svipben/.vscode/extensions/dbaeumer.vscode-eslint-1.2.10/server/server.js:613:42)
    at Object.messageQueue.onNotification [as handler] (/home/svipben/.vscode/extensions/dbaeumer.vscode-eslint-1.2.10/server/server.js:308:5)
    at BufferedMessageQueue.processQueue (/home/svipben/.vscode/extensions/dbaeumer.vscode-eslint-1.2.10/server/server.js:297:18)
    at Immediate.timer.setImmediate (/home/svipben/.vscode/extensions/dbaeumer.vscode-eslint-1.2.10/server/server.js:260:18)
    at runCallback (timers.js:651:20)
    at tryOnImmediate (timers.js:624:5)
    at processImmediate [as _immediateCallback] (timers.js:596:5)
[Error - 5:39:09 PM] Connection to server got closed. Server will not be restarted.
[Info  - 5:39:09 PM] ESLint server stopped.

```

**Comment by dbaeumer** [comment]
Sorry for this. I optimized performance be reordering some notifications and request and not tried to validate closed documents. Published 1.2.11 which should fix the problem.

**Comment by oliversalzburg** [comment]
Seems to work like a charm. Thanks for the quick fix :)

**Comment by scottsauber** [comment]
@dbaeumer - thanks for the quick fix!

**Comment by guppie70** [comment]
Indeed - update works perfectly! Many thanks for your support!

**Comment by kurtnovack** [comment]
I ran into this issue today and had the latest version. If anyone else sees this, uninstalling/reinstalling fixed it.
