### ISSUE TITLE
Error show wrong path

### ISSUE THREAD

**Issue by eromoe** [Microsoft/vscode-eslint#289]
Hi , I don't know why it take wrong path `node_modules\redux-saga`,  

```
Cannot find module 'e:\Project\allproject_git\annotator-v2\node_modules\redux-saga\internals\webpack\webpack.prod.babel.js'
```
![image](https://user-images.githubusercontent.com/3938751/29851231-8a806798-8d65-11e7-842a-abaf3ec9daf8.png)

`webpack.prod.babel.js`  is in  `e:\Project\allproject_git\annotator-v2\internals\webpack\webpack.prod.babel.js`

Config is :

```
  "eslintConfig": {
    "parser": "babel-eslint",
    "extends" : [
      "eslint:recommended",
      "plugin:import/errors"
    ],
    "env": {
      "browser": true,
      "node": true,
      "jest": true,
      "es6": true
    },
    "plugins": [
      "redux-saga",
      "react",
      "jsx-a11y"
    ],
    "parserOptions": {
      "ecmaVersion": 6,
      "sourceType": "module",
      "ecmaFeatures": {
        "jsx": true
      }
    },
    "rules": {
      "class-methods-use-this": 0,
      "no-unused-vars": 0,
      "import/imports-first": 0,
      "import/newline-after-import": 0,
      "import/no-dynamic-require": 0,
      "import/no-extraneous-dependencies": 0,
      "import/no-named-as-default": 0,
      "import/no-unresolved": 2,
      "import/no-webpack-loader-syntax": 0,
      "import/prefer-default-export": 0,
      "jsx-a11y/aria-props": 2,
      "jsx-a11y/heading-has-content": 0,
      "jsx-a11y/href-no-hash": 2,
      "jsx-a11y/label-has-for": 2,
      "jsx-a11y/mouse-events-have-key-events": 2,
      "jsx-a11y/role-has-required-aria-props": 2,
      "jsx-a11y/role-supports-aria-props": 2,
      "indent": [
        2,
        2,
        {
          "SwitchCase": 1
        }
      ],
      "max-len": 0,
      "newline-per-chained-call": 0,
      "no-confusing-arrow": 0,
      "no-console": 1,
      "no-use-before-define": 0,
      "prefer-template": 2,
      "react/forbid-prop-types": 0,
      "react/jsx-filename-extension": 0,
      "react/jsx-no-target-blank": 0,
      "react/require-default-props": 0,
      "react/require-extension": 0,
      "react/self-closing-comp": 0,
      "redux-saga/no-yield-in-race": 2,
      "redux-saga/yield-effects": 2,
      "require-yield": 0
    },
    "settings": {
      "import/resolver": {
        "webpack": {
          "config": "./internals/webpack/webpack.prod.babel.js"
        }
      }
    }
  },
```

**Comment by dbaeumer** [comment]
@eromoe what happens if you try to run ESLint from a terminal (e.g. bash, cmd.exe or PowerShell)

**Comment by eromoe** [comment]
```

> react-boilerplate@3.4.0 lint E:\Project\allproject_git\annotator-v2
> npm run lint:js


> react-boilerplate@3.4.0 lint:js E:\Project\allproject_git\annotator-v2
> npm run lint:eslint -- .


> react-boilerplate@3.4.0 lint:eslint E:\Project\allproject_git\annotator-v2
> eslint --ignore-path .gitignore --ignore-pattern internals/scripts "."

Cannot find module 'E:\Project\allproject_git\annotator-v2\node_modules\redux-sa
ga\internals\webpack\webpack.prod.babel.js'
Error: Cannot find module 'E:\Project\allproject_git\annotator-v2\node_modules\r
edux-saga\internals\webpack\webpack.prod.babel.js'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.exports.resolve (E:\Project\allproject_git\annotator-v2\node_modul
es\eslint-import-resolver-webpack\index.js:68:25)
    at v2 (E:\Project\allproject_git\annotator-v2\node_modules\eslint-module-uti
ls\resolve.js:79:23)
    at withResolver (E:\Project\allproject_git\annotator-v2\node_modules\eslint-
module-utils\resolve.js:84:16)
    at fullResolve (E:\Project\allproject_git\annotator-v2\node_modules\eslint-m
odule-utils\resolve.js:101:22)
    at Function.relative (E:\Project\allproject_git\annotator-v2\node_modules\es
lint-module-utils\resolve.js:46:10)
    at remotePath (E:\Project\allproject_git\annotator-v2\node_modules\eslint-pl
ugin-import\lib\ExportMap.js:348:20)
    at resolveImport (E:\Project\allproject_git\annotator-v2\node_modules\eslint
-plugin-import\lib\ExportMap.js:352:16)
    at Object.getImport (E:\Project\allproject_git\annotator-v2\node_modules\esl
int-plugin-import\lib\ExportMap.js:445:68)
    at ExportMap.get (E:\Project\allproject_git\annotator-v2\node_modules\eslint
-plugin-import\lib\ExportMap.js:115:34)
    at processBodyStatement (E:\Project\allproject_git\annotator-v2\node_modules
\eslint-plugin-import\lib\rules\rules\namespace.js:67:38)
    at Array.forEach (native)
    at EventEmitter.Program (E:\Project\allproject_git\annotator-v2\node_modules
\eslint-plugin-import\lib\rules\rules\namespace.js:77:14)

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "D:\\nodejs\\node.exe" "D:\\nodejs\\node_modules\\npm\\bin\\npm-cl
i.js" "run" "lint:eslint" "--" "."
npm ERR! node v6.9.5
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! react-boilerplate@3.4.0 lint:eslint: `eslint --ignore-path .gitignore -
-ignore-pattern internals/scripts "."`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the react-boilerplate@3.4.0 lint:eslint script 'eslint --igno
re-path .gitignore --ignore-pattern internals/scripts "."'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the react-boilerplate pac
kage,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     eslint --ignore-path .gitignore --ignore-pattern internals/scripts
"."
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs react-boilerplate
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls react-boilerplate
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     E:\Project\allproject_git\annotator-v2\npm-debug.log

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "D:\\nodejs\\node.exe" "D:\\nodejs\\node_modules\\npm\\bin\\npm-cl
i.js" "run" "lint:js"
npm ERR! node v6.9.5
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! react-boilerplate@3.4.0 lint:js: `npm run lint:eslint -- . `
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the react-boilerplate@3.4.0 lint:js script 'npm run lint:esli
nt -- . '.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the react-boilerplate pac
kage,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run lint:eslint -- .
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs react-boilerplate
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls react-boilerplate
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     E:\Project\allproject_git\annotator-v2\npm-debug.log

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "D:\\nodejs\\node.exe" "D:\\nodejs\\node_modules\\npm\\bin\\npm-cl
i.js" "run" "lint"
npm ERR! node v6.9.5
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! react-boilerplate@3.4.0 lint: `npm run lint:js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the react-boilerplate@3.4.0 lint script 'npm run lint:js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the react-boilerplate pac
kage,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run lint:js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs react-boilerplate
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls react-boilerplate
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     E:\Project\allproject_git\annotator-v2\npm-debug.log
```

**Comment by dbaeumer** [comment]
OK. I will close the issue then since there is nothing the ESLint extension can do here.
