### ISSUE TITLE
Error: Header must provide a Content-Length property

### ISSUE THREAD

**Issue by ALF-er** [Microsoft/vscode-eslint#3]
Hello, thank you for this great extension.

I began to receive error (in DevTools of vscode):
```
Error: Header must provide a Content-Length property.: Error: Header must provide a Content-Length property.
    at MessageReader.onData (C:\Users\elfer\.vscode\extensions\dbaeumer.vscode-eslint\node_modules\vscode-languageclient\node_modules\vscode-jsonrpc\lib\messageReader.js:105:27)
    at Socket.<anonymous> (C:\Users\elfer\.vscode\extensions\dbaeumer.vscode-eslint\node_modules\vscode-languageclient\node_modules\vscode-jsonrpc\lib\messageReader.js:92:19)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:146:16)
    at Socket.Readable.push (_stream_readable.js:110:10)
    at Pipe.onread (net.js:523:20)
```
First it works perfectly on my codebase. But at some moment (I didn't change eslint version or vscode version or extension (explicitly)) that error just appear and it is stable. I'm playing with eslint rules in .eslintrc. 

If you need any additional info - let me know.

PS: sorry for my English

**Comment by dbaeumer** [comment]
@ALF-er  this should not happen :-). Any steps to reproduce would be highly appreciated

**Comment by ALF-er** [comment]
Sorry for delay. Here is settings and code (just 2 lines of code) that lead to subj issue https://github.com/ALF-er/vscode-eslint-test But it's obvious that it's not eslint-settings-issue. I want to reinstall vscode from scratch. But maybe I can provide some extended issue report for you before that?

**Comment by jwulf** [comment]
I have the same error:

```
Error: Header must provide a Content-Length property.
    at MessageReader.onData (/Users/sitapati/.vscode/extensions/dbaeumer.vscode-eslint/node_modules/vscode-languageclient/node_modules/vscode-jsonrpc/lib/messageReader.js:105:27)
    at Socket.<anonymous> (/Users/sitapati/.vscode/extensions/dbaeumer.vscode-eslint/node_modules/vscode-languageclient/node_modules/vscode-jsonrpc/lib/messageReader.js:92:19)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:146:16)
    at Socket.Readable.push (_stream_readable.js:110:10)
    at Pipe.onread (net.js:523:20)
```

**Comment by ALF-er** [comment]
So full reinstall of VSCode, vscode-eslint,local eslint doesn't fix problem =| Any ideas, someone?

**Comment by dbaeumer** [comment]
@ALF-er the problem comes from the fact the something interferes with the protocol socket we use. It will not go away by installing fresh

**Comment by ALF-er** [comment]
@dbaeumer Good to know that the source of problem defined (approximately =)). If you need any additional information - let me know, I'll be glad to help.

**Comment by dbaeumer** [comment]
I fixed it by allowing both stdio and node ipc as a transport. For eslint I change now to ipc transport which makes it impossible that a console.log interferes with the protocol. I publish a new version of eslint as well.

**Comment by ALF-er** [comment]
Great! But after update I get
```
EPERM: operation not permitted, write
e.doShow @ workbench.main.js:1598
e.show @ workbench.main.js:1598
e.showMessage @ workbench.main.js:1590
__dirname.undefined.t.Class.derive._oncancel @ workbench.main.js:1544
e.showMessage @ workbench.main.js:1590
e.handle @ workbench.main.js:1588
a @ workbench.main.js:1576
h.handle @ workbench.main.js:1576
(anonymous function) @ workbench.main.js:1602
(anonymous function) @ workbench.main.js:1602
emitTwo @ events.js:87
emit @ events.js:172
handleMessage @ internal/child_process.js:685
channel.onread @ internal/child_process.js:440
```
