### ISSUE TITLE
Activating extension `dbaeumer.vscode-eslint` failed

### ISSUE THREAD

**Issue by maksimkurb** [Microsoft/vscode-eslint#331]
You have published version `1.4.1` just an hour ago and when I updated, plugin stopped working.
![2017-11-01 17-27-32](https://user-images.githubusercontent.com/1351924/32279585-37c6e076-bf2a-11e7-98d2-a10de543f4d4.png)

It looks like that plugin is failed to build before publishing to VS Marketplace

```
[Extension Host] Ошибка активации расширения "dbaeumer.vscode-eslint": Cannot find module '/home/maksimkurb/.vscode-insiders/extensions/dbaeumer.vscode-eslint-1.4.1/client/out/extension'. (at Object.showMessage (/usr/share/code-insiders/resources/app/out/vs/workbench/node/extensionHostProcess.js:4:502720))
/usr/share/code-insiders/resources/app/out/vs/workbench/workbench.main.js:9 [Extension Host] Activating extension `dbaeumer.vscode-eslint` failed:  Cannot find module '/home/maksimkurb/.vscode-insiders/extensions/dbaeumer.vscode-eslint-1.4.1/client/out/extension' (at /usr/share/code-insiders/resources/app/out/vs/workbench/node/extensionHostProcess.js:4:288724)
/usr/share/code-insiders/resources/app/out/vs/workbench/workbench.main.js:9 [Extension Host] Here is the error stack:  Error: Cannot find module '/home/maksimkurb/.vscode-insiders/extensions/dbaeumer.vscode-eslint-1.4.1/client/out/extension'
	at Function.Module._resolveFilename (module.js:470:15)
	at Function.Module._load (module.js:418:25)
	at Function.J.o._load (/usr/share/code-insiders/resources/app/out/vs/workbench/node/extensionHostProcess.js:4:484491)
	at Module.require (module.js:498:17)
	at require (internal/module.js:20:19)
	at Function.d [as __$__nodeRequire] (/usr/share/code-insiders/resources/app/out/vs/loader.js:4:27801)
	at g (/usr/share/code-insiders/resources/app/out/vs/workbench/node/extensionHostProcess.js:4:499934)
	at e._doActivateExtension (/usr/share/code-insiders/resources/app/out/vs/workbench/node/extensionHostProcess.js:4:505198)
	at e._activateExtension (/usr/share/code-insiders/resources/app/out/vs/workbench/node/extensionHostProcess.js:4:504674)
	at Object.actualActivateExtension (/usr/share/code-insiders/resources/app/out/vs/workbench/node/extensionHostProcess.js:4:502852) (at /usr/share/code-insiders/resources/app/out/vs/workbench/node/extensionHostProcess.js:4:288792)
/usr/share/code-insiders/resources/app/out/vs/workbench/workbench.main.js:9 Ошибка активации расширения "dbaeumer.vscode-eslint": Cannot find module '/home/maksimkurb/.vscode-insiders/extensions/dbaeumer.vscode-eslint-1.4.1/client/out/extension'.
```

**Comment by maksimkurb** [comment]
Duplicate of #330
