### ISSUE TITLE
ESlint server keeps crashing on VSCode 1.18

### ISSUE THREAD

**Issue by initram** [Microsoft/vscode-eslint#342]
Just upgraded to version 1.18 of VsCode and I get the following error from the ESLint plugin:

```
module.js:472
    throw err;
    ^

Error: Cannot find module 'C:\Users\mmi\.vscode\extensions\dbaeumer.vscode-eslint-1.4.3\server\out\server.js'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Server.<anonymous> (C:\Users\mmi\.vscode\extensions\dbaeumer.vscode-eslint-1.4.3\client\node_modules\vscode-languageclient\lib\utils\electronForkStart.js:110:9)
    at emitOne (events.js:96:13)
    at Server.emit (events.js:191:7)
    at Pipe.onconnection (net.js:1486:8)
[Error - 10:30:32] Connection to server got closed. Server will not be restarted.
```

**Comment by dbaeumer** [comment]
This works for me.  I guess somehow the eslint extension installation is broken. Can you uninstall and reinstall it and see if this fixes the problem?

**Comment by initram** [comment]
That solved it... weird.
