### ISSUE TITLE
Unexpected Identifier

### ISSUE THREAD

**Issue by chantlong** [Microsoft/vscode-eslint#368]
I am using eslint extension along with prettier for vscode.

In my react components, when I type a function name, as I'm typing, the error image from the 2nd screenshot constantly pops up. So for _n_ letters I type, the popup shows up _n_ times.

```
handleChange() {}
```
Does not happen if all functions are written like the above.

```
handleChange = () => {}
```
Error constantly pops up if I have functions written in this format. (but I want to write it in this format)

<img width="641" alt="screen shot 2017-12-18 at 4 37 52 pm" src="https://user-images.githubusercontent.com/17346712/34094779-07f2d6b8-e412-11e7-8ed5-8f5ff4791d69.png">
<img width="911" alt="screen shot 2017-12-18 at 4 38 02 pm" src="https://user-images.githubusercontent.com/17346712/34094780-0825d194-e412-11e7-98ef-7594102cf04d.png">

My eslintrc file setup like the following
```
{
  "extends": [
    "standard",
    "plugin:flowtype/recommended",
    "plugin:react/recommended",
    "prettier",
    "prettier/flowtype",
    "prettier/react",
    "prettier/standard"
  ],
  "plugins": [
    "flowtype",
    "react",
    "prettier",
    "standard"
  ],
  "parserOptions": {
    "sourceType": "module",
    "ecmaFeatures": {
      "jsx": true
    }
  },
  "env": {
    "es6": true,
    "node": true
  },
  "rules": {
    "prettier/prettier": "error"
  }
}
```

Any idea what could be wrong?

Thanks

**Comment by dbaeumer** [comment]
What happens if you execute the eslint command directly in the terminal. This error looks more like an exception in ESLint npm module then a linting diagnostics.

If everything works fine in the terminal can you please provide me with a GitHub repository that demos the behavior with steps on how to reproduce.

**Comment by chantlong** [comment]
@dbaeumer  Thanks for getting back. So I tried running eslint in terminal directly on the js file and there are no errors. The error only pops up in vscode when I type a function like `toggle...`

I'll get back to you when I have the GitHub repo ready.

**Comment by chantlong** [comment]
@dbaeumer Here's the link the repo. In the index.js file, there's a comment on L12. Try typing a function name there and vscode pops those errors out. (at least in my workspace)
https://github.com/chantlong/test-eslint-prettier-standard

**Comment by dbaeumer** [comment]
I tries to running eslint from the command line and here is what I get:

```
Unexpected identifier (15:3)
  13 |   too
  14 |
> 15 |   handleChange = (e: SyntheticEvent<HTMLInputElement>) => {
     |   ^^^^^^^^^^^^
  16 |     this.setState({ [e.currentTarget.value]: e.currentTarget.value })
  17 |   }
  18 |   render() {
SyntaxError: Unexpected identifier (15:3)
  13 |   too
  14 |
> 15 |   handleChange = (e: SyntheticEvent<HTMLInputElement>) => {
     |   ^^^^^^^^^^^^
  16 |     this.setState({ [e.currentTarget.value]: e.currentTarget.value })
  17 |   }
  18 |   render() {
    at createError$1 (P:\mseng\VSCode\Playgrounds\bugs\eslint\test-eslint-prettier-standard\node_modules\prettier\parser-flow.js:1:183)
    at parse (P:\mseng\VSCode\Playgrounds\bugs\eslint\test-eslint-prettier-standard\node_modules\prettier\parser-flow.js:1:902)
    at Object.parse$1 [as parse] (P:\mseng\VSCode\Playgrounds\bugs\eslint\test-eslint-prettier-standard\node_modules\prettier\index.js:5837:12)
    at formatWithCursor (P:\mseng\VSCode\Playgrounds\bugs\eslint\test-eslint-prettier-standard\node_modules\prettier\index.js:27654:22)
    at format (P:\mseng\VSCode\Playgrounds\bugs\eslint\test-eslint-prettier-standard\node_modules\prettier\index.js:27697:10)
    at Object.format (P:\mseng\VSCode\Playgrounds\bugs\eslint\test-eslint-prettier-standard\node_modules\prettier\index.js:27936:12)
    at Program (P:\mseng\VSCode\Playgrounds\bugs\eslint\test-eslint-prettier-standard\node_modules\eslint-plugin-prettier\eslint-plugin-prettier.js:374:45)
    at listeners.(anonymous function).forEach.listener (P:\mseng\VSCode\Playgrounds\bugs\eslint\test-eslint-prettier-standard\node_modules\eslint\lib\util\safe-emitter.js:47:58)
    at Array.forEach (<anonymous>)
    at Object.emit (P:\mseng\VSCode\Playgrounds\bugs\eslint\test-eslint-prettier-standard\node_modules\eslint\lib\util\safe-emitter.js:47:38)
    at NodeEventGenerator.applySelector (P:\mseng\VSCode\Playgrounds\bugs\eslint\test-eslint-prettier-standard\node_modules\eslint\lib\util\node-event-generator.js:251:26)
    at NodeEventGenerator.applySelectors (P:\mseng\VSCode\Playgrounds\bugs\eslint\test-eslint-prettier-standard\node_modules\eslint\lib\util\node-event-generator.js:280:22)
    at NodeEventGenerator.enterNode (P:\mseng\VSCode\Playgrounds\bugs\eslint\test-eslint-prettier-standard\node_modules\eslint\lib\util\node-event-generator.js:294:14)
    at CodePathAnalyzer.enterNode (P:\mseng\VSCode\Playgrounds\bugs\eslint\test-eslint-prettier-standard\node_modules\eslint\lib\code-path-analysis\code-path-analyzer.js:608:23)
    at Traverser.enter (P:\mseng\VSCode\Playgrounds\bugs\eslint\test-eslint-prettier-standard\node_modules\eslint\lib\linter.js:956:32)
    at Traverser.__execute (P:\mseng\VSCode\Playgrounds\bugs\eslint\test-eslint-prettier-standard\node_modules\estraverse\estraverse.js:397:31)
```

You need to put `too` in the file where you indicated and then run eslint from the terminal (e.g. `.\node_modules\.bin\eslint index.js`. This looks like a ESLint problem to me. Can you please report it there.

**Comment by chantlong** [comment]
@dbaeumer 

Right now I can get by it by adding the `"eslint.run": "onSave"` option so vscode does not throw the popup notification out as I'm typing the function name. All my eslint errors appear in the Problems status bar but this error is the only situation where I get popup notifications. Is there anyway at the moment to disable vscode from popping out eslint error notifications on the top screen?

**Comment by dbaeumer** [comment]
No there is currently no way to prevent this pop up.

**Comment by sambigelow44** [comment]
I am having an issue with this as well. I would love it if I could just turn off notifications from vscode-eslint. Is there any way to do that? I still want the squiggly lines, just not the popup notifications.
