### ISSUE TITLE
TypeError: Cannot read property 'language' of undefined

### ISSUE THREAD

**Issue by liyi8576** [Microsoft/vscode-eslint#442]
When I execute with eslint command, I can run normally
```
./node_modules/.bin/eslint XXX.jsx
```
I use the atom editor, eslint can also run the right

But when I use eslint plug-in, the console is wrong, the error message is as follows:
```
[Info  - 4:47:34 PM] ESLint server is running.
[Info  - 4:47:36 PM] ESLint library loaded from: /Users/liyi/Workspace/ws_ai_mdp/ai-mdp-web/node_modules/eslint/lib/api.js
[Error - 4:47:36 PM] ESLint stack trace:
[Error - 4:47:36 PM] TypeError: Cannot read property 'language' of undefined
    at Object.keys.forEach.key (/Users/liyi/Workspace/ws_ai_mdp/ai-mdp-web/node_modules/eslint/lib/config/config-ops.js:180:75)
    at Array.forEach (native)
    at deepmerge (/Users/liyi/Workspace/ws_ai_mdp/ai-mdp-web/node_modules/eslint/lib/config/config-ops.js:177:30)
    at Object.keys.forEach (/Users/liyi/Workspace/ws_ai_mdp/ai-mdp-web/node_modules/eslint/lib/config/config-ops.js:159:34)
    at Array.forEach (native)
    at deepmerge (/Users/liyi/Workspace/ws_ai_mdp/ai-mdp-web/node_modules/eslint/lib/config/config-ops.js:150:38)
    at Object.keys.forEach.key (/Users/liyi/Workspace/ws_ai_mdp/ai-mdp-web/node_modules/eslint/lib/config/config-ops.js:181:32)
    at Array.forEach (native)
    at Object.deepmerge [as merge] (/Users/liyi/Workspace/ws_ai_mdp/ai-mdp-web/node_modules/eslint/lib/config/config-ops.js:177:30)
    at Config.getConfig (/Users/liyi/Workspace/ws_ai_mdp/ai-mdp-web/node_modules/eslint/lib/config.js:341:28)
```

My eslint configuration file “.eslintrc.json ” is as follows:
```json
{
    "parser": "babel-eslint",
    "parserOptions": {
        "ecmaVersion": 6,
        "sourceType": "module",
        "ecmaFeatures": {
            "jsx": true,
            "impliedStrict":true
        }
    },
    "extends": [
        "eslint:recommended"
    ],
    "plugins": [
        "react"
    ],
    "env": {
        "browser": true,
        "commonjs": true,
        "es6": true
    }
}
```

The eslint plug-in version number of my vscode editor is 1.4.8
The dependencies configured in package.json are as follows：
```json
{
  "devDependencies": {
    "autoprefixer": "7.1.6",
    "babel-core": "^6.26.0",
    "babel-eslint": "^8.2.2",
    "babel-loader": "^7.1.4",
    "babel-plugin-import": "^1.6.7",
    "babel-plugin-transform-decorators-legacy": "^1.3.4",
    "babel-preset-react-app": "^3.1.1",
    "babel-runtime": "^6.26.0",
    "eslint": "^4.19.1",
    "eslint-config-airbnb": "^16.1.0",
    "eslint-plugin-html": "^4.0.2",
    "eslint-plugin-import": "^2.10.0",
    "eslint-plugin-jsx-a11y": "^6.0.3",
    "eslint-plugin-react": "^7.7.0",
   }
}
```

**Comment by dbaeumer** [comment]
@liyi8576 I am not able to reproduce this:

<img width="389" alt="capture" src="https://user-images.githubusercontent.com/1931590/38242702-be5933b8-3735-11e8-8467-282ac6e8455d.png">

Can you please provide me with a GitHUb repository I can clone that demos the problematic behaviour?

**Comment by JonWallsten** [comment]
I have the same or similar error. Attached is the console from VSCode.
![image](https://user-images.githubusercontent.com/5993909/38366567-71514356-38e0-11e8-8322-289afee11ec0.png)

**Comment by dbaeumer** [comment]
@JonWallsten this looks like a broken install to me. Could you try to uninstall ESLint and then reinstall.

**Comment by JonWallsten** [comment]
@dbaeumer Should have mention. I tried that yesterday. With a restart in between to be sure. Same result.

**Comment by dbaeumer** [comment]
@JonWallsten this is really strange. Can you double check that there is directory `vscode-languageclient` under `c:\Users\jway52\.vscode\extensions\dbaeumer.vscode-eslint-1.4.8\client\node_modules`

And can you do the following as well: disable the built-in Git extension and then try to reproduce this. To do so filter the extension viewlet for `@builtin` and then disable Git.

**Comment by JonWallsten** [comment]
Yep! They are there.
![image](https://user-images.githubusercontent.com/5993909/38481714-716d2762-3bcc-11e8-88ee-4fb005eef726.png)

**Comment by JonWallsten** [comment]
Edit: Might be a bigger issue:
> Activating extension 'dbaeumer.vscode-eslint' failed: Cannot find module 'vscode-languageclient'.
> Activating extension 'shinnn.stylelint' failed: Cannot find module 'vscode-languageclient'

**Comment by dbaeumer** [comment]
I am pretty sure that this is not special to ESLint since it fails for other extensions as well. @JonWallsten anything that you can think of is special with our machine. Which VS Code build are you using?

**Comment by JonWallsten** [comment]
I'm using the latest version. Updated a couple of days ago, if not yesterday. I tried to debug today, but I can't access all necessary files in the built-in dev tools.

**Comment by joaomoreno** [comment]
@dbaeumer Related to https://github.com/Microsoft/vscode-extension-telemetry/issues/12#issuecomment-379977047 ?

**Comment by dbaeumer** [comment]
@joaomoreno thanks for the hint. @JonWallsten are you using insider releases ?

**Comment by JonWallsten** [comment]
Sorry. I'm using the normal version. 
![image](https://user-images.githubusercontent.com/5993909/38551087-994c1b48-3cb8-11e8-8b9e-69a9bc07b374.png)

**Comment by JonWallsten** [comment]
How do I debug this thing?
Most of the files referenced doesn't exist when using CTRL+P in DevTools and the once that does exist does not break for anything related to dbaeumer.vscode-eslint. Is this thing running in some other context? Feels like I'm missing something.

```
Here is the error stack:  Error: Cannot find module 'vscode-languageclient'
	at Function.Module._resolveFilename (module.js:470:15)
	at Function.Module._load (module.js:418:25)
	at Function.o._load (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:653:398)
	at Module.require (module.js:498:17)
	at Module.patchedRequire [as require] (c:\Program Files\Microsoft VS Code\resources\app\extensions\git\node_modules\diagnostic-channel\dist\src\patchRequire.js:14:46)
	at require (internal/module.js:20:19)
	at Object.<anonymous> (C:\Users\jway52\.vscode\extensions\dbaeumer.vscode-eslint-1.4.8\client\out\extension.js:11:33)
	at Object.<anonymous> (C:\Users\jway52\.vscode\extensions\dbaeumer.vscode-eslint-1.4.8\client\out\extension.js:644:3)
	at Module._compile (module.js:571:32)
	at Object.Module._extensions..js (module.js:580:10)
	at Module.load (module.js:488:32)
	at tryModuleLoad (module.js:447:12)
	at Function.Module._load (module.js:439:3)
	at Function.o._load (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:653:398)
	at Module.require (module.js:498:17)
	at Module.patchedRequire [as require] (c:\Program Files\Microsoft VS Code\resources\app\extensions\git\node_modules\diagnostic-channel\dist\src\patchRequire.js:14:46)
	at require (internal/module.js:20:19)
	at Function.i [as __$__nodeRequire] (c:\Program Files\Microsoft VS Code\resources\app\out\vs\loader.js:30:770)
	at c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:676:131
	at t._doActivateExtension (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:676:243)
	at t._activateExtension (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:675:161)
	at Object.actualActivateExtension (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:673:282)
	at e._activateExtension (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:417:920)
	at c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:417:539
	at Array.map (native)
	at e._activateExtensions (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:417:514)
	at e.activateByEvent (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:416:14)
	at t.activateByEvent (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:673:646)
	at t.handleEagerExtensions (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:695:734)
	at c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:694:950
	at Object.g [as _notify] (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:69:572)
	at Object.enter (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:72:924)
	at n.Class.derive._oncancel._run (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:74:719)
	at n.Class.derive._oncancel._completed (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:74:160)
	at e.open (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:99:339)
	at c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:673:320
	at Object.g [as _notify] (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:69:572)
	at Object.enter (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:72:924)
	at n.Class.derive._oncancel._run (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:74:719)
	at n.Class.derive._oncancel._completed (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:74:160)
	at c (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:77:654)
	at q.then.o.(anonymous function) (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:77:868)
	at Object.g [as _notify] (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:69:572)
	at Object.enter (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:72:924)
	at n.Class.derive._oncancel._run (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:74:719)
	at n.Class.derive._oncancel._completed (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:74:160)
	at c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:103:286
	at c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:133:661
	at LOOP (fs.js:1728:14)
	at _combinedTickCallback (internal/process/next_tick.js:73:7)
	at process._tickCallback (internal/process/next_tick.js:104:9)
```

**Comment by alexandrudima** [comment]
Well, the first place I would check would be on disk. Is there a `vscode-languageclient` node module in the install location of `eslint`?

`C:\users\YOUR_USER\.vscode-insiders\extensions\dbaeumer.vscode-eslint-1.4.8\client\node_modules\vscode-languageclient`

i.e. perhaps the installation of eslint became corrupt for some reason...

**Comment by JonWallsten** [comment]
@alexandrudima Thanks for joining! Yes, be cleared that up already unfortunately. I would like to dig around with the debugger. Then problem is that when I add breakpoints to module.js it doesn't have this extension. I've made a conditional breakpoint to stop whenever it's trying to load the module 'vscode-languageclient', but it never stops. I've tried adding breakpoints to other places as well. For example where it outputs the error message. But I just hits the debugger för other error, not the one it's printing. So I'm pretty lost here.

**Comment by alexandrudima** [comment]
@JonWallsten Sorry about that, I didn't pay enough attention. I wonder if a built-in or another 3rd party extension is causing this. i.e. it is possible for any extension to *mess with* node's `require` and then not show up in the stack traces.

So, could you please:
* Have only eslint in `C:\users\YOUR_USER\.vscode-insiders\extensions\` and move all the other somewhere else temporarily
* Move all the built-in extensions somewhere else temporarily. i.e. rename `c:\Program Files\Microsoft VS Code\resources\app\extensions` to `extensions2` and make a new empty folder `extensions`.

This would make it that the only running extension is `eslint`, so we rule out any interference from other extensions...

**Comment by JonWallsten** [comment]
After the first suggestion: 
![image](https://user-images.githubusercontent.com/5993909/38657208-3fef83f6-3e1f-11e8-83d4-29fefe6159aa.png)

After the first and then second suggestion:
![image](https://user-images.githubusercontent.com/5993909/38657242-73f5037e-3e1f-11e8-9efa-354970730fd2.png)

**Comment by JonWallsten** [comment]
So, it turns out that uninstalling an extension is not actually removing it in the extension folder. So when you install again, it still the same old files. I removed eslint and stylelint and installed both again. Voila! No error! Thanks guys!

**Comment by alexandrudima** [comment]
The extension on disk is marked for deletion and is deleted at the next restart of VSCode...

@sandy081 Is there a way to avoid this. i.e. We were troubleshooting an extension installation problem, and the very first thing we tried was to reinstall the extension, but uninstall and install resulted in the same old files. Is there a way to prevent this? i.e. we could disable installing again until the old folder is deleted on disk.

**Comment by sandy081** [comment]
@alexandrudima For trouble shooting there is a developer command that will delete and install the extension `Developer: Reinstall Extension`.

In normal scenario where user tries to uninstall and install the same version of extension, we can try to delete the extension on install and if there is an issue while deleting, we can ask user to restart VS Code before installing.

**Comment by dbaeumer** [comment]
@alexandrudima thanks a lot for your help with this.

**Comment by JonWallsten** [comment]
@alexandrudima @sandy081: I did press the "Restart" button between uninstall and install. But I still had the same files left.
