### ISSUE TITLE
ESLint: Cannot read property 'value' of null. Please see the 'ESLint' output channel for details.

### ISSUE THREAD

**Issue by justinlevi** [Microsoft/vscode-eslint#456]
Referencing this issue
https://github.com/Microsoft/vscode/issues/48151

[Error - 14:15:49] ESLint stack trace:
[Error - 14:15:49] TypeError: Cannot read property 'value' of null
at Object.isOpeningBraceToken (/Users/justinwinter/Sites/d8d/front-end/node_modules/eslint/lib/ast-utils.js:354:17)
at validate (/Users/justinwinter/Sites/d8d/front-end/node_modules/eslint/lib/rules/arrow-body-style.js:127:41)
at listeners.(anonymous function).forEach.listener (/Users/justinwinter/Sites/d8d/front-end/node_modules/eslint/lib/util/safe-emitter.js:47:58)
at Array.forEach (native)
at Object.emit (/Users/justinwinter/Sites/d8d/front-end/node_modules/eslint/lib/util/safe-emitter.js:47:38)
at NodeEventGenerator.applySelector (/Users/justinwinter/Sites/d8d/front-end/node_modules/eslint/lib/util/node-event-generator.js:251:26)
at NodeEventGenerator.applySelectors (/Users/justinwinter/Sites/d8d/front-end/node_modules/eslint/lib/util/node-event-generator.js:280:22)
at NodeEventGenerator.leaveNode (/Users/justinwinter/Sites/d8d/front-end/node_modules/eslint/lib/util/node-event-generator.js:303:14)
at CodePathAnalyzer.leaveNode (/Users/justinwinter/Sites/d8d/front-end/node_modules/eslint/lib/code-path-analysis/code-path-analyzer.js:630:23)
at Traverser.leave [as _leave] (/Users/justinwinter/Sites/d8d/front-end/node_modules/eslint/lib/linter.js:869:28)
[Error - 14:15:50] ESLint stack trace:
[Error - 14:15:50] TypeError: Cannot read property 'value' of null
at Object.isOpeningBraceToken (/Users/justinwinter/Sites/d8d/front-end/node_modules/eslint/lib/ast-utils.js:354:17)
at validate (/Users/justinwinter/Sites/d8d/front-end/node_modules/eslint/lib/rules/arrow-body-style.js:127:41)
at listeners.(anonymous function).forEach.listener (/Users/justinwinter/Sites/d8d/front-end/node_modules/eslint/lib/util/safe-emitter.js:47:58)
at Array.forEach (native)
at Object.emit (/Users/justinwinter/Sites/d8d/front-end/node_modules/eslint/lib/util/safe-emitter.js:47:38)
at NodeEventGenerator.applySelector (/Users/justinwinter/Sites/d8d/front-end/node_modules/eslint/lib/util/node-event-generator.js:251:26)
at NodeEventGenerator.applySelectors (/Users/justinwinter/Sites/d8d/front-end/node_modules/eslint/lib/util/node-event-generator.js:280:22)
at NodeEventGenerator.leaveNode (/Users/justinwinter/Sites/d8d/front-end/node_modules/eslint/lib/util/node-event-generator.js:303:14)
at CodePathAnalyzer.leaveNode (/Users/justinwinter/Sites/d8d/front-end/node_modules/eslint/lib/code-path-analysis/code-path-analyzer.js:630:23)
at Traverser.leave [as _leave] (/Users/justinwinter/Sites/d8d/front-end/node_modules/eslint/lib/linter.js:869:28)

I can duplicated based on this project
https://github.com/justinlevi/Decoupled-Drupal-8-Starter-Kit/tree/master/front-end

**Comment by dbaeumer** [comment]
@justinlevi this is a problem in the ESLint npm library itself. TO verify can you run ESLint from the terminal and see if you get the same exception. If yes, please report the issue here: https://github.com/eslint/eslint

**Comment by justinlevi** [comment]
The issue seems intermittent and is no working. I'll report back here if it pops up again.
