### ISSUE TITLE
Error Notification 'ESLint: sourceCode.getCommentsBefore is not a function`

### ISSUE THREAD

**Issue by devert** [Microsoft/vscode-eslint#474]
Continually receive this error notification in VSCode
```
ESLint: sourceCode.getCommentsBefore is not a function. Please see the 'ESLint' output channel for details.
```

We have a `.eslintrc.js` configuration file
```
/* eslint-disable */
const path = require('path');

module.exports = {
  parser: 'babel-eslint',
  extends: [
    'airbnb',
  ],
  plugins: [
    'flowtype',
  ],
  env: {
    browser: true,
    jasmine: true,
    protractor: true,
    node: true,
    jest: true,
  },
  rules: {
    semi: [2, 'always'],
    'no-extra-semi': 2,
    // XXX: Due to an error in the webpack import and
    // vvv concern that we are coupling too many things
    // vvv into our lintint/commiting process I am gonna lower the
    // vvv level of this rule to a warning. We should explore
    // vvv if we wanna either remove or fix this in the future.
    'import/no-extraneous-dependencies': 1,
    'key-spacing': ['off'],
    'react/jsx-filename-extension': [0, { extensions: ['.js', '.jsx'] }],
    'no-underscore-dangle': [2, { "allow": ["_meta", "_items", "_status", "_super", "_ui", "_data"] }],
  },
  globals: {
    EC: true,
    waitTimeout: true,
  },
  settings: {
    flowtype: {
      onlyFilesWithFlowAnnotation: true,
    },
    // XXX: related to above rule and "eslint-import-resolver-webpack" package
    // look at https://github.com/benmosher/eslint-plugin-import/issues/799
    'import/resolver': {
      webpack: {
        config: path.resolve(__dirname, 'webpack.config.js'),
      },
    },
  },
};
```

My user settings for the extension are
```
"eslint.autoFixOnSave": false,
"eslint.packageManager": "npm",
```

This appears to be related to some odd behavior I am seeing with the linting errors displayed in the editor while coding. Getting a lot of `Parsing error: Unexpected token` errors that appear to display for issues that are behind what is currently typed into the editor.

**Comment by devert** [comment]
Here is the stack trace for this problem also

```
[Error - 10:28:50] ESLint stack trace:
[Error - 10:28:50] TypeError: sourceCode.getCommentsBefore is not a function
    at Object.fix (/Users/dennisevert/Projects/Leadpages/lead-pages/node_modules/eslint-plugin-react/lib/rules/jsx-curly-spacing.js:256:46)
    at RuleContext.report (/Users/dennisevert/Projects/Leadpages/lead-pages/node_modules/eslint/lib/rule-context.js:127:34)
    at reportNoEndingSpace (/Users/dennisevert/Projects/Leadpages/lead-pages/node_modules/eslint-plugin-react/lib/rules/jsx-curly-spacing.js:250:15)
    at EventEmitter.validateBraceSpacing (/Users/dennisevert/Projects/Leadpages/lead-pages/node_modules/eslint-plugin-react/lib/rules/jsx-curly-spacing.js:368:11)
    at emitOne (events.js:101:20)
    at EventEmitter.emit (events.js:191:7)
    at NodeEventGenerator.applySelector (/Users/dennisevert/Projects/Leadpages/lead-pages/node_modules/eslint/lib/util/node-event-generator.js:265:26)
    at NodeEventGenerator.applySelectors (/Users/dennisevert/Projects/Leadpages/lead-pages/node_modules/eslint/lib/util/node-event-generator.js:294:22)
    at NodeEventGenerator.enterNode (/Users/dennisevert/Projects/Leadpages/lead-pages/node_modules/eslint/lib/util/node-event-generator.js:308:14)
    at CodePathAnalyzer.enterNode (/Users/dennisevert/Projects/Leadpages/lead-pages/node_modules/eslint/lib/code-path-analysis/code-path-analyzer.js:602:23)
    at CommentEventGenerator.enterNode (/Users/dennisevert/Projects/Leadpages/lead-pages/node_modules/eslint/lib/util/comment-event-generator.js:98:23)
    at Traverser.enter (/Users/dennisevert/Projects/Leadpages/lead-pages/node_modules/eslint/lib/eslint.js:929:36)
```

**Comment by dbaeumer** [comment]
@devert: can you please report the issue to `eslint-plugin-react` which is actually causing the exception. I am pretty sure will see the same error even when running eslint directly from a terminal. Right?

**Comment by devert** [comment]
🤦‍♂️ Thanks @dbaeumer. You were right. There was an issue about this in `eslint-plugin-react` and I was able to resolve.
