### ISSUE TITLE
Get error using airbnb config but works from cli

### ISSUE THREAD

**Issue by ztolley** [Microsoft/vscode-eslint#494]
I've created a simple project and am trying to setup linting to use the Airbnb rules

If I edit my App.jsx file in Visual Studio Code vscode-eslint throws an error, complaining about something in the Airbnb source, but if I run eslint from the command line it lints things fine.

![capture](https://user-images.githubusercontent.com/56056/42122825-9d07dd64-7c3f-11e8-9c50-1f6dd01c9eeb.PNG)

The project can be found here: https://github.com/ztolley/react-full-stack/tree/airbnb

**Comment by dbaeumer** [comment]
Actually cloning the repository and executing eslint both inside VS Code and outside produces this for me:

```
Cannot find module 'eslint-config-react-app'
Referenced from: C:\Users\dirkb\Projects\mseng\VSCode\Playgrounds\bugs\eslint\494\client\.eslintrc
Error: Cannot find module 'eslint-config-react-app'
Referenced from: C:\Users\dirkb\Projects\mseng\VSCode\Playgrounds\bugs\eslint\494\client\.eslintrc
    at ModuleResolver.resolve (C:\Users\dirkb\Projects\mseng\VSCode\Playgrounds\bugs\eslint\494\node_modules\eslint\lib\util\module-resolver.js:74:19)
    at resolve (C:\Users\dirkb\Projects\mseng\VSCode\Playgrounds\bugs\eslint\494\node_modules\eslint\lib\config\config-file.js:471:25)
    at load (C:\Users\dirkb\Projects\mseng\VSCode\Playgrounds\bugs\eslint\494\node_modules\eslint\lib\config\config-file.js:542:26)
    at configExtends.reduceRight (C:\Users\dirkb\Projects\mseng\VSCode\Playgrounds\bugs\eslint\494\node_modules\eslint\lib\config\config-file.js:421:36)
    at Array.reduceRight (<anonymous>)
    at applyExtends (C:\Users\dirkb\Projects\mseng\VSCode\Playgrounds\bugs\eslint\494\node_modules\eslint\lib\config\config-file.js:403:28)
    at loadFromDisk (C:\Users\dirkb\Projects\mseng\VSCode\Playgrounds\bugs\eslint\494\node_modules\eslint\lib\config\config-file.js:514:22)
    at Object.load (C:\Users\dirkb\Projects\mseng\VSCode\Playgrounds\bugs\eslint\494\node_modules\eslint\lib\config\config-file.js:550:20)
    at Config.getLocalConfigHierarchy (C:\Users\dirkb\Projects\mseng\VSCode\Playgrounds\bugs\eslint\494\node_modules\eslint\lib\config.js:228:44)
    at Config.getConfigHierarchy (C:\Users\dirkb\Projects\mseng\VSCode\Playgrounds\bugs\eslint\494\node_modules\eslint\lib\config.js:180:43)
```

Any additional info?

**Comment by ztolley** [comment]
Not sure how my reply got deleted. The app has a subfolder, client, that you also need to run yarn install in. Then you get the issue.

**Comment by dbaeumer** [comment]
Reopening then

**Comment by dbaeumer** [comment]
Strange. Here is what is see after running yarn install in the client folder

![capture](https://user-images.githubusercontent.com/1931590/42790871-11a18a28-8922-11e8-8092-09a8e937d881.png)

Any additional steps?
