### ISSUE TITLE
Cannot read property 'loc' of undefined. Please see the 'ESLint' output channel for details.

### ISSUE THREAD

**Issue by u3u** [Microsoft/vscode-eslint#496]
I often receive this error notification, is there any way to disable it?

```
[Error - 21:57:16] ESLint stack trace:
[Error - 21:57:16] TypeError: Cannot read property 'loc' of undefined
    at Object.VariableDeclaration [as listener] (node_modules/eslint/lib/rules/indent.js:1317:68)
    at Program:exit.listenerCallQueue.filter.forEach.nodeInfo (node_modules/eslint/lib/rules/indent.js:1496:55)
    at Array.forEach (native)
    at Program:exit (node_modules/eslint/lib/rules/indent.js:1496:26)
    at listeners.(anonymous function).forEach.listener (node_modules/eslint/lib/util/safe-emitter.js:47:58)
    at Array.forEach (native)
    at Object.emit (node_modules/eslint/lib/util/safe-emitter.js:47:38)
    at NodeEventGenerator.applySelector (node_modules/eslint/lib/util/node-event-generator.js:251:26)
    at NodeEventGenerator.applySelectors (node_modules/eslint/lib/util/node-event-generator.js:280:22)
    at NodeEventGenerator.leaveNode (node_modules/eslint/lib/util/node-event-generator.js:303:14)

```

**Comment by dbaeumer** [comment]
This looks like a problem of the eslint npm module itself (https://eslint.org/). Does the problem occur if you run eslint in a terminal and validate the file there.

**Comment by u3u** [comment]
<img src="https://user-images.githubusercontent.com/20062482/42280397-38e02156-7fd3-11e8-8e06-f12f47203b95.png" width="500">

There will be no problems running in the terminal, only vscode will notify the error from time to time. 
I don't know how to reproduce it at the moment.

**Comment by dbaeumer** [comment]
Without steps to reproduce this is very hard to track down. If you have any, please provide them here.

**Comment by dbaeumer** [comment]
The reason why the notification is shown is that there is a serious error. Not showing it would simply mean swallowing it. Best would be to have steps on how to reproduce it so it can be fixed. 

I looked at the screen shot and the information doesn't help me to understand why it is failing. 

Since the failure happens in the eslint module have you tried to move to never version of the ESLint npm module (not the VS Code extension)
