### ISSUE TITLE
SyntaxError: Unexpected token e in JSON at position 0

### ISSUE THREAD

**Issue by UnderNotic** [Microsoft/vscode-eslint#533]
No matter what eslint config i have I'm getting error:
```
SyntaxError: Unexpected token e in JSON at position 0
    at JSON.parse (<anonymous>)
    at new IgnoredPaths (/home/undernotic/workspace/projects/react-file-load/example/node_modules/eslint/lib/ignored-paths.js:174:55)
    at CLIEngine.executeOnText (/home/undernotic/workspace/projects/react-file-load/example/node_modules/eslint/lib/cli-engine.js:593:28)
    at validate (/home/undernotic/.vscode/extensions/dbaeumer.vscode-eslint-1.5.0/server/out/eslintServer.js:613:26)
    at resolveSettings.then (/home/undernotic/.vscode/extensions/dbaeumer.vscode-eslint-1.5.0/server/out/eslintServer.js:544:13)
    at <anonymous>
```

Given config .eslintrc file at project root level
```
{
  "parserOptions": {
      "ecmaVersion": 6,
      "sourceType": "module",
      "ecmaFeatures": {
          "jsx": true
      }
  },
  "rules": {
      "semi": 2
  }
}
```

My os is Linux mint 19.

**Comment by UnderNotic** [comment]
Solved. I was missing some npm packages.
