### ISSUE TITLE
Uncaught exception

### ISSUE THREAD

**Issue by joshgeller** [Microsoft/vscode-eslint#545]
macOS High Sierra 10.13.6
VS Code 1.27.1

```
[Info  - 11:44:31 AM] ESLint library loaded from: /Users/me/node_modules/eslint/lib/api.js
Uncaught exception recevied.
Error: spawn /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper.app/Contents/MacOS/Code Helper ENOENT
    at _errnoException (util.js:1024:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:190:19)
    at onErrorNT (internal/child_process.js:372:16)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
````

**Comment by dbaeumer** [comment]
For some reason the ESLint extension can't spawn another node process. Does it work if you use the setting `eslint.runtime` and point to a installed node version on your system?
