### ISSUE TITLE
sourceCode.getCommentsBefore is not a function

### ISSUE THREAD

**Issue by bm-stschneider** [Microsoft/vscode-eslint#592]
Issue Type: <b>Bug</b>
I encountered the following error message in vscode recently.

```log
[Error - 1:54:24 PM] ESLint stack trace:
[Error - 1:54:24 PM] TypeError: sourceCode.getCommentsBefore is not a function
    at hasJSDocThisTag (/node_modules/eslint/lib/util/ast-utils.js:243:23)
    at Object.isDefaultThisBinding (/node_modules/eslint/lib/util/ast-utils.js:625:39)
    at Array.stack.getCurrent (/node_modules/eslint/lib/rules/no-invalid-this.js:50:43)
    at EventEmitter.ThisExpression (/node_modules/eslint/lib/rules/no-invalid-this.js:118:39)
    at EventEmitter.emit (events.js:187:15)
    at NodeEventGenerator.applySelector (/node_modules/eslint/lib/util/node-event-generator.js:265:26)
    at NodeEventGenerator.applySelectors (/node_modules/eslint/lib/util/node-event-generator.js:294:22)
    at NodeEventGenerator.enterNode (/node_modules/eslint/lib/util/node-event-generator.js:308:14)
    at CodePathAnalyzer.enterNode (/node_modules/eslint/lib/code-path-analysis/code-path-analyzer.js:602:23)
    at CommentEventGenerator.enterNode (/node_modules/eslint/lib/util/comment-event-generator.js:98:23)
```

Extension version: 1.7.2
VS Code version: Code - Insiders 1.31.0-insider (edf1090b8546ad0d17f30bf6f8075613e37e1b37, 2018-12-17T09:59:53.442Z)
OS version: Darwin x64 17.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4980HQ CPU @ 2.80GHz (8 x 2800)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 5, 4|
|Memory (System)|16.00GB (0.02GB free)|
|Process Argv|-psn_0_3896247|
|Screen Reader|no|
|VM|0%|

</details>

**Comment by dbaeumer** [comment]
This looks like a problem in ESLint npm module itself. 

@bm-stschneider if you run this in a terminal do you see the same error? If yes, please file an issue here: https://github.com/eslint/eslint. If no, can you provide me with a GitHub repository that demos this?
