### ISSUE TITLE
Error: channel closed 

### ISSUE THREAD

**Issue by aeschli** [Microsoft/vscode-eslint#63]
Error from error telemetry

Error: channel closed 
at ChildProcess.target.send (internal/child_process.js:509:16) <no sourcemaps> 
 at IPCMessageWriter.write (/Users/c2159749/.vscode-insiders/extensions/dbaeumer.vscode-eslint-0.10.13/node_modules/vscode-languageclient/node_modules/vscode-jsonrpc/lib/messageWriter.js:34:22) <no sourcemaps> 
 at Object.connection.sendNotification (/Users/c2159749/.vscode-insiders/extensions/dbaeumer.vscode-eslint-0.10.13/node_modules/vscode-languageclient/node_modules/vscode-jsonrpc/lib/main.js:180:27) <no sourcemaps> 
 at Object.result.didCloseTextDocument (/Users/c2159749/.vscode-insiders/extensions/dbaeumer.vscode-eslint-0.10.13/node_modules/vscode-languageclient/lib/main.js:56:69) <no sourcemaps> 
 at LanguageClient.onDidCloseTextDoument (/Users/c2159749/.vscode-insiders/extensions/dbaeumer.vscode-eslint-0.10.13/node_modules/vscode-languageclient/lib/main.js:381:20) <no sourcemaps> 
 at /Users/c2159749/.vscode-insiders/extensions/dbaeumer.vscode-eslint-0.10.13/node_modules/vscode-languageclient/lib/main.js:279:87 <no sourcemaps>

**Comment by robertlong** [comment]
I'm getting the same thing:

```
Error: channel closed
    at ChildProcess.target.send (internal/child_process.js:509:16)
    at IPCMessageWriter.write (/Users/robertlong/.vscode-insiders/extensions/dbaeumer.vscode-eslint-0.10.13/node_modules/vscode-languageclient/node_modules/vscode-jsonrpc/lib/messageWriter.js:34:22)
    at Object.connection.sendNotification (/Users/robertlong/.vscode-insiders/extensions/dbaeumer.vscode-eslint-0.10.13/node_modules/vscode-languageclient/node_modules/vscode-jsonrpc/lib/main.js:180:27)
    at Object.result.didOpenTextDocument (/Users/robertlong/.vscode-insiders/extensions/dbaeumer.vscode-eslint-0.10.13/node_modules/vscode-languageclient/lib/main.js:54:68)
    at LanguageClient.onDidOpenTextDoument (/Users/robertlong/.vscode-insiders/extensions/dbaeumer.vscode-eslint-0.10.13/node_modules/vscode-languageclient/lib/main.js:361:20)
    at /Users/robertlong/.vscode-insiders/extensions/dbaeumer.vscode-eslint-0.10.13/node_modules/vscode-languageclient/lib/main.js:277:86
    at e.invoke (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/node/pluginHostProcess.js:7:14035)
    at e.fire (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/node/pluginHostProcess.js:7:15488)
    at e._acceptModelAdd (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/node/pluginHostProcess.js:18:26095)
    at t.e.handle (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/node/pluginHostProcess.js:15:12687)
```

This happened sometime in the last few days. I believe I updated the extension and this began happening silently without any visible errors.

I was wondering how I was writing such perfect syntax the past few days 😄  now I know why.

I'll try to find a way to roll back / manually install an earlier version of a plugin to see if that fixes the issue, although I'm not sure how to do so yet.

**Comment by robertlong** [comment]
By the way, this is not exclusive to VSCode Insiders. This occurs for me with the latest VSCode Stable as well.

```
channel closed: Error: channel closed
    at ChildProcess.target.send (internal/child_process.js:509:16)
    at IPCMessageWriter.write (/Users/robertlong/.vscode/extensions/dbaeumer.vscode-eslint-0.10.13/node_modules/vscode-languageclient/node_modules/vscode-jsonrpc/lib/messageWriter.js:34:22)
    at Object.connection.sendNotification (/Users/robertlong/.vscode/extensions/dbaeumer.vscode-eslint-0.10.13/node_modules/vscode-languageclient/node_modules/vscode-jsonrpc/lib/main.js:180:27)
    at Object.result.didChangeTextDocument (/Users/robertlong/.vscode/extensions/dbaeumer.vscode-eslint-0.10.13/node_modules/vscode-languageclient/lib/main.js:55:70)
    at Delayer.task (/Users/robertlong/.vscode/extensions/dbaeumer.vscode-eslint-0.10.13/node_modules/vscode-languageclient/lib/main.js:373:28)
    at /Users/robertlong/.vscode/extensions/dbaeumer.vscode-eslint-0.10.13/node_modules/vscode-languageclient/lib/utils/async.js:27:36
```

**Comment by robertlong** [comment]
I'm not sure why, but this is no longer occurring for me. I have since updated to 0.10.15, however I do not see anything in the release notes to suggest that these last two updates fixed the issue.

How about you @aeschli?

**Comment by dbaeumer** [comment]
@robertlong this happens when the language server doing the actual linting crashes. Do you know whether you changed anything around eslint (installed a new version, ...).

**Comment by dbaeumer** [comment]
I opened https://github.com/Microsoft/vscode-languageserver-node/issues/34 since the language server process management must be done in the language client.

**Comment by dbaeumer** [comment]
I added support to the LSP to restart a server when it crashes. And ESLint now handles the case when the eslint server calls process.exit() which is the case in some eslint plugins.
