### ISSUE TITLE
TypeError: Cannot read property of 'CLIEngine' of undefined

### ISSUE THREAD

**Issue by ashah023** [microsoft/vscode-eslint#651]
Hi team,

I've been consistently getting this error in the output channel of ESLint and was wondering if you could point me in the right direction:

```
[Info  - 12:48:15 AM] ESLint server stopped.
[Info  - 12:48:15 AM] ESLint server running in node v11.6.0
[Info  - 12:48:15 AM] ESLint server is running.
(node:3749) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'CLIEngine' of undefined
    at n.then.e (/Users/username/.vscode/extensions/dbaeumer.vscode-eslint-1.8.2/server/out/eslintServer.js:1:28199)
    at process.internalTickCallback (internal/process/next_tick.js:77:7)
(node:3749) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
```

If there's any suggestions or information you know of that can help me resolve this, please let me know. Thanks!

**Comment by dbaeumer** [comment]
@ashah023 which version of ESLint npm are you using. Can you provide me with a GitHub repository that reveals the behavior I could clone?

**Comment by anburocky3** [comment]
I'm too experiencing the same problem. here is the complete log
``` [Info  - 8:27:26 PM] ESLint server stopped.
[Info  - 8:27:27 PM] ESLint server running in node v10.2.0
[Info  - 8:27:27 PM] ESLint server is running.
[Info  - 8:27:28 PM] ESLint library loaded from: /home/cyberdude/Desktop/react-pro/react-do/react-client/node_modules/eslint/lib/api.js
(node:13097) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'CLIEngine' of undefined
    at n.then.e (/home/name/.vscode/extensions/dbaeumer.vscode-eslint-1.8.2/server/out/eslintServer.js:1:28292)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:13097) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:13097) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:13097) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'CLIEngine' of undefined
    at n.then.e (/home/name/.vscode/extensions/dbaeumer.vscode-eslint-1.8.2/server/out/eslintServer.js:1:28292)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:13097) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:13097) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'CLIEngine' of undefined
    at n.then.e (/home/name/.vscode/extensions/dbaeumer.vscode-eslint-1.8.2/server/out/eslintServer.js:1:28292)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:13097) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 3)
[Error - 9:35:54 PM] ESLint stack trace:
[Error - 9:35:54 PM] Error: ENOENT: no such file or directory, uv_cwd
    at process.cwd (/home/name/Desktop/react-pro/react-do/react-client/node_modules/graceful-fs/polyfills.js:10:19)
    at /home/name/.vscode/extensions/dbaeumer.vscode-eslint-1.8.2/server/out/eslintServer.js:1:34579
    at W.E.get.N.then.n (/home/name/.vscode/extensions/dbaeumer.vscode-eslint-1.8.2/server/out/eslintServer.js:1:35937)
[Error - 9:39:11 PM] ESLint stack trace:
[Error - 9:39:11 PM] Error: ENOENT: no such file or directory, uv_cwd
    at process.cwd (/home/name/Desktop/react-pro/react-do/react-client/node_modules/graceful-fs/polyfills.js:10:19)
    at /home/name/.vscode/extensions/dbaeumer.vscode-eslint-1.8.2/server/out/eslintServer.js:1:34579
    at W.E.get.N.then.n (/home/name/.vscode/extensions/dbaeumer.vscode-eslint-1.8.2/server/out/eslintServer.js:1:35937)
[Error - 9:39:16 PM] ESLint stack trace:
[Error - 9:39:16 PM] Error: ENOENT: no such file or directory, uv_cwd
    at process.cwd (/home/name/Desktop/react-pro/react-do/react-client/node_modules/graceful-fs/polyfills.js:10:19)
    at /home/name/.vscode/extensions/dbaeumer.vscode-eslint-1.8.2/server/out/eslintServer.js:1:34579
    at W.E.get.N.then.n (/home/name/.vscode/extensions/dbaeumer.vscode-eslint-1.8.2/server/out/eslintServer.js:1:35937)
[Error - 9:41:44 PM] ESLint stack trace:
[Error - 9:41:44 PM] Error: ENOENT: no such file or directory, uv_cwd
    at process.cwd (/home/name/Desktop/react-pro/react-do/react-client/node_modules/graceful-fs/polyfills.js:10:19)
    at /home/name/.vscode/extensions/dbaeumer.vscode-eslint-1.8.2/server/out/eslintServer.js:1:34579
    at W.E.get.N.then.n (/home/name/.vscode/extensions/dbaeumer.vscode-eslint-1.8.2/server/out/eslintServer.js:1:35937)```

**Comment by anburocky3** [comment]
**Update:** restarting the editor, fixed the issue.

**Comment by dbaeumer** [comment]
Any steps to reproduce?

**Comment by ashah023** [comment]
> @ashah023 which version of ESLint npm are you using. Can you provide me with a GitHub repository that reveals the behavior I could clone?

ESLint: 5.16.0
npm: 6.7.0

I'll try to put together a clone-able repository for you this weekend. Thank you for your assistance.

**Comment by ashah023** [comment]
Sorry, I haven't had the time to create a clone-able repository. Should I close this and open another issue when I have the chance to make one, or leave this one open and revisit it later? 

Thank you for your time.

**Comment by dbaeumer** [comment]
@ashah023 I leave this one open for some time.

**Comment by bmashru** [comment]
Facing the same issue 

> (node:23174) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'CLIEngine' of undefined
    at n.then.e (/Users/userName/.vscode/extensions/dbaeumer.vscode-eslint-1.8.2/server/out/eslintServer.js:1:28292)
    at process._tickCallback (internal/process/next_tick.js:68:7)

**Comment by decentraliser** [comment]
same here:
node v10.2.0
win10

`
    "eslint": "^5.16.0",
    "eslint-config-airbnb-base": "^13.1.0",
    "eslint-plugin-import": "^2.16.0",
    "eslint-plugin-vue": "^5.2.2",

(node:73400) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'CLIEngine' of undefined
    at n.then.e (c:\Users\jeanl\.vscode\extensions\dbaeumer.vscode-eslint-1.8.2\server\out\eslintServer.js:1:28292)
    at process._tickCallback (internal/process/next_tick.js:68:7)
`

**Comment by decentraliser** [comment]
I just downgraded `eslint `version to 5.15.0, ran `npm i`, and I am not facing the issue anymore

**Comment by dbaeumer** [comment]
Strange, eslint 5.16.0 works for me. @decentraliser can you provide me with a GitHub repository I can clone that demos what you are seeing.

![capture](https://user-images.githubusercontent.com/1931590/56567883-20304b80-65b6-11e9-9067-3557cbbc9f8e.png)

**Comment by decentraliser** [comment]
for some reason after a few tries, I didn't manage to reproduce it @dbaeumer ...

**Comment by dbaeumer** [comment]
Does anyone have additional info on how to reproduce.

**Comment by bmashru** [comment]
Upgraded to 5.16 and EsLint started working.

**Comment by dbaeumer** [comment]
@bmashru do you remember which eslint version you used before?

**Comment by bmashru** [comment]
@dbaeumer 

Before:
 global ver: 5.16
 project ver: 5.15.1

Current (Working):
 global ver: 5.16
 project ver: 5.16

**Comment by dbaeumer** [comment]
I can not reproduce this. ESLint `5.15.1` works for me as well. 

Has anyone additional info on how to reproduce?

**Comment by matheo** [comment]
I had the same error but was `eslint` version mismatch indeed. Thanks!
