### ISSUE TITLE
UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'CLIEngine' of undefined

### ISSUE THREAD

**Issue by raksa** [microsoft/vscode-eslint#714]
MacOSX 10.14.5
vscode:
1.36.1
2213894ea0415ee8c85c5eea0d0ff81ecc191529
x64

```

(node:2850) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'CLIEngine' of undefined
    at n.then.e (/Users/raksa/.vscode/extensions/dbaeumer.vscode-eslint-1.9.0/server/out/eslintServer.js:1:47836)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:2850) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:2850) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:2850) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'CLIEngine' of undefined
    at n.then.e (/Users/raksa/.vscode/extensions/dbaeumer.vscode-eslint-1.9.0/server/out/eslintServer.js:1:47836)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:2850) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)

```

**Comment by dbaeumer** [comment]
Dups #713
