### ISSUE TITLE
Cannot read property 'indexOf' of undefined writing import statement

### ISSUE THREAD

**Issue by crystalfp** [microsoft/vscode-eslint#897]
Issue Type: <b>Bug</b>

1. Have a types.d.ts file defining and exporting the interface `MyInterface`.
2. In a ts file start writing the import statement `import {MyInterface} from`
At this point a notification appears with the following text:
```
ESLint: Cannot read property 'indexOf' of undefined
Occurred while linting D:\Projects\IdeaIgniterEnvironment\client\east-viewmodel.ts:3.
Please see the 'ESLint' output channel for details.
```
The output channel shows the following stack trace:
```
[Error - 6:05:10 AM] TypeError: Cannot read property 'indexOf' of undefined
Occurred while linting D:\Projects\IdeaIgniterEnvironment\client\east-viewmodel.ts:3
    at stripImportPathParams (D:\Projects\IdeaIgniterEnvironment\node_modules\eslint-plugin-node\lib\util\strip-import-path-params.js:8:20)
    at ExportAllDeclaration,ExportNamedDeclaration,ImportDeclaration,ImportExpression (D:\Projects\IdeaIgniterEnvironment\node_modules\eslint-plugin-node\lib\util\visit-import.js:55:40)
    at D:\Projects\IdeaIgniterEnvironment\node_modules\eslint\lib\linter\safe-emitter.js:45:58
    at Array.forEach (<anonymous>)
    at Object.emit (D:\Projects\IdeaIgniterEnvironment\node_modules\eslint\lib\linter\safe-emitter.js:45:38)
    at NodeEventGenerator.applySelector (D:\Projects\IdeaIgniterEnvironment\node_modules\eslint\lib\linter\node-event-generator.js:254:26)
    at NodeEventGenerator.applySelectors (D:\Projects\IdeaIgniterEnvironment\node_modules\eslint\lib\linter\node-event-generator.js:283:22)
    at NodeEventGenerator.enterNode (D:\Projects\IdeaIgniterEnvironment\node_modules\eslint\lib\linter\node-event-generator.js:297:14)
    at CodePathAnalyzer.enterNode (D:\Projects\IdeaIgniterEnvironment\node_modules\eslint\lib\linter\code-path-analysis\code-path-analyzer.js:634:23)
    at D:\Projects\IdeaIgniterEnvironment\node_modules\eslint\lib\linter\linter.js:936:32
```
Not critical, but annoying.
Thanks for looking!
mario

Extension version: 2.0.15
VS Code version: Code 1.42.0 (ae08d5460b5a45169385ff3fd44208f431992451, 2020-02-06T10:51:34.058Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz (8 x 2904)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.81GB (4.73GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by dbaeumer** [comment]
@crystalfp this looks like a problem in the `eslint-plugin-node` module`  and I am pretty confident it will occur as well when you try to validate the file in that state in the terminal using the eslint command. 

Can you please file the issue against the owner of the extension.

**Comment by crystalfp** [comment]
OK opened on `eslint-plugin-node`.
Thanks!
