### ISSUE TITLE
eslint complains of missing module that doesn't exist in npm

### ISSUE THREAD

**Issue by GaurangTandon** [microsoft/vscode-eslint#898]
Error received:

```
[Error - 11:19:03 AM] ESLint stack trace:
[Error - 11:19:03 AM] Error: Cannot find module './default-param-last'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:582:15)
    at Function.Module._load (internal/modules/cjs/loader.js:508:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at default-param-last (./frontend/node_modules/eslint/lib/rules/index.js:40:33)
    at Map.entries (./frontend/node_modules/eslint/lib/rules/utils/lazy-loading-rule-map.js:87:28)
    at entries.next (<anonymous>)
    at ./frontend/node_modules/eslint/lib/cli-engine/cli-engine.js:629:13
    at Generator.next (<anonymous>)
    at new Map (<anonymous>)
```

Folder structure:

```
workspace (opened folder in VS Code)
 - .vscode
 - frontend
   - eslintrc
   - package.json
```

`package.json`

```
{
  "name": "frontend",
  "version": "0.1.0",
  "private": true,
  "dependencies": {
    "prop-types": "^15.7.2",
    "react": "^16.8.6",
    "react-dom": "^16.8.6",
    "react-router-dom": "^5.0.1",
    "react-scripts": "^3.3.1",
    "react-text-truncate": "^0.14.1",
    "reactstrap": "^8.0.0"
  },
  "scripts": {
    "start": "set PORT=8080 && react-scripts start",
    "build": "react-scripts build",
    "test": "react-scripts test",
    "eject": "react-scripts eject"
  },
  "eslintConfig": {
    "extends": "react-app"
  },
  "browserslist": {
    "production": [
      ">0.2%",
      "not dead",
      "not op_mini all"
    ],
    "development": [
      "last 1 chrome version",
      "last 1 firefox version",
      "last 1 safari version"
    ]
  },
  "devDependencies": {
    "@typescript-eslint/eslint-plugin": "^2.19.2",
    "@typescript-eslint/parser": "^2.19.2",
    "babel-eslint": "^10.0.3",
    "eslint": "^5.16.0",
    "eslint-config-airbnb-base": "^13.1.0",
    "eslint-plugin-import": "^2.17.3",
    "eslint-plugin-jsx-a11y": "^6.2.1",
    "eslint-plugin-react": "^7.13.0",
    "husky": "^2.4.1",
    "lint-staged": "^8.2.1"
  },
  "lint-staged": {
    "linters": {
      "*.js": [
        "eslint --fix",
        "git add"
      ]
    },
    "ignore": [
      "**/build/*.js"
    ]
  },
  "husky": {
    "hooks": {
      "pre-commit": "lint-staged",
      "post-commit": "git update-index -g"
    }
  }
}

```

`.eslintrc.json`

```
{
    "env": {
        "browser": true,
        "es6": true,
        "webextensions": true
    },
    "extends": [
        "airbnb-base",
        "plugin:react/recommended"
    ],
    "globals": {
        "Atomics": "readonly",
        "SharedArrayBuffer": "readonly"
    },
    "parserOptions": {
        "ecmaVersion": 2018,
        "sourceType": "module",
        "ecmaFeatures": {
            "jsx": true
        }
    },
    "rules": {
        "quotes": [
            "error",
            "double"
        ],
        "indent": [
            "warn",
            4
        ],
        "curly": [
            "error",
            "all"
        ],
        "func-names": "off",
        "no-multi-assign": "off",
        "no-plusplus": "off",
        "no-magic-numbers": "warn",
        "no-param-reassign": "off",
        "no-extend-native": "off",
        "one-var": [
            "error",
            "consecutive"
        ],
        "prefer-const": "warn",
        "no-global-assign": "warn",
        "no-tabs": "warn",
        "no-restricted-syntax": [
            "error",
            "ForInStatement",
            "LabeledStatement",
            "WithStatement"
        ],
        "no-nested-ternary": "warn",
        "no-use-before-define": "warn",
        "prefer-destructuring": "warn",
        "import/prefer-default-export": "off",
        "max-len": [
            "warn",
            {
                "code": 100
            }
        ],
        "no-continue": "off",
        "linebreak-style": "off",
        "class-methods-use-this": "off"
    }
}
```

`.vscode/settings.json`

```
{
    "eslint.nodePath": "frontend/node_modules",
    "eslint.alwaysShowStatus": true,
    "eslint.format.enable": true,
    "eslint.lintTask.enable": true,
    "eslint.workingDirectories": [
        "frontend"
    ]
}
```

How to fix this? I already googled about it but there does not seem to be any module in npm by this name. So, I am not really sure where to begin.

**Comment by dbaeumer** [comment]
@GaurangTandon  does the validation happen correctly when you use eslint in the terminal. If this is the case can you please provide me with a GitHub repository I can clone that demos what you are experiencing.

**Comment by GaurangTandon** [comment]
I am very sorry, but this was so long ago that I've lost track of the code which experienced this issue. I will post an update if I find something. Thank you.
