### ISSUE TITLE
EPERM: operation not permitted, write

### ISSUE THREAD

**Issue by ALF-er** [Microsoft/vscode-eslint#9]
Clean install of VSCode, Eslint, vscode-eslint and I'm constantly receiving this in DevTools
```
EPERM: operation not permitted, write
e.doShow @ workbench.main.js:1598
e.show @ workbench.main.js:1598
e.showMessage @ workbench.main.js:1590
__dirname.undefined.t.Class.derive._oncancel @ workbench.main.js:1544
e.showMessage @ workbench.main.js:1590
e.handle @ workbench.main.js:1588
a @ workbench.main.js:1576
h.handle @ workbench.main.js:1576
(anonymous function) @ workbench.main.js:1602
(anonymous function) @ workbench.main.js:1602
emitTwo @ events.js:87
emit @ events.js:172
handleMessage @ internal/child_process.js:685
channel.onread @ internal/child_process.js:440
```

**Comment by dbaeumer** [comment]
@ALF-er sorry for that. On which OS are you?

**Comment by ALF-er** [comment]
@dbaeumer Windows 10 (10586.17) x64

**Comment by dbaeumer** [comment]
@ALF-er strange me too. Does it easy reproduce for you with the test case you once provided to me?

**Comment by ALF-er** [comment]
@dbaeumer sorry, looks like i'ts project-dependent. I'll try to pick out new minimal project for it tomorrow (I'm from eastern Europe)

**Comment by dbaeumer** [comment]
@ALF-er thanks for trying to come up with a minimal project revealing the problem.

**Comment by ALF-er** [comment]
@dbaeumer sorry for delay here it's https://github.com/ALF-er/vscode-eslint-test Just `npm install` and try to lint (via VSCode) index.js

**Comment by dbaeumer** [comment]
@ALF-er The problem is caused by the react plugin writing to console.log which when executed in a electron node environment causes an exception:
```
"Error: EPERM: operation not permitted, write
    at Error (native)\n    at Object.fs.writeSync (fs.js:663:20)
	at SyncWriteStream.write (fs.js:1981:6)
	at Console.log (console.js:36:16)
	at EventEmitter.module.exports.character.Program (p:\mseng\VSCode\Playgrounds\bugs\vscode-eslint-test\node_modules\eslint-plugin-react\lib\rules\jsx-quotes.js:52:15)
	at emitOne (events.js:82:20)
	at EventEmitter.emit (events.js:169:7)
	at NodeEventGenerator.enterNode (p:\mseng\VSCode\Playgrounds\bugs\vscode-eslint-test\node_modules\eslint\lib\util\node-event-generator.js:42:22)
	at CommentEventGenerator.enterNode (p:\mseng\VSCode\Playgrounds\bugs\vscode-eslint-test\node_modules\eslint\lib\util\comment-event-generator.js:98:23)
	at Controller.module.exports.api.verify.controller.traverse.enter (p:\mseng\VSCode\Playgrounds\bugs\vscode-eslint-test\node_modules\eslint\lib\eslint.js:767:36)"
```
This seems to be related to https://github.com/atom/electron/issues/1471 and https://github.com/atom/electron/issues/3482

**Comment by dbaeumer** [comment]
and https://github.com/atom/electron/issues/2033

**Comment by dbaeumer** [comment]
I fixed this by using a separate pipe for stdio even if we use IPC communication. Nice side effect is that console.log statements of the linter now show up in a corresponding output channel.

![capture](https://cloud.githubusercontent.com/assets/1931590/11741767/5a788a70-9ffb-11e5-867e-f30d7c3a3055.png)

**Comment by ALF-er** [comment]
Sweet! Thank you!
