### ISSUE TITLE
[Error] not compatible with json?  "UnhandledPromiseRejectionWarning: Error: Request eslint/probleFailed failed with message: No provider available for the given text document."

### ISSUE THREAD

**Issue by ryuta69** [microsoft/vscode-eslint#952]
Hi I got `eslint/probleFailed` when I started to use this plugin inside json.

VSCode: 1.44.2
ESlint Plugin: 2.1.3

This may show that not compatible with json?

```
(node:23773) UnhandledPromiseRejectionWarning: Error: Request eslint/probleFailed failed with message: No provider available for the given text document
    at /Users/kohei.murakami/.vscode/extensions/dbaeumer.vscode-eslint-2.1.3/server/out/eslintServer.js:1:8961
    at /Users/kohei.murakami/.vscode/extensions/dbaeumer.vscode-eslint-2.1.3/server/out/eslintServer.js:1:9255
    at Immediate.<anonymous> (/Users/kohei.murakami/.vscode/extensions/dbaeumer.vscode-eslint-2.1.3/server/out/eslintServer.js:1:9616)
    at processImmediate (internal/timers.js:439:21)
(node:23773) UnhandledPromiseRejectionWarning: Error: Request eslint/probleFailed failed with message: No provider available for the given text document
    at /Users/kohei.murakami/.vscode/extensions/dbaeumer.vscode-eslint-2.1.3/server/out/eslintServer.js:1:8961
    at /Users/kohei.murakami/.vscode/extensions/dbaeumer.vscode-eslint-2.1.3/server/out/eslintServer.js:1:9255
    at Immediate.<anonymous> (/Users/kohei.murakami/.vscode/extensions/dbaeumer.vscode-eslint-2.1.3/server/out/eslintServer.js:1:9616)
    at processImmediate (internal/timers.js:439:21)
(node:23773) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 16)
(node:23773) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 16)
(node:23773) UnhandledPromiseRejectionWarning: Error: Request eslint/probleFailed failed with message: No provider available for the given text document
    at /Users/kohei.murakami/.vscode/extensions/dbaeumer.vscode-eslint-2.1.3/server/out/eslintServer.js:1:8961
    at /Users/kohei.murakami/.vscode/extensions/dbaeumer.vscode-eslint-2.1.3/server/out/eslintServer.js:1:9255
    at Immediate.<anonymous> (/Users/kohei.murakami/.vscode/extensions/dbaeumer.vscode-eslint-2.1.3/server/out/eslintServer.js:1:9616)
    at processImmediate (internal/timers.js:439:21)
(node:23773) UnhandledPromiseRejectionWarning: Error: Request eslint/probleFailed failed with message: No provider available for the given text document
    at /Users/kohei.murakami/.vscode/extensions/dbaeumer.vscode-eslint-2.1.3/server/out/eslintServer.js:1:8961
    at /Users/kohei.murakami/.vscode/extensions/dbaeumer.vscode-eslint-2.1.3/server/out/eslintServer.js:1:9255
    at Immediate.<anonymous> (/Users/kohei.murakami/.vscode/extensions/dbaeumer.vscode-eslint-2.1.3/server/out/eslintServer.js:1:9616)
    at processImmediate (internal/timers.js:439:21)
(node:23773) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 17)
(node:23773) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 17)
```

**Comment by dbaeumer** [comment]
@ryuta69 does the validation happen correctly when you use eslint in the terminal. If this is the case can you please provide me with a GitHub repository I can clone that demos what you are experiencing.

**Comment by ryuta69** [comment]
Sorry... this was mistaken. I did as you said and it worked. sorry about that.
