### ISSUE TITLE
vscode-eslint does not work for dotnet-core/react projects in vscode

### ISSUE THREAD

**Issue by ydsood** [microsoft/vscode-eslint#959]
`dotnet-core` comes with react templates since `netcore 2.0` which can be used to setup the project with a `dotnet-core` back end and a react front end. To work on this project, the project can be opened in VS code from the root directory with sln file. This allows for appropriate launch and debug configurations to be used for launching the dotnet project with react appropriately.

The ESLint plugin is somehow able to correctly locate the local eslint installation with the following vscode workspace settings, however it fails to find plugins specified in the `eslintrc.json` file. I am able to execute eslint correctly from the `ClientApp` folder. Is there some way to check the `node_modules` location that the ESLint plugin is using.

```JavaScript
{
  "eslint.format.enable": true,
  "editor.codeActionsOnSave": {
    "source.fixAll.eslint": true,
  },
  "eslint.packageManager": "npm",
  "eslint.enable": true,
  "editor.tabSize": 2,
  "eslint.run": "onSave",
  "[javascript]": { "editor.defaultFormatter": "dbaeumer.vscode-eslint" },
  "eslint.options": {
    "configFile": "ConfigApp/ClientApp/.eslintrc.json",
  },
}
```

Here is the project structure

```
netCoreApp
│   netCoreApp.sln
│
└───netCoreApp
    │   appsettings.Development.json
    │   appsettings.json
    │   netCoreApp.csproj
    │   netCoreApp.csproj.user
    │   Program.cs
    │   Startup.cs
    │
    ├───ClientApp
    │   │   .eslintrc.json
    │   │   package-lock.json
    │   │   package.json
    │   │   README.md
    │   │
    │   ├───node_modules
    │   └───src
    │           App.css
    │           App.js
    │           index.css
    │           index.js
    │
    ├───Controllers
    │       SampleDataController.cs
    │
    └───Properties
            launchSettings.json
```

Since the workspace for vscode is the root folder, the eslint plugin cannot find the plugin modules located in `netCoreApp/ClientApp/node_modules` and gives the following error
```
[Info  - 7:34:06 PM] Failed to load plugin 'react' declared in '--config': Cannot find module 'eslint-plugin-react' Require stack: - C:\__Repos__\netCoreApp\__placeholder__.js
```
Even the stack is empty and I cannot see any errors.

This error is not specific to the react plugin, when that is removed, an error is thrown for the next plugin. All the plugins specified in `.eslintrc.json` are installed in the `node_modules` folder
However, it is correctly able to locate `eslint` installation from the same location.

I generated this project using Visual Studio 2017 react-redux template. I can setup a sample project if needed, for reference.

**Comment by ydsood** [comment]
I tried to read through the suggestions on #696 but nothing has worked for me so far.

**Comment by dbaeumer** [comment]
@ydsood can you please provide me with a GitHub repository I can clone that demos what you are experiencing.

**Comment by ydsood** [comment]
Here's a sample repository https://github.com/ydsood/TestESLint.git.
I have committed the .vscode folder so you can have the same setup for launch and ESLint settings. I do not have a global installation for ESLint and use the node_modules location for generating the eslintrc.json using the following command

```
XXXXX\XXXXX\TestESLint\ClientApp> node_modules/.bin/eslint --init
```



Here's the error I am seeing on the ESLint output
```
[Info  - 2:01:41 PM] ESLint server stopped.
[Info  - 2:01:42 PM] ESLint server running in node v12.8.1
[Info  - 2:01:42 PM] ESLint server is running.
(node:7488) UnhandledPromiseRejectionWarning: Error: Failed to load plugin 'react' declared in '--config': Cannot find module 'eslint-plugin-react'
Require stack:
- XXXXX\XXXXX\XXXXX\TestESLint\__placeholder__.js
Referenced from: XXXXX\XXXXX\XXXXX\TestESLint\TestESLint\ClientApp\.eslintrc.json
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:717:15)
    at Function.resolve (internal/modules/cjs/helpers.js:74:19)
    at Object.resolve (XXXXX\XXXXX\XXXXX\TestESLint\TestESLint\ClientApp\node_modules\eslint\lib\shared\relative-module-resolver.js:44:50)
    at ConfigArrayFactory._loadPlugin (XXXXX\XXXXX\XXXXX\TestESLint\TestESLint\ClientApp\node_modules\eslint\lib\cli-engine\config-array-factory.js:959:39)
    at ConfigArrayFactory._loadExtendedPluginConfig (XXXXX\XXXXX\XXXXX\TestESLint\TestESLint\ClientApp\node_modules\eslint\lib\cli-engine\config-array-factory.js:779:29)
    at ConfigArrayFactory._loadExtends (XXXXX\XXXXX\XXXXX\TestESLint\TestESLint\ClientApp\node_modules\eslint\lib\cli-engine\config-array-factory.js:725:29)
    at ConfigArrayFactory._normalizeObjectConfigDataBody (XXXXX\XXXXX\XXXXX\TestESLint\TestESLint\ClientApp\node_modules\eslint\lib\cli-engine\config-array-factory.js:660:25)
    at _normalizeObjectConfigDataBody.next (<anonymous>)
    at ConfigArrayFactory._normalizeObjectConfigData (XXXXX\XXXXX\XXXXX\TestESLint\TestESLint\ClientApp\node_modules\eslint\lib\cli-engine\config-array-factory.js:596:20)
    at _normalizeObjectConfigData.next (<anonymous>)
(node:7488) UnhandledPromiseRejectionWarning: Error: Failed to load plugin 'react' declared in '--config': Cannot find module 'eslint-plugin-react'
Require stack:
- XXXXX\XXXXX\XXXXX\TestESLint\__placeholder__.js
Referenced from: XXXXX\XXXXX\XXXXX\TestESLint\TestESLint\ClientApp\.eslintrc.json
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:717:15)
    at Function.resolve (internal/modules/cjs/helpers.js:74:19)
    at Object.resolve (XXXXX\XXXXX\XXXXX\TestESLint\TestESLint\ClientApp\node_modules\eslint\lib\shared\relative-module-resolver.js:44:50)
    at ConfigArrayFactory._loadPlugin (XXXXX\XXXXX\XXXXX\TestESLint\TestESLint\ClientApp\node_modules\eslint\lib\cli-engine\config-array-factory.js:959:39)
    at ConfigArrayFactory._loadExtendedPluginConfig (XXXXX\XXXXX\XXXXX\TestESLint\TestESLint\ClientApp\node_modules\eslint\lib\cli-engine\config-array-factory.js:779:29)
    at ConfigArrayFactory._loadExtends (XXXXX\XXXXX\XXXXX\TestESLint\TestESLint\ClientApp\node_modules\eslint\lib\cli-engine\config-array-factory.js:725:29)
    at ConfigArrayFactory._normalizeObjectConfigDataBody (XXXXX\XXXXX\XXXXX\TestESLint\TestESLint\ClientApp\node_modules\eslint\lib\cli-engine\config-array-factory.js:660:25)
    at _normalizeObjectConfigDataBody.next (<anonymous>)
    at ConfigArrayFactory._normalizeObjectConfigData (XXXXX\XXXXX\XXXXX\TestESLint\TestESLint\ClientApp\node_modules\eslint\lib\cli-engine\config-array-factory.js:596:20)
    at _normalizeObjectConfigData.next (<anonymous>)
(node:7488) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:7488) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:7488) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:7488) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by dbaeumer** [comment]
Since validation needs to happen in the `TestESLint/ClientApp` directory (even in the terminal to work correctly the setting you need to use is

```
  "eslint.workingDirectories": [
    "./TestESLint/ClientApp"
  ]
```

The `eslint.options` setting needs to be removed.
