### ISSUE TITLE
UnhandledPromiseRejectionWarning on markdown file

### ISSUE THREAD

**Issue by Kagami** [microsoft/vscode-eslint#964]
Hi,

I've created empty workspace, empty markdown file, and started typing.

I see the following errors in the output:

```
(node:20433) UnhandledPromiseRejectionWarning: Error: No ESLint configuration found in /home/kagami/t.
    at CascadingConfigArrayFactory._finalizeConfigArray (/home/kagami/.npm-packages/lib/node_modules/eslint/lib/cli-engine/cascading-config-array-factory.js:432:19)
    at CascadingConfigArrayFactory.getConfigArrayForFile (/home/kagami/.npm-packages/lib/node_modules/eslint/lib/cli-engine/cascading-config-array-factory.js:271:21)
    at CLIEngine.getConfigForFile (/home/kagami/.npm-packages/lib/node_modules/eslint/lib/cli-engine/cli-engine.js:931:14)
    at /home/kagami/.vscode-server/extensions/dbaeumer.vscode-eslint-2.1.5/server/out/eslintServer.js:1:36902
    at ce (/home/kagami/.vscode-server/extensions/dbaeumer.vscode-eslint-2.1.5/server/out/eslintServer.js:1:46186)
    at f.then.r.validate (/home/kagami/.vscode-server/extensions/dbaeumer.vscode-eslint-2.1.5/server/out/eslintServer.js:1:36856)
    at processTicksAndRejections (internal/process/task_queues.js:89:5)
```

Environment:
* node v14
* globally installed eslint v6.8.0 to ~/.npm-packages
* vscode v1.44.2
* vscode-eslint v2.1.5

It's probably just cosmetics, but it clutters output window.

**Comment by dbaeumer** [comment]
@Kagami do you have eslint installed globally?

**Comment by Kagami** [comment]
Yes.
