### ISSUE TITLE
Error referencing not existing package eslint.config

### ISSUE THREAD

**Issue by crystalfp** [microsoft/vscode-eslint#974]
Issue Type: <b>Bug</b>

I have a project that reference the node package `tippy.js`.
In VS Code the eslint extension complains about extending a not existent eslint.config in the package:
```
[Error - 6:24:32 AM] ESLint stack trace:
[Error - 6:24:32 AM] Error: Failed to load config "./.config/eslint.config" to extend from.
Referenced from: D:\Project\node_modules\tippy.js\package.json
    at configMissingError (D:\Project\node_modules\eslint\lib\cli-engine\config-array-factory.js:282:9)
    at ConfigArrayFactory._loadExtendedShareableConfig (D:\Project\node_modules\eslint\lib\cli-engine\config-array-factory.js:858:23)
    at ConfigArrayFactory._loadExtends (D:\Project\node_modules\eslint\lib\cli-engine\config-array-factory.js:763:25)
    at ConfigArrayFactory._normalizeObjectConfigDataBody (D:\Project\node_modules\eslint\lib\cli-engine\config-array-factory.js:702:25)
    at _normalizeObjectConfigDataBody.next (<anonymous>)
    at ConfigArrayFactory._normalizeObjectConfigData (D:\Project\node_modules\eslint\lib\cli-engine\config-array-factory.js:647:20)
    at _normalizeObjectConfigData.next (<anonymous>)
    at ConfigArrayFactory.loadInDirectory (D:\Project\node_modules\eslint\lib\cli-engine\config-array-factory.js:495:28)
    at CascadingConfigArrayFactory._loadConfigInAncestors (D:\Project\node_modules\eslint\lib\cli-engine\cascading-config-array-factory.js:355:46)
    at CascadingConfigArrayFactory.getConfigArrayForFile (D:\Project\node_modules\eslint\lib\cli-engine\cascading-config-array-factory.js:276:18)
```
The `tippy.js` module `package.json` contains the following lines:
```
  "eslintConfig": {
    "extends": "./.config/eslint.config"
  },
```
but the subdirectory `.config` is missing.

Besides the annoying notification, all seems to work.
I opened an issue to the package maintainer to fix the reference, but could eslint extension simply ignore the error?
Thanks for reading!
mario

Extension version: 2.1.5
VS Code version: Code 1.45.1 (5763d909d5f12fe19f215cbfdd29a91c0fa9208a, 2020-05-14T08:27:35.169Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz (8 x 2904)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.81GB (7.79GB free)|
|Process Argv|D:\Projects\IdeaIgniterEnvironment\IdeaIgniterEnvironment.code-workspace|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by crystalfp** [comment]
Running eslint externally show no error.

**Comment by crystalfp** [comment]
The issue for `tippy.js` [here](https://github.com/atomiks/tippyjs/issues/780#issuecomment-629747378) states it is not a package problem, but `eslintConfig` in package.json should be ignored by eslint extension.

**Comment by dbaeumer** [comment]
The ESLint extension doesn't read any config by itself. It fully relies on the behavior of eslint itself (e.g. https://eslint.org/)

Does the validation happen correctly when you use eslint in the terminal. If this is the case can you please provide me with a GitHub repository I can clone that demos what you are experiencing.

**Comment by crystalfp** [comment]
Embarrassing. The error no longer appears. I have only rebooted and restarted VS Code. Anyway, if it reappears, sure I will reopen this issue.
Thanks for the patience!
mario

**Comment by Mossop** [comment]
I'm seeing this locally too:

```
[Error - 8:22:03 AM] ESLint stack trace:
[Error - 8:22:03 AM] Error: Failed to load config "./node_modules/kcd-scripts/eslint.js" to extend from.
Referenced from: /Users/dave/workspace/pixelbin/node_modules/@testing-library/dom/package.json
    at configMissingError (/Users/dave/workspace/pixelbin/node_modules/eslint/lib/cli-engine/config-array-factory.js:282:9)
    at ConfigArrayFactory._loadExtendedShareableConfig (/Users/dave/workspace/pixelbin/node_modules/eslint/lib/cli-engine/config-array-factory.js:858:23)
    at ConfigArrayFactory._loadExtends (/Users/dave/workspace/pixelbin/node_modules/eslint/lib/cli-engine/config-array-factory.js:763:25)
    at ConfigArrayFactory._normalizeObjectConfigDataBody (/Users/dave/workspace/pixelbin/node_modules/eslint/lib/cli-engine/config-array-factory.js:702:25)
    at _normalizeObjectConfigDataBody.next (<anonymous>)
    at ConfigArrayFactory._normalizeObjectConfigData (/Users/dave/workspace/pixelbin/node_modules/eslint/lib/cli-engine/config-array-factory.js:647:20)
    at _normalizeObjectConfigData.next (<anonymous>)
    at ConfigArrayFactory.loadInDirectory (/Users/dave/workspace/pixelbin/node_modules/eslint/lib/cli-engine/config-array-factory.js:495:28)
    at CascadingConfigArrayFactory._loadConfigInAncestors (/Users/dave/workspace/pixelbin/node_modules/eslint/lib/cli-engine/cascading-config-array-factory.js:355:46)
    at CascadingConfigArrayFactory._loadConfigInAncestors (/Users/dave/workspace/pixelbin/node_modules/eslint/lib/cli-engine/cascading-config-array-factory.js:374:20)
```

In this case `kcd-scripts` is a dev-dependency of `@testing-library/dom` and so not installed. Running eslint directly from the command line shows no errors. It looks like simply importing something from `@testing-library/dom` causes the issue. This is a demonstration repository: https://github.com/Mossop/vscode-eslint-974
