### ISSUE TITLE
Language client is not ready yet

### ISSUE THREAD

**Issue by aeschli** [microsoft/vscode-eslint#986]
Got the following in the extension host log:

[4595:0605/172358.880980:INFO:CONSOLE(144)] "%c  ERR color: #f33 Language client is not ready yet: Error: Language client is not ready yet
    at b.sendNotification (/home/martin/.vscode-oss-dev/extensions/dbaeumer.vscode-eslint-2.1.3/client/out/extension.js:1:41373)
    at /home/martin/.vscode-oss-dev/extensions/dbaeumer.vscode-eslint-2.1.3/client/out/extension.js:1:102650
    at Emitter.fire (/home/martin/workspaces/vscode/out/vs/base/common/file:/home/martin/workspaces/vscode/src/vs/base/common/event.ts:587:16)
    at ExtHostConfigProvider.$acceptConfigurationChanged (/home/martin/workspaces/vscode/out/vs/workbench/api/common/file:/home/martin/workspaces/vscode/src/vs/workbench/api/common/extHostConfiguration.ts:154:34)
    at /home/martin/workspaces/vscode/out/vs/workbench/api/common/file:/home/martin/workspaces/vscode/src/vs/workbench/api/common/extHostConfiguration.ts:125:54
    at processTicksAndRejections (internal/process/task_queues.js:85:5)", source: file:///home/martin/workspaces/vscode/out/vs/platform/log/common/log.js (144)

**Comment by dbaeumer** [comment]
@aeschli did you execute the auto fix command. This is the only place were I sent custom messages which are affected by the client not being ready?
